### ISSUE TITLE
Ability to trigger event handlers manually.

### ISSUE THREAD

**Issue by mbostock** [mbostock/d3#100]
@RandomEtc suggests something like jQuery's [trigger](http://api.jquery.com/trigger/) operator. The docs suggest it creates a proper DOM event and dispatches it to the selected elements (plural?).

**Comment by kuanslove** [comment]
@mbostock  Hi, Mike. I got a similar question about triggering D3 drag action manually. Suppose there are two layers:  the top layer is a PATH, and bottom layer is a RECT, the path block the RECT.  How can I apply the drag action to RECT while still make the PATH respond to mouse over event?

**Comment by leishman** [comment]
+1

**Comment by mdcfrancis** [comment]
I'm currently using the following to trigger events on a selection.

     d3.selection.prototype.trigger = function( event ) {
         var e = document.createEvent('Event');
         e.initEvent( event, true, true);
         this.node().dispatchEvent( e );
         return this;
     }

I've also created a few other helpers for items such as scrollTop

**Comment by mbostock** [comment]
That is similar to the [selection.dispatch](https://github.com/d3/d3-selection/blob/master/src/selection-dispatch.js) method that is currently planned for D3 4.0. Though selection.dispatch dispatches an event to every selected node, not just the first one.

**Comment by mdcfrancis** [comment]
Ah yes so I would need an each in their to loop across all the events in the selection. In my use case I've only being using it in a scalar selection context. The below appears to work for the selection case. 

    d3.selection.prototype.trigger = function( event ) {
        var e = document.createEvent('Event');
        e.initEvent( event, true, true);
        this.each( function( d ) {
            this.dispatchEvent( e );    
        });    
       return this;
    }

**Comment by mbostock** [comment]
I don’t think you’re supposed to dispatch the same event more than once. If you want my recommendation, see the selection.dispatch implementation. :grin:

**Comment by pixelhijack** [comment]
+1

**Comment by bjkomer** [comment]
+1

**Comment by Wooyol** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

neolaocoon@naver.com 님께 보내신 메일 <Re: [d3] Ability to trigger event handlers manually. (#100)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by mbostock** [comment]
Closing as fixed in d3-selection for 4.0; see [*selection*.dispatch](https://github.com/d3/d3-selection#selection_dispatch).
