### ISSUE TITLE
.gravity() doesn't accept a function

### ISSUE THREAD

**Issue by emeeks** [mbostock/d3#1270]
I'd like to be able to adjust the effect of gravity based on the data bound to a force layout on a per-node basis, but it seems like gravity doesn't take a function, unlike charge and link strength.

**Comment by timerickson** [comment]
I would love this feature also, and my solution was very similar to @rpoconn . Why the insistence on handling it in the tick function when, as @blq points out, so many of the other parameters accept functions? It seems there is an issue with doing it the recommended way, as @rpoconn suggests, he tried it as recommended but wasn't able to get it to work satisfactorily that way.

**Comment by mbostock** [comment]
The new [d3.forcePosition](https://github.com/d3/d3-force#forcePosition) in [d3-force](https://github.com/d3/d3-force), part of [D3 4.0](https://github.com/mbostock/d3/tree/4), allows [*position*.strength](https://github.com/d3/d3-force#position_strength) to be specified as a function or a constant, satisfying this feature request. The *x* and *y* coordinates representing the focus may also be specified as functions.

And of course the new d3.forceSimulation is modular so you can also compose whatever custom forces you desire!
