### ISSUE TITLE
d3.geom.closest

### ISSUE THREAD

**Issue by syntagmatic** [mbostock/d3#1506]
A utility for computing the closest point between a target and set of points.

```javascript
var closest = d3.geom.closest()
  .metric(d3.distanceEuclidean); // default metric

var target = [1,1],
    points = [[0,1,],[0,2],[0,3]];

closest.points(points);

closest.to(target);
// returns [0,1];
```

This can serve the same function as d3.geom.voronoi in an interaction layer.

Example: [Voronoi lookup by closest point](http://bl.ocks.org/syntagmatic/6432815)

**Comment by mbostock** [comment]
D3 3.5 added [*quadtree*.find](https://github.com/d3/d3-quadtree#quadtree_find) which implements this functionality.
