### ISSUE TITLE
context menu triggers drag

### ISSUE THREAD

**Issue by eahutchins** [mbostock/d3#1627]
If you open a context menu on a node in a force layout (for example http://bl.ocks.org/mbostock/1021841), a drag is triggered when you release the menu button. I checked this with d3 version 3.3.9, both chrome (31.0.1612.0 dev) and firefox (slightly different incorrect behavior for 25.0) on linux x86_64.

**Comment by partap** [comment]
So if anybody is interested, I have a branch that fixes this situation here: https://github.com/partap/d3/tree/drag-buttons

I opened another issue (#2498) that turned out to be a duplicate, but it describes how to use the patch to prevent the right mouse button from initiating a drag.

**Comment by mbostock** [comment]
In [d3-drag](https://github.com/d3/d3-drag) (see d3/d3-drag@7e70ce18d7cd07ae60383fea374a952e326ed76a) I’ve added a *drag*.filter method which allows you to set a function to customize which mousedown or touchstart events the drag behavior will use to initiate a drag gesture. The default is:

```js
function filter() {
  return !d3.event.button;
}
```

This means the drag behavior will ignore mousedown on secondary buttons completely, so it’ll open the context menu without initiating drag. If you *want* to initiate a drag with the secondary buttons, you can do that by changing the filter—though presumably you’ll also want to prevent the default behavior by listening to the contextmenu event to prevent the context menu from also appearing.
