### ISSUE TITLE
Expose time.interval as a public class

### ISSUE THREAD

**Issue by lulingar** [mbostock/d3#1684]
Please correct me if I'm missing the correct use case, but I found it necessary for my purposes to add a line after the declaration of d3_time_interval that exposes that function to the user, like:
`d3_time.interval = d3_time_interval;`

I deemed that necessary in order to define a class that generates interval objects of a number of minutes (i.e. 15 or 20 minutes) with the same functionality as, say, `d3.time.minutes`.

**Comment by mbostock** [comment]
Closing as fixed in d3-time for 4.0. See [d3.timeInterval](https://github.com/d3/d3-time#timeInterval).
