### ISSUE TITLE
Pack layout padding in parent/child context 

### ISSUE THREAD

**Issue by VividD** [mbostock/d3#1686]
If a non-zero padding is applied to pack layout, this will affect minimal distance between siblings. However, a parent circle and its children circles could still touch, or have distance less than padding.

Example: http://jsfiddle.net/VividD/rfBRz/

There are some real world applications that would benefit if padding affected also parent/children distance (so that even a parent and child could never have distance less than padding) (an example would be labeling parents with text flowing along their circles). In fact, my personal impression is that such modified behavior of padding would be more intuitive for developers and users than present behavior.

Perhaps the most desirable resolution would be a new independent parameter called, let's say, parentPadding.

Please consider enabling pack layout to support such modified behavior of padding.

**Comment by mbostock** [comment]
Merging into d3/d3-hierarchy#7.
