### ISSUE TITLE
Scale Transform on Body Tag breaking all D3.mouse coordinates

### ISSUE THREAD

**Issue by LeeGDavis** [mbostock/d3#1787]
I working on an app that has a scale (webkit-transform) set on the body tag and it is throwing all the coordinates off provided by d3.mouse(container).  I don't know if this is actually a problem with D3 or the with the browsers representation of clientX/Y or PageX/Y when using transform scale.  In short I can't get accurate coordinates for dragging while this scaling is involved.

This is largely a repost of the issue I originally created at [D3 google group](https://groups.google.com/forum/#!topic/d3-js/EYnbizCA3LM).  While this was resolved by using offset and doing the matrix transforms manually, I would like to use the mouse points to more easily manage boundaries within various viewports.

I have also created another test to showcase this behaviour.  The larger you set the container holding the svg the more obvious the discrepancy.
http://jsbin.com/kuhiy/6/ or [edit](http://jsbin.com/kuhiy/6/edit)

Chrome: 33.0.1750.154 m
OS: Win 7X64
D3: 3.4.3

**Comment by mbostock** [comment]
Merging into d3/d3-selection#67.
