### ISSUE TITLE
d3.timer.replace and d3.timer.reschedule

### ISSUE THREAD

**Issue by mbostock** [mbostock/d3#1790]
Transitions currently use the internal d3_timer_active variable to reschedule the active timer and replace its callback function. It’d be nice if we made these methods public so that you can easily stub out the d3.timer API or use similar functionality when implementing complex custom animations.

**Comment by cool-Blue** [comment]
Have you also considered d3.timer maintaining a timers by name array? Or timers by id maybe.  It would be good if d3.timer returned an id and maintained a list, this would round out the proposed api nicely. It would also allow better management of the timer in the force layout for example. Currently, if you `.stop()` a force layout and restart it before `force.tick()` is called, you end up with two timers hitting the call-back and the animation runs at double speed.

**Comment by mbostock** [comment]
In 4.0, I’m planning on having d3.timer return a handle so that you can modify and cancel timers outside of the callback; see d3/d3-timer#5.

**Comment by mbostock** [comment]
Closing as fixed in d3-timer for 4.0.
