### ISSUE TITLE
Compatibility with jsFiddle and load XML/JSON/CSV files placed on Github 

### ISSUE THREAD

**Issue by lordbaco** [mbostock/d3#1828]
I am using jsFiddle to learn D3.js and 
I am using a special feature to load demo 
XML/JSON/CSV files placed on Github.
http://blog.jsfiddle.net/doc-api-github

This feature is very cool to load data
using d3.xhr from Github so you don't
need to run a local web server (python, etc.)
nor have issues with browser unable to load
local files. 

The only problem is that jsFiddle allow
only Ajax jQuery by checking the header
"X-Requested-With: XMLHttpRequest".
So they return the following error:
"Please use only with Ajax requests"

Can you set the default headers of d3.xhr to this?
.header("X-Requested-With", "XMLHttpRequest")
.header("Content-Type", "application/x-www-form-urlencoded")

Check out this example to load a JSON from GitHub:
http://jsfiddle.net/lordbaco/8KDg6/

Another project loading the XML from GitHub (use mouse wheel to zoom in/out)
http://jsfiddle.net/lordbaco/kVWNq/

P.S. Use jsFiddle+GitHub could be a nice alternative so people can hack/fork the code of D3.js Gallery currently hosted on http://bl.ocks.org/ and GitHub

Best Regards,
Guy Baconniere

**Comment by mbostock** [comment]
I’m not planning on implementing this, but thank you for the suggestion. This functionality has moved to [d3-request](https://github.com/d3/d3-request) for 4.0. I’ve added some documentation to the README there. It probably wouldn’t be hard to detect cross-domain requests as is already done to use XDomainRequest (specifically, `/^(http(s)?:)?\/\//.test(url)`), but I’m nervous about backwards-compatibility and I think it’s probably good for headers to be set explicitly anyway.
