### ISSUE TITLE
On Safari, d3.time.day returns 1 AM for some time zones (e.g., Moscow Standard Time)

### ISSUE THREAD

**Issue by ghost** [mbostock/d3#1846]
For example you can look at this page: http://bl.ocks.org/mbostock/3883195

As you can see, instead of a year is displayed "01 AM"
Do you know how to fix this bug?
![screen_for_d3](https://cloud.githubusercontent.com/assets/1280250/2698743/29f5c3ca-c3fe-11e3-9059-46036e0919a6.png)

**Comment by mbostock** [comment]
Some of these problems appear to have been fixed by browsers, and [d3-time’s interval](https://github.com/d3/d3-time/blob/master/src/interval.js) seems to be more robust than D3 3.x’s. So moving this to the icebox, and we should probably close it.

**Comment by mbostock** [comment]
Closing as fixed in d3-time for 4.0.
