### ISSUE TITLE
Listener for all dispatch events

### ISSUE THREAD

**Issue by gmaclennan** [mbostock/d3#1853]
It would be useful to be able to add a listener for all events on a dispatcher object. I'm not sure what syntax would make the most sense, but maybe like #1140 use:

    dispatch.on('.namespace', listener)

I have created a starting point for discussion gmaclennan@ab17c43 however this will overwrite all other events in `namespace`. One solution would be to use a reserved event type like `all` but I don't like that idea too much. The other option would be to internally add a namespace to the listener when `dispatch.on('.namespace', listener)` is called, so that internally it is registered as `name = namespace__all__` or something like that.

For this to be useful you would need to track the initiating event, which would probably mean adding a method to d3.event and making it available within `listener`.

**Comment by mbostock** [comment]
I’m not planning on implementing this, but thank you for the suggestion.
