### ISSUE TITLE
allow alignment of `ordinal.rangeRoundBands`

### ISSUE THREAD

**Issue by tpreusse** [mbostock/d3#1913]
`ordinal.rangeRoundBands` is very useful to create nice, sharp bar charts. To accomplish this it calculates error pixels and distributes them 50/50 to the start and end of the range.

However when creating a bar chart often an author wishes to left align it. Error pixels are also sometimes incorrectly identified as padding (probably in pursuit of alignment) - see https://github.com/mbostock/d3/issues/1592.

As an api consumer it would be nice to decide where those pixels go.

Code:
https://github.com/mbostock/d3/blob/master/src/scale/ordinal.js#L72
Maybe an additional parameter? `align`: center, default = `Math.round(error / 2)`, left = `0`, right = `error`.

**Comment by mbostock** [comment]
Nice idea. Filed d3/d3-scale#16 for 4.0.

**Comment by mbostock** [comment]
Fixed in d3/d3-scale#28 for D3 4.0.
