### ISSUE TITLE
partition layout overwrites data on other graph nodes

### ISSUE THREAD

**Issue by explunit** [mbostock/d3#1929]
See example here: http://bl.ocks.org/explunit/ab8cf15534f7fec5ac6d

While partition.nodes() seems to generate a new data structure (e.g if you give it some .key functions, it writes the extra properties (e.g. `x`, `y` `dx`, `dy`, `value`) to the underlying objects and does not wrap the data. Thus if the data structure is shared between multiple visualizations, these `x`, `y` `dx`, `dy`, `value` properties will bleed through to the other graphs in a "last graph wins" scenario.

In reading #1145 this seems to be treated as "by design", but perhaps it can be reconsidered in future version. It's inconsistent with Pie layout which wraps the original data in a `.data` property.

Discussion of workarounds [here](http://stackoverflow.com/questions/24499739).

**Comment by mbostock** [comment]
In [d3-hierarchy](https://github.com/d3/d3-hierarchy) for 4.0, the hierarchy layouts assign properties directly to the input nodes; however, the input nodes are typically wrapper objects around the original data created using [d3.hierarchy](https://github.com/d3/d3-hierarchy#hierarchy) or [d3.stratify](https://github.com/d3/d3-hierarchy#stratify). Furthermore, you can use [*root*.copy](https://github.com/d3/d3-hierarchy#node_copy) to create a copy of a hierarchy before computing a layout if you want to avoid overwriting a previous layout.
