### ISSUE TITLE
Allow AMD users to disable the global

### ISSUE THREAD

**Issue by gpgekko** [mbostock/d3#1945]
I can understand the recent change to create a global, even with an AMD loader present. However, I think a solution like used by Moment.js is much more elegant: http://momentjs.com/docs/#/use-it/require-js/.

It would involve some extra code to introduce an AMD configuration parameter to prevent the object of being globally exported. This will keep the behavior you have now, but it allows those who don't want to pollute their global namespace to keep things tidy.

Another option would be to make the changes they want to do, by going back to not creating a global by default for AMD and adding instructions how an user can export the object to the global namespace themselves. Though it's up to you to decide on that.

I'll see if I can find some time to create a pull request later today, it should be only a few lines of code.

**Comment by mbostock** [comment]
The global is going away in D3 4.0, where we are adopting Rollup’s standard UMD boilerplate.
