### ISSUE TITLE
.ticks() is ignored when zooming out in logarithmic scale

### ISSUE THREAD

**Issue by kraf** [mbostock/d3#1971]
Usually when zooming out, d3 is automatically updating the axes and removing ticks to fit the set ```.ticks()``` value, but in the below example it's not working. Instead it's just adding more and more ticks. Am I doing something wrong here?

http://codepen.io/anon/pen/Ebpne

**Comment by mbostock** [comment]
Fixed in d3-scale for D3 4.0; see d3/d3-scale#15.
