### ISSUE TITLE
Add support for cubic-bezier easing functions

### ISSUE THREAD

**Issue by idan** [mbostock/d3#1982]
Working with CSS, I've become accustomed to specifying easing curves using the [cubic-bezier notation (transition-timing-function)](http://www.w3.org/TR/css3-transitions/#transition-timing-function-property).

Nominally the format for specifying the curves is `(c1x, c1y, c2x, c2y)`. If you're unfamiliar with them, you can [experiment with them live](http://cubic-bezier.com/).

There's already a [fantastic (MIT-licensed) implementation: gre/bezier-easing](https://github.com/gre/bezier-easing).

I'd love to contribute to D3, and integrating this would be a good first patch for me to get my feet wet.

- [ ] I assume I'll be vendoring in the actual source, since d3 has zero dependencies
- [ ] Any other guidance before I convert this to a PR?

**Comment by kriede** [comment]
+1

**Comment by idibidiart** [comment]
+11

**Comment by mbostock** [comment]
This is now covered by d3/d3-ease#3. (Also see d3/d3-ease#14.)

**Comment by idan** [comment]
:heart_eyes: :sparkles: :cake: :tada:
