### ISSUE TITLE
Make jsdom an optional dependency in package.json

### ISSUE THREAD

**Issue by parkermalenke** [mbostock/d3#1986]
*First just wanted to say thanks to everyone involved for working on D3, this is a very cool project and I've enjoyed using it.*

To the point: jsdom is not actually a requirement if you use the npm version of D3 in the browser with a tool like browserify. There's a couple problems with marking it as a dependency in package.json:

- jsdom itself requires contextify, which can be pretty difficult to get set up on the windows platform. Marking the package as optional would let people completely avoid this irrelevant challenge if they just use D3 in the browser.
- Even if contextify installs easily on your platform that's an unnecessary step that introduces extraneous code for projects that only use D3 in the browser.

**Comment by mbostock** [comment]
Fixed in #2225, which demotes JSDOM to a development dependency only used for D3’s tests.

**Comment by natevw** [comment]
Whoohoo, thanks! The way things are now handled (checking nodes to determine their context) sounds excellent.

**Comment by vinimxit** [comment]
What are the commands to install d3 and c3 without dependency on python and contextify?

**Comment by mbostock** [comment]
I can’t comment on c3, but for d3, a simple `npm install d3` should install without any dependencies. Like so:

```bash
$ npm install d3
d3@3.5.5 node_modules/d3
$
```
