### ISSUE TITLE
Empty line segments not displayed in d3.svg.line.

### ISSUE THREAD

**Issue by kraf** [mbostock/d3#2061]
I can't get a line chart to display single points. In SVG it get's rendered as a dot when I move the pen to a point and then do a line to with the same coordinates (at least with a linecap different than "butt"). I noticed that d3.svg.line just creates the moves of the pen. Is this intentional?
I provided an example: http://jsfiddle.net/ntdwa4dv/1/

**Comment by mbostock** [comment]
Fix staged in #2591 for 3.5.7.

**Comment by mbostock** [comment]
http://bl.ocks.org/mbostock/bbbe5171af94cc4b18c1
