### ISSUE TITLE
Examples gallery broken (again)

### ISSUE THREAD

**Issue by couchand** [mbostock/d3#2078]
In re: #1822, the sidebar seems to have been added again.  It's still hideous, and it's still breaking the Examples gallery.

Let's 86 it once more!

**Comment by muan** [comment]
I fixed this in `0953d5c`, https://github.com/mbostock/d3/wiki/Gallery/_history. I'll leave this for someone else to verify (and close). The fixes should continue to work if/when the sidebar is removed again.

The original issue is in Firefox, so here are the before afters in Firefox & Chrome for comparison:

## Firefox – before

![image](https://cloud.githubusercontent.com/assets/1153134/5664535/f1802a8c-978b-11e4-8983-c38a3c3f2f4b.png)

## Firefox – after (fixed)

![image](https://cloud.githubusercontent.com/assets/1153134/5664538/f7b25d30-978b-11e4-8931-b6b42a6cbaa5.png)

---

## Chrome – before

![image](https://cloud.githubusercontent.com/assets/1153134/5664509/da7b7e90-978b-11e4-96d8-7dbf339e46e4.png)

## Chrome – after

![image](https://cloud.githubusercontent.com/assets/1153134/5664541/fe8692fc-978b-11e4-8b18-6b25f2e45997.png)

**Comment by mbostock** [comment]
Someone inexplicably reverted your fix, so I just made another set of fixes myself. Thanks for the report.
