### ISSUE TITLE
Sort ascending, by key

### ISSUE THREAD

**Issue by gka** [mbostock/d3#2088]
This would be so useful to have in D3:

```js
d3.ascendingKey = function(key) {
   return function (a, b) {
      return a[key] < b[key] ? -1 : a[key] > b[key] ? 1 : a[key] >= b[key] ? 0 : NaN;
   };
}
```

Alternatively also supporting accessor functions, but I think that's less often needed and possibly inefficient:

```js
d3.ascendingKey = function(key) {
   return typeof key == 'function' ? function (a, b) {
          return key(a) < key(b) ? -1 : key(a) > key(b) ? 1 : key(a) >= key(b) ? 0 : NaN;
      } : function (a, b) {
          return a[key] < b[key] ? -1 : a[key] > b[key] ? 1 : a[key] >= b[key] ? 0 : NaN;
      };
}
```

**Comment by axelson** [comment]
FYI if you use https://github.com/gka/d3-jetpack you get `d3.ascendingKey` and `d3.descendingKey` functions.

**Comment by mbostock** [comment]
I’m not planning on adding these to 3.x, but hopefully 4.0’s module system will make it easier to bundle plugins like d3-jetpack.
