### ISSUE TITLE
Document which default locales are available

### ISSUE THREAD

**Issue by andrioni** [mbostock/d3#2147]
[The documentation page on locales](https://github.com/mbostock/d3/wiki/Localization) doesn't inform that there are already [some default locales available for some languages](https://github.com/mbostock/d3/tree/master/src/locale). Should this information be added? Should I just edit the documentation wiki?

**Comment by mbostock** [comment]
Feel free to edit the wiki. For 4.0, I link to the locales from the documentation (see [d3-format](https://github.com/d3/d3-format#localeFormat) and [d3-time-format](https://github.com/d3/d3-time-format#localeFormat)), and I also make the locales available in the default build using a locale code.
