### ISSUE TITLE
allow `d3.layout.force().chargeDistance` to take a function

### ISSUE THREAD

**Issue by mhelvens** [mbostock/d3#2158]
A number of settings on the `d3.layout.force()` object are dynamic, like `linkStrength`, `linkDistance` and `charge`. They take a function, so the value can be different for each node or link.

This seems to not be the case for `chargeDistance`. Is there a reason for this? It would come in handy for me at the moment. I have a number of isolated groups of nodes with their own gravity and enforced bounds, but still with occasional inter-group links. Having the `chargeDistance` be limited to the group size of each particular node would help both performance and visible behavior.

**Comment by mikeazo** [comment]
Looking at the code in https://github.com/mbostock/d3/blob/master/src/layout/force.js, it doesn't look like this would be too hard to do. I agree it would be useful. I'll see what I can hack together.

**Comment by IPWright83** [comment]
I actually need this too and was going to take a look to see how difficult it is. @mikeazo how've you got on at looking at it? 

My use case is that I want nodes to repel each other and to use the chargeDistance to prevent overlaps in a soft way - making nodes gradually move away from each other rather than a sudden snap.

**Comment by mgold** [comment]
*reads docs* I wonder if you can achieve the desired effect with `linkDistance` or `linkStrength`, which both take functions? All functions in this layout are evaluated when the layout starts, so the same style of function may not be helpful if you want nodes to dynamically adjust the charge distance. The other reason I can think of is performance, say, that per-node charge distances may be incompatible with the [Barnes Hut algorithm](http://arborjs.org/docs/barnes-hut), but I'm not certain. That's al Devil's Advocate though - if it's possible to take a function, it should take a function.

**Comment by mikeazo** [comment]
@IPWright83 I ended up finding a work around by tweaking some of the other force layout functions, similar to what @mgold suggests.

**Comment by IPWright83** [comment]
@mgold I'm not sure if it would properly, or you'd at least require quite some tweaking. The charge only operates over a certain distance, whereas the links operate regardless of how far things are apart (so you'd have to dynamically set the linkStrength to 0 when over a distance threshold and automatically scale it based on the distance so nodes far away don't suddenly ping close).

**Comment by mikeazo** [comment]
@IPWright83 what you are suggesting is what I ended up doing. It worked well in my case, not sure if it would work in all cases. I made the linkStrength a function that would be dynamically calculated. In my case, I did it based on some properties of the end points as that is what I needed. Theoretically you could compute the length of the link and change the linkStrength accordingly.

That said, I still think that having chargeDistance could be useful in certain scenarios.

**Comment by mhelvens** [comment]
Also, link strength / distance only operates between nodes that are *linked*. Charge applies between *all* nodes. Similar but different.

**Comment by IPWright83** [comment]
@mhelvens that is true, I don't know if there's a quad tree underneath to reduce the affect of charge based on distance. In my case I'd have to link every single node (which prohibits using links for something else)

**Comment by mhelvens** [comment]
@IPWright83: Which is the #1 reason I can't use this... hack. For my scenario, charge distance taking a function is really the only way.

When calculating the charge between two nodes with a different charge distance, I'm sure something appropriate could be done.

**Comment by mbostock** [comment]
The charge is a global force, so it can’t be customized on a per-node basis (or per pair of nodes). However, it would be possible to compose multiple charge forces that affect different subsets of nodes, such that each charge force is local to the subset. See d3/d3-force#2.

**Comment by mbostock** [comment]
Composable forces have been implemented in [d3-force](https://github.com/d3/d3-force) for D3 4.0.
