### ISSUE TITLE
D3 and Shadow DOM

### ISSUE THREAD

**Issue by pemrouz** [mbostock/d3#2161]
@mbostock @jasondavies 

There seems to be some strange cases where D3 doesn't work properly with the Shadow DOM. I've created an example page to demonstrate one (`.append('textarea')`) of them here: 

http://bl.ocks.org/pemrouz/4a3e7ce9322c091ec058

**Comment by mbostock** [comment]
Fixed in #2227 for 3.5.4.

**Comment by pemrouz** [comment]
:+1:
