### ISSUE TITLE
Make locale files available with bower

### ISSUE THREAD

**Issue by greg0ire** [mbostock/d3#2166]
As [I described here](https://github.com/mozilla/metrics-graphics/issues/285#issuecomment-67841443), getting an i18n d3 involves copying a locale file in my project. I'd rather have this file in `bower_components/d3`. I did not reuse the file exactly as is, I removed the `import "locale";` line (not sure what it does).

**Comment by wytrych** [comment]
Why not have the locales imported in the source code, so it can be easily accessible with d3.locale.nl_NL for instance? I know it will bring a few more lines in the code, but it's not that much compared to the size of the library.

**Comment by greg0ire** [comment]
Sorry for the late reply, I was on holiday. I now locale files are not big, but I am not the maintainer of that, therefore it should not managed in my VCS, but by bower.

**Comment by mbostock** [comment]
In 4.0 the default build will include all available locales.

**Comment by mbostock** [comment]
Closing as fixed in D3 4.0.

**Comment by wytrych** [comment]
Thanks!
