### ISSUE TITLE
Update to JSDom 1.5.0

### ISSUE THREAD

**Issue by peller** [mbostock/d3#2180]
Significant performance improvements since 1.0.0 should help D3, such as NodeList iteration and insertion.  See https://github.com/tmpvar/jsdom/issues/694

**Comment by mbostock** [comment]
Sounds good. Though, I have also been thinking about removing the JSDOM dependency entirely, and instead changing D3 to rely an externally-provided document. This way, you can use D3 with whatever DOM you desire, and Windows users won’t run into so many issues trying to install Contextify.

**Comment by fczuardi** [comment]
not only windows users, any iojs or node unstable users as well, see https://github.com/brianmcd/contextify/issues/149

**Comment by greim** [comment]
D3 is a fairly popular module that won't install on io.js (for reasons mentioned above). Here's a link to io.js's own thread documenting such modules. https://github.com/iojs/io.js/issues/456

**Comment by mbostock** [comment]
Closing in favor of #2225, which demotes JSDOM to a development dependency used only for tests. (I also upgraded to JSDOM 3.x, but it’ll only benefit the tests.)

**Comment by mbostock** [comment]
Fixed in 3.5.4.
