### ISSUE TITLE
enterSelection.select does not accept a string argument

### ISSUE THREAD

**Issue by chrisprice** [mbostock/d3#2182]
Selection behaviour -
```
d3_selectionPrototype.select = function(selector) {
...
  selector = d3_selection_selector(selector);
...
        subgroup.push(subnode = selector.call(node, node.__data__, i, j));
...
};
```

Enter selection behaviour -
```
d3_selection_enterPrototype.select = function(selector) {
...
        subgroup.push(upgroup[i] = subnode = selector.call(group.parentNode, node.__data__, i, j));
...
};
```

Is this expected behaviour?

**Comment by mgold** [comment]
95% of the time you call `.append("tagName")` right after `.enter()`. And because the elements are placeholders, selectors don't really make sense. I suspect that the implementation of .select for the enter selection is an implementation detail. 

In _How Selections Work_, we read, "The implementation of enter.select is then specialized such that nodes are inserted into the group’s parent, replacing the placeholder." And indeed, selection.append (which is not overridden for enter selections) makes use of select, passing it a function. From the docs: "The _selector_ [argument] may also be specified as a function that returns an element, or null if there is no matching element."

That's my guess, though I'm interested in what Mike has to say. (Also, this might be better on the mailing list.)

**Comment by chrisprice** [comment]
My use case is to allow decoration of the update selection (and implicitly the enter/exit selections) from a user supplied function e.g. -

```
...
an.example = function(selection) {
    var updateSelection = selection.selectAll('g.example')
        .data(...);
    updateSelection.append('g')
        .attr('class', 'example');
    ...
    decorate(selection);
};
...
var example = an.example()
    .decorate(function(updateSelection) {
        updateSelection.enter()
            .select(function() {
                return d3.select(this).select('g.example').node();
            })
            .doStuff...
    });
```

The workaround shown above (of passing a function to ```enterSelection.select```) works fine but seems unnecessary. If it's just a case of no-one has asked to do this before and there's nothing inherently wrong with it, then I'm happy to create a PR.

**Comment by mgold** [comment]
Hmm. I suspect that if you get to know d3 idioms better, there will be a way to accomplish what you want. I could be totally off-base here but I'll give it a go.

You're appending to the update selection, which is weird - I actually had to try it out:
````js
d3.selectAll("p").data(d3.range(12)).size()
12
d3.selectAll("p").data(d3.range(12)).append("p").size()
12
````
That's probably not what you want.

If you want to apply a function to the enter and update selections, you should know that enter merges with update after you append to it. So, basing this off the docs for enter,

````js
var updateSelection = selection.selectAll('g.example').data(...);
updateSelection.attr(/* operate on old elements only */)
updateSelection.enter().append("g").attr('class', 'example') /* operate on new elements only */
updateSelection.call(decorator) /* pass selection of old and new elements to decorator */
updateSelection.exit().remove() /* complete the enter-update-exit pattern */
````

**Comment by mbostock** [comment]
The reason enter.select doesn’t take a string is that it’s called on placeholder nodes which are by definition empty — there is nothing inside placeholder node to select, and furthermore the placeholder nodes won’t have a querySelector or querySelectorAll method defined, so it will simply crash. Therefore, the only thing you can do with enter.select is create and append a new element, as enter.append does. 

Note that you can also pass a function to enter.append, which allows to you override how elements are created, while still appending them (as in the [Clone Templates example](http://bl.ocks.org/mbostock/9360565)). You can also pass a function to enter.select if you want to change how elements are appended (say to use something besides appendChild or insertBefore); but I’ve never seen a case where this is necessary.

**Comment by chrisprice** [comment]
Thanks to both of you for taking the time to explain things, this was indeed rooted in my misunderstanding of the enter selection...

The example use case I posted contained a typo which I think added to the confusion, it should have read ```updateSelection.enter().append('g')```. However, it was still an invalid technique, as I found out when I tried to create an example gist with more than one item in my data array.
