### ISSUE TITLE
How to use d3 and date format with years before Christ?

### ISSUE THREAD

**Issue by GixPix** [mbostock/d3#2185]
I have some data in JSON format I need to import it to build a scatter plot with d3. The problem is that the records have some dates referred to years before Christ born, for example 400 B.C. Is it possible to format it in a way that d3 accepts?

**Comment by mbostock** [comment]
No special treatment is required to specify B.C. dates; D3 uses standard JavaScript dates, so you’ll need to specify a negative year for years before 0. D3 does not support an “A.D.” or “B.C.” directive, however, so if you want to include that in the formatted year, you’ll need to write your own custom formatter or consider using a different date formatting library that supports this feature.
