### ISSUE TITLE
improving d3 layout tree with html content instead of single title

### ISSUE THREAD

**Issue by meva86** [mbostock/d3#2186]
I would like to extend the collapsible tree layout of the d3js 
(http://mbostock.github.io/d3/talk/20111018/tree.html) with the 
following functionality: in the nodes they would like to be able to 
specify not only a title, but html content (let's say a div element). It 
should be able to get its size, and automatically calculate the 
positions of the nodes.
I've attached an example, where the red boxes are the specified html 
contents (instead of simple one line title).

Is somebody open to do it in a payed project? If yes, please contact me!

![collapsible-tree-improved](https://cloud.githubusercontent.com/assets/10498385/5703579/b744faca-9a68-11e4-8f0d-023ffdca58e4.png)

**Comment by jasondavies** [comment]
Hello!  These GitHub issues are for bug reports and feature requests only.  Please use [StackOverflow](http://stackoverflow.com/questions/tagged/d3.js) or the [d3-js group](https://groups.google.com/d/forum/d3-js) for help, or you might want to try the [data-vis-jobs group](https://groups.google.com/d/forum/data-vis-jobs) if you want to find a contractor.

**Comment by mgold** [comment]
@jasondavies Might be time to revise CONTRIBUTING.md ...

**Comment by jasondavies** [comment]
Good idea!  Proposed fix in #2188.

**Comment by meva86** [comment]
Hello,
thank you very much and sorry for the off topic.

**Comment by mgold** [comment]
No worries @meva86, you are hardly the first.
