### ISSUE TITLE
geo.projection wiki page (docs) missing

### ISSUE THREAD

**Issue by mgold** [mbostock/d3#2187]
The [url](https://github.com/mbostock/d3/wiki/Geo-Projections) results in GitHub asking to create a wiki page, which means that it doesn't exist.

It's definitely the right page, since it's linked to from pages like [API Reference](https://github.com/mbostock/d3/wiki/API-Reference#d3geo-geography) and [Geo](https://github.com/mbostock/d3/wiki/Geo). The wayback machine [has a copy](https://web.archive.org/web/20130829020150/https://github.com/mbostock/d3/wiki/Geo-Projections) from August but hopefully you have a more recent one, or have some magic admin button.

And no, I have no idea how or when this happened.

**Comment by jasondavies** [comment]
Fixed, thanks!
