### ISSUE TITLE
Adding a new chart to raw.density from the d3 Gallery

### ISSUE THREAD

**Issue by symes1** [mbostock/d3#2197]
Hi guys I'm new to Raw and Git Hub. There seems to be a provision to add a chart to raw, however, when you click on Add chart it takes you to Git Hub but where how you add the chart is so far a mystery. Can anyone help?? (I'm trying to create a graphic from a sample of excel data).

**Comment by jasondavies** [comment]
Sounds like a question for [RAW](https://github.com/densitydesign/raw), not D3.
