### ISSUE TITLE
Feeding External Data

### ISSUE THREAD

**Issue by FRadice1977** [mbostock/d3#2198]
Does this still work for feeding external data into a interactive bar graph. I have not been able to get it to work, when applying this code to the .js file: 
                d3.tsv ('data.tsv', function(data){})
                for(key in data){bardata.push(d)[key].value
If someone could give me the code or a simple example a chart or graph being pushed by external data, that would really help me.

**Comment by jasondavies** [comment]
Sounds like a question for [StackOverflow](http://stackoverflow.com/questions/tagged/d3.js) or the [d3-js group](https://groups.google.com/d/forum/d3-js); these GitHub issues are for bug reports and feature requests only.  Thanks!

**Comment by FRadice1977** [comment]
Thanks for your reply. Cheers!
