### ISSUE TITLE
Use .attr() instead of .style() for axis label's "text-anchor" assignment.

### ISSUE THREAD

**Issue by floledermann** [mbostock/d3#2199]
I opened pull request #2102 for this a while ago, but couldn't get any attention to it so opening an issue too. d3 is using attr() for visual attributes pretty much everywhere else in the code, so maybe there's some reason I've overlooked for specifically using style() here, but from what I see there should be no reason to not use attr() for assigning the text-anchor value and therefore allow the default to be overridden by CSS (for example for horizontally centered labels on vertical axis).

**Comment by jasondavies** [comment]
Thanks for the reminder.  I’m closing this issue in favour of the pull request.
