### ISSUE TITLE
GaussianBlur Doubt

### ISSUE THREAD

**Issue by eduardoperez2151** [mbostock/d3#2200]
Hi , i am using D3 and transition and i have a doubt how can i make a transition from a circle without gaussain blur to a other circle with gaussian blur effect .
i will pareciate your help, thanks.
Regads ,
Eduardo.

**Comment by jasondavies** [comment]
Sounds like a question for [StackOverflow](http://stackoverflow.com/questions/tagged/d3.js) or the [d3-js group](https://groups.google.com/d/forum/d3-js); these GitHub issues are for bug reports and feature requests only.  Thanks!
