### ISSUE TITLE
Using order() or sort() breaks animated CSS class changes

### ISSUE THREAD

**Issue by keithng** [mbostock/d3#2202]
When the order of nodes are changed using order() or sort(), animated CSS class changes break.

Example here: http://jsfiddle.net/keithng/6k9frgrs/2/

In the example, the top middle circle and the bottom middle circle are swapped. When the class is added, transitions for all the elements *between* the elements which have been swapped are broken. Those elements are in the same place as they were before the swap. Elements *after* the swap are okay though.

This only seems to happen if the reordering happens in the same mouse event as as the class change.

The use-case for this is I'm making a visualisation with heavy dynamic layering requirements, and the reordering required to make the layers work are breaking all my class transitions.

![screenshot - 220115 - 22 02 13](https://cloud.githubusercontent.com/assets/1203875/5856938/5caa116e-a282-11e4-804c-a5bfb3a8867b.png)

**Comment by mbostock** [comment]
Unfortunately, I don’t think there’s any way to avoid this; using selection.order or selection.sort requires re-appending those elements to the DOM to change their order. (If they are actually out-of-order: we avoid re-appending elements if they are already in-order for performance reasons.) Re-appending or re-inserting is the only way to change the order of elements in the DOM.

So, if you want to use CSS transitions, you’ll need to avoid using selection.order or selection.sort. Alternatively, you’ll need to write some code to restart your transitions where they were interrupted after the re-order.
