### ISSUE TITLE
Create a fictional world and visualize the topojson

### ISSUE THREAD

**Issue by kwoxer** [mbostock/d3#2203]
I'm not able to ask in the Google Groups forum somehow. So I ask here.

My question is how can a create a **fictional** world and visualize it with d3 afterwards. So using the official world maps is working fine. After that I created my own with QGIS, that was also fine. I created the shp file there and with mapshaper I got the topojson. 

But that I wanted to go a bit bigger. And so I reached high numbers. And somehow the projection or so cannot handle that. http://stackoverflow.com/questions/28075867/qgis-generated-shapefile-malformed-when-converted-to-topojson-by-mapshaper/28099909#28099909

That's why I wanted to ask. How is the best approach to create fictive maps. The best would be a projection. I for sure have knowledge about the kilometers.

**Comment by jasondavies** [comment]
Sorry, this isn’t the best place to ask for help; the GitHub issues are meant for bug reports and feature requests only.  Try [StackOverflow](http://stackoverflow.com/questions/tagged/d3.js) or the [d3-js group](https://groups.google.com/d/forum/d3-js).
