### ISSUE TITLE
Use CustomEvent for event dispatching.

### ISSUE THREAD

**Issue by mbostock** [mbostock/d3#2204]
It’d be nice if custom events, like those used by the zoom behavior, were done through the CustomEvent standard. This would allow you to register a listener based solely on an element plus an event name, rather than needing a reference to the zoom behavior object. (However, it’s not clear how to apply this strategy to objects that emit events and are not bound to elements, such as a force layout.)

**Comment by IPWright83** [comment]
Would this enable me to define new events that could be used through out D3? 

I'm building an application at the moment and want both a `click` and `double click` behavior, but want to fire either one or the other. I keep having to use the same pattern everywhere I want this but haven't figured out how to define in a way that I can re-use it. In fact I've not even figured out how to define it like the zoom behavior :(

**Comment by mbostock** [comment]
Implemented as [*selection*.dispatch](https://github.com/d3/d3-selection#selection_dispatch) in [d3-selection](https://github.com/d3/d3-selection) for [D3 4.0](https://github.com/mbostock/d3/tree/4).
