### ISSUE TITLE
transfering an infographicto raw.density

### ISSUE THREAD

**Issue by symes1** [mbostock/d3#2206]
Hi, I'm a newbie and wondered if anyone could tell me how to add a graphic from the library.....Cheers

**Comment by jasondavies** [comment]
Duplicate of #2197.  These GitHub issues are for bug reports and feature requests only.  Please use [StackOverflow](http://stackoverflow.com/questions/tagged/d3.js) or the [d3-js group](https://groups.google.com/d/forum/d3-js) for help.
