### ISSUE TITLE
Var hoisting masking value from outer scope

### ISSUE THREAD

**Issue by mckamey** [mbostock/d3#2207]
I'm reading through the d3 force implementation and it looks like there might be a typo. [On line 260 of force.js](https://github.com/mbostock/d3/blob/master/src/layout/force.js#L260), `m` is being used as a closure from the outer scope: 

    for (j = 0; j < m; ++j) /*...*/

where it is being initialized from the outer scope to `links.length`. Then a few lines later on it is being initialized:

    var /*...*/ m = candidates.length, /*...*/
    while (++j < m) /*...*/

But my thought (besides the fact that it is unclear to use `m` with two meanings) is that the function scoping combined with var hoisting may be obscuring the `links.length` value with `undefined`? The two usages were added during different commits, so I'm wondering if it is unintended that `m` was reused.

The side effect is that the loop on line 260 never executes because `j < undefined` is always `false`;

**Comment by mbostock** [comment]
Good catch!

**Comment by mbostock** [comment]
Fixed in #2227 for 3.5.4.
