### ISSUE TITLE
support rebeccapurple = #663399

### ISSUE THREAD

**Issue by targumon** [mbostock/d3#2208]
Please add
`rebeccapurple: 6697881`
to the d3_rgb_names map.

TIA!

Referecnes:
http://lists.w3.org/Archives/Public/www-style/2014Jun/0312.html
https://developer.mozilla.org/en-US/docs/Web/CSS/color_value

**Comment by vladh** [comment]
@targumon, not entirely sure where you got that number, `0x663399 = 6697881` if I'm not mistaken.

**Comment by targumon** [comment]
@vladh I'm not sure where I got this number as well :-) you're right. corrected.

**Comment by mbostock** [comment]
Fixed in #2227 for 3.5.4.
