### ISSUE TITLE
Is it possible to add a watermark to a line chart?

### ISSUE THREAD

**Issue by romanrdgz** [mbostock/d3#2212]
Is it possible to add a watermark as background image to a line chart created with D3.js? I have been searching at google and among past issues, but haven't been able to find anything. Is there any example for that out there?

**Comment by jasondavies** [comment]
These GitHub issues are for bug reports and feature requests only.  Please use [StackOverflow](http://stackoverflow.com/questions/tagged/d3.js) or the [d3-js group](https://groups.google.com/d/forum/d3-js) for help.
