### ISSUE TITLE
Please update meteor package to 3.5.3

### ISSUE THREAD

**Issue by bobiblazeski** [mbostock/d3#2214]
As of today 2015.01.29 meteor is still at 3.4.13. Could you please update it to latest 3.5.3

**Comment by garrilla** [comment]
if you're talking about the d3js:d3 this might need to involve @dandv or refer to #2130 - not sure that was an attempt to get a an official d3 package for meteor was even concluded

**Comment by bobiblazeski** [comment]
Atmosphere documentation looks like its official by @mbostock not an wrapper . Thanks anyway will write to @dandv
