### ISSUE TITLE
Add ability to draw paths directly onto CanvasPixelArray

### ISSUE THREAD

**Issue by devTristan** [mbostock/d3#2224]
So you know what's even cooler than using d3 to draw paths on canvas?

Doing it in a background thread that doesn't lock up the UI.

This is definitely a wishlist type of deal.

```javascript
var path = d3.geo.path()
  .projection(projection)
  .pixelArray(myCanvasPixelArray);

path(someGeoJSONFeaturesOrWhatever);
```

If d3 can draw to canvas pixel arrays, then drawing can be done from within a web worker, freeing the UI thread to do UI stuff.

I'm aware that this is a difficult proposition, and not necessarily strictly within the scope of what d3 does. Still, though, it'd be a game changer.

**Comment by mbostock** [comment]
Are you proposing that D3 draw by manipulating a pixel array directly (i.e., D3 should implement rasterization) rather than using the Canvas 2D context? Interesting idea, but it would be an impossibly huge amount of work.
