### ISSUE TITLE
Remove generated d3.js & d3.min.js from git repository.

### ISSUE THREAD

**Issue by mbostock** [mbostock/d3#2226]

**Comment by mbostock** [comment]
Unfortunately, this is dependent on Bower implementing its own registry (or, even better, pulling from GitHub release assets).

**Comment by voltcode** [comment]
Will generated min.js be accessible from elsewhere? It's actually very useful for non-node developers to just download the right min.js directly.

**Comment by mbostock** [comment]
Yes, it is available in the d3.zip attached to [every release](https://github.com/mbostock/d3/releases), on the [official website](http://d3js.org/d3.v3.min.js) (albeit not yet served via HTTPS), and via package managers such as [NPM](https://www.npmjs.com/package/d3) and [Bower](http://bower.io/search/?q=d3).

**Comment by mbostock** [comment]
Bower assets have been moved to https://github.com/mbostock-bower/d3-bower.
