### ISSUE TITLE
interpolateHcl direction

### ISSUE THREAD

**Issue by ccorcos** [mbostock/d3#2231]
I can't seem to get this to work:

```
color = d3.scale.linear()
  .domain([0,1])
  .range(["#61312B", "#948636"])
  .interpolate(d3.interpolateHcl);
```

It seems to be interpolating the "other" way around... Ideally, I'd like to scan through all the hues..

**Comment by mgold** [comment]
Have you tried reversing the domain and/or range?

**Comment by ccorcos** [comment]
Just tried it. All combinations of reversing the domain and/or range. Didn't work.

It makes sense based on the documentation. It says it will take the shortest path and this indeed is -- I didn't realize it wraps around the other way. But now I don't get all the Hue I'm looking for...

**Comment by mgold** [comment]
How about a polylinear scale? Just add more values (presumably the hue you want) to the range, and sorted domain values to match. Downside: unequal interpolation in the different parts of the scale unless you're careful in choice of domain value.

**Comment by ccorcos** [comment]
Hmm... I tried this:

```
color = d3.scale.linear()
  .domain([0,1])
  .range(["#4D261F","#573649","#395267","#206B5D","#5E793B","#A97839"])
  .interpolate(d3.interpolateHcl);
```

Still doesn't got through all the hues listed there... My syntax may be wrong though

**Comment by mgold** [comment]
The length of the domain and of the range must be equal.

**Comment by mbostock** [comment]
When you use a polylinear scale the domain and range must have the same number of elements. So, you’d need to space your domain values equally to insure that you interpolate through your range values consistently.

d3.interpolateHcl is doing the right thing here; it’s documented to use the shortest-path and most of the time that’s what you want. I would recommend glancing at the Cubehelix examples if you are considering interpolating through huespace:

http://bl.ocks.org/mbostock/11413789
http://bl.ocks.org/mbostock/11415064
http://bl.ocks.org/mbostock/310c99e53880faec2434

If you really want to implement manually through HCL colorspace, you should write your own interpolator. You could perhaps build it off of d3.interpolateObject but I think I’d probably do something like this:

```js
var scale = d3.scale.linear()
    .range(["#61312B", "#948636"])
    .interpolate(interpolateHcl);

function interpolateHcl(a, b) {
  a = d3.hcl(a);
  b = d3.hcl(b);
  var h = d3.interpolateNumber(a.h, b.h),
      c = d3.interpolateNumber(a.c, b.c),
      l = d3.interpolateNumber(a.l, b.l);
  return function(t) {
    return d3.hcl(h(t), c(t), l(t));
  };
}
```
