### ISSUE TITLE
Semantic zoom for a stacked bar chart with timeline

### ISSUE THREAD

**Issue by milheiros** [mbostock/d3#2232]
Hi,

I'm learning all about D3 by myself and I have a lot of questions and confusions in my head.
I have a stacked bar chart using a timeline. My dataset uses data with this format:"Y-m-d".

I need to implement zooming (perhaps semantic zooming) who be able to transpose from bars by year to month or even bars by day. My implantation of geometric zoom works:

container.selectAll(".rgroups rect").attr('transform', 'translate(' + d3.event.translate[0] + ')scale(' + d3.event.scale + ',1)');

But my chart stays with the same bar width. So, when I navigate to days, my bar still have the same width as when I see in year format.

You can see an example here: http://jsfiddle.net/milheiros/m4bLbg3q/

Sorry, this is my first issue here. I've putted some issues in stackoverflow too.
I really need some kind of help. I'm very confused here...

Thanks in advance,
Filipe

**Comment by jasondavies** [comment]
These GitHub issues are for bug reports and feature requests only.  Please use [StackOverflow](http://stackoverflow.com/questions/tagged/d3.js) or the [d3-js group](https://groups.google.com/d/forum/d3-js) for help.

**Comment by milheiros** [comment]
Sorry Jason,

I've realize that after create this... it's already in d3-js group.
Thanks,
