### ISSUE TITLE
int keys in nest function become strings

### ISSUE THREAD

**Issue by barrybecker4** [mbostock/d3#2235]
Not sure if this is a bug in the code or in the doc, but when I run the example here
https://github.com/mbostock/d3/wiki/Arrays#-nest
I see the keys as strings and not ints.
the doc says 
  {key: 1931, values:...
but I see 
  {key: "1931", values:...

**Comment by jasondavies** [comment]
Looks like a bug in the example: d3.nest, d3.map and d3.set all use string keys at the moment due the way they’re implemented internally.  It’s mentioned in the documentation, though somewhat buried:

> The key function will be invoked for each element in the input array, and must return a string identifier that is used to assign the element to its group.

I’ve fixed the bug in the example.  Thanks for the report!
