### ISSUE TITLE
Weird behavior using d3 transitions in Desktop Chrome and Opera

### ISSUE THREAD

**Issue by Kelt** [mbostock/d3#2239]
Have a table with two rows, each row has 2 cells ...

upon "Updater" button click i animate rows 20px down and animate number in first cell to next hundred ...

Works fine apart from Desktop Chrome and Opera, where the 2nd number stops animating after 1st update. However upon DOM inspection i see the updated value is there ...

Seems more like a browser issue, I just want to verify?

More info, STR and working example here ...

http://bl.ocks.org/Kelt/5f00aae668a37c84b62f

Thanks

**Comment by jasondavies** [comment]
Looks like a Chrome bug; seems to be fixed in Chrome Canary.

**Comment by maximaxi131** [comment]
i think so 2
