### ISSUE TITLE
Combination of horizontal tree layout, rectangles and wrapped text seems impossible

### ISSUE THREAD

**Issue by lordplagus02** [mbostock/d3#2242]
I have been struggling for days to create a d3 tree layout that is horizontal, uses rectangles instead of circles, and has long text labels wrapped inside those rectangles. It doesn't seem like this is possible at this point. Unless it is and there's a way that I'm not aware of...?

**Comment by israelst** [comment]
Hello @lordplagus02, you are suspecting a bug? It's not very clear of what is the problem, could you share some code?

**Comment by jasondavies** [comment]
These GitHub issues are for bug reports and feature requests only.  Please use [StackOverflow](http://stackoverflow.com/questions/tagged/d3.js) or the [d3-js group](https://groups.google.com/d/forum/d3-js) for help.
