### ISSUE TITLE
Add an option in brush to return brush ranges on .extent() call

### ISSUE THREAD

**Issue by jfarid27** [mbostock/d3#2244]

**Comment by mgold** [comment]
I don't understand what the request is, and how it differs from the existing [brush.extent](https://github.com/mbostock/d3/wiki/SVG-Controls#brush_extent).

**Comment by jasondavies** [comment]
@jfarid27 Does `brush.extent()` not already address this?  Feel free to reopen if you meant something else.  Thanks.

**Comment by jfarid27** [comment]
Sorry for getting back so late @jasondavies. What I was getting at is that it's not exactly intuitive returning the start and end points for an extent. In my use cases, I typically want an array of the ranges of x and y. I end up always having to transform from the returned array of points to an array of ranges, and they testing whether my objects in the visualization are in the ranges. I figured we could add some code to at least give the option to return either points or ranges, and at least skip the step of transforming. It's sort of bloaty and probably shouldn't be an added feature, but I figured it was worth an addition. It is pull request worthy?

**Comment by mgold** [comment]
I think this is something best done in your client code, perhaps a pointInBox function.

**Comment by jasondavies** [comment]
I appreciate it may not be intuitive at first, but we use a similar representation for extents elsewhere in D3 (clipExtent for geometry/geography), and generally we’d like to avoid multiple ways of representing things as it would complicate the API.

FWIW, I don’t think the amount of code needed to check whether a point is within an extent is substantially different for the different representations.
