### ISSUE TITLE
packed circle charts should have variable padding width, and this should include parent circles

### ISSUE THREAD

**Issue by jamiewaese** [mbostock/d3#2247]
I am trying to display a phylogenetic tree with the packed circle chart. It displays the hierarchy of the data structure nicely, and it automatically sets the size of the leaf nodes according to the phylogenetic branch lengths as one would expect.

However, I am not able to adjust the sizes of the parent nodes. This is a shame because they have phylogenetic branch lengths too, just like the leaf nodes. We're masking data here! After a day of hacking, I have to come to realize that there is no clever work-around. 

The pack function allows you to adjust the radius of leaf nodes, but parent node sizes are not adjustable. Also, we can add padding to the leaf nodes but it does not apply to parent nodes.

Ideally we should be able to set the padding for all the circles individually. Parent circles should have an internal padding setting so their children don't automatically touch their sides. They should expand to contain their children *plus* leave a padding gap to display whatever size values are associated with their node.

Any help would be most appreciated!

**Comment by mbostock** [comment]
Moving to d3/d3-hierarchy#7. I also filed d3/d3-hierarchy#9, but the padding solution makes more sense to me than internal node values, since the pack layout won’t be very effective at showing that internal node value (due to “wasted space” between sibling nodes and their enclosing circle).
