### ISSUE TITLE
Display sunburst as a semicircle

### ISSUE THREAD

**Issue by crina27** [mbostock/d3#2248]
Is it possible to create a sunburst that is shaped as a semicircle? I was able to give it the shape that I want, but I have problems with the nodes. Not all the colors appear on the new shape and the text is displayed wrong.

            var partition = d3.layout.partition()
                 .sort(null)
                 .value(function(d) { return d.size; });

            var arc = d3.svg.arc()
                .startAngle(function(d) { return Math.max(0, Math.min(Math.PI/360, x(d.x))); }) 
                .endAngle(function(d) { return Math.max(0, Math.min(Math.PI, x(d.x + d.dx))); })
                .innerRadius(function(d) { return Math.max(0, d.y ? y(d.y) : d.y); })
                .outerRadius(function(d) { return Math.max(0, y(d.y + d.dy)); });

             var nodes = partition.nodes(json);

             var path = vis.selectAll("path").data(nodes);
             path.enter().append("path")
                  .attr("id", function(d, i) { return "path-" + i; })
                  .attr("d", arc)
                  .attr("fill-rule", "evenodd")
                  .attr("fill", function(d) { return color((d.children ? d : d.parent).name); })
                  .on("click", function(d,i) { 
                       //This is a mimic of the selection in the Tree List Box - picking all the parents of the selected cell
                   _this.Data.SearchColumn(0, "*" + d.name + "*",false);
             });

            var text = vis.selectAll("text").data(nodes);
            var textEnter = text.enter().append("text")
                  .style("opacity", 1)
                  .style("fill","#333")
                  .attr("text-anchor", function(d) {
                        return x(d.x + d.dx / 2) > Math.PI ? "end" : "start";
                     })
                  .attr("dy", ".2em")
                  .attr("transform", function(d) {
                        var multiline = (d.name || "").split(" ").length > 1,
                        angle = x(d.x + d.dx / 2) * 180 / Math.PI -90,
                        rotate = angle + (multiline ? -.5 : 0);
                        return "rotate(" + rotate + ")translate(" + (y(d.y) + p) + ")rotate(" + (angle > 90 ? -180 : 0) + ")";
                })
               .on("click", function(d,i) { 		
                       _this.Data.SearchColumn(0, "*" + d.name + "*",false);
                 });
 
         textEnter.append("tspan")
               .attr("x", 0)
               .text(function(d) { return d.depth ? d.name.split(" ")[0] : ""; });
        textEnter.append("tspan")
             .attr("x", 0)
             .attr("dy", "1em")
             .text(function(d) { return d.depth ? d.name.split(" ")[1] || "" : ""; });
        textEnter.append("tspan")
               .text(" ");
       textEnter.append("tspan")
               .text(function(d) { return d.depth ? d.name.split(" ")[2] || "" : ""; } );
       textEnter.append("tspan")
              .text(" ");
       textEnter.append("tspan")
             .text(function(d) { return d.depth ? d.name.split(" ")[3] || "" : ""; } );
I attached 2 photos with the original sunburst and with the one that I modified. 
![old](https://cloud.githubusercontent.com/assets/8511643/6444587/39451e5a-c107-11e4-811f-652723a771cd.png)
![new](https://cloud.githubusercontent.com/assets/8511643/6444592/3da3e65c-c107-11e4-8208-a6b2c5593cda.png)

**Comment by jasondavies** [comment]
These GitHub issues are for bug reports and feature requests only.  Please use [StackOverflow](http://stackoverflow.com/questions/tagged/d3.js) or the [d3-js group](https://groups.google.com/d/forum/d3-js) for help.
