### ISSUE TITLE
incorrect docs for d3.scale.quantize

### ISSUE THREAD

**Issue by jfirebaugh** [mbostock/d3#2255]
https://github.com/mbostock/d3/wiki/Quantitative-Scales#quantize-scales

The following parts seem inaccurate:

> The mapping is linear in that the output range value y can be expressed as a linear function of the input domain value x: y = mx + b.

This is the definition of d3.scale.linear.

> The output range is typically a dimension of the desired output visualization, such as the height of bars (measured in pixels) in a histogram.

"height in pixels" doesn't seem like a good example for a quantize scale range.

**Comment by mbostock** [comment]
So, like, y = round(mx + b), instead? Although round implies that it’s an integer output, which is potentially misleading. Would y = quantize(mx + b) be better?

**Comment by mbostock** [comment]
https://github.com/d3/d3-scale#quantize-scales

Fixed, maybe? If not, please open a pull request over there.
