### ISSUE TITLE
Simpler API in d3.geo.path().projection to turn off resampling

### ISSUE THREAD

**Issue by dgerber** [mbostock/d3#2263]
[This](http://bl.ocks.org/mbostock/5663666) seems a bit complicated to do a simple thing... What about accepting a second argument to turn off adaptive resampling?
```js
d3.geo.path().projection(function(c){ return [c[0], -c[1]] }, resampleOrNot)
```
AFAICS resampling is useless for any linear transformation, yet it produces much longer path strings because of rounding.

**Comment by jasondavies** [comment]
To turn off resampling, you can simply use `.precision(0)`.

**Comment by dgerber** [comment]
Thanks, I had missed that.

Actually, the rounding errors were not due to resampling only:
```js
var invertY = d3.geo.projection(function(λ, φ){
  return [λ, φ] //d3.geo.equirectangular()
}).scale(180/Math.PI).translate([0,0]).precision(0)
invertY([.42,0.42])
// [0.42000000000000004, -0.42000000000000004]
```
So a custom geometry stream is the only way to keep svg paths compact.
