### ISSUE TITLE
Get the bounds of the visible part of a map?

### ISSUE THREAD

**Issue by collioud** [mbostock/d3#2349]
Hi,

Is there is a way to get the bounds (in svg coords) of only the visible part of a map, especially after zooming/panning?

Thanks,
Arnaud

**Comment by jasondavies** [comment]
These GitHub issues are for *bug reports and feature requests only*. Please use [StackOverflow](http://stackoverflow.com/questions/tagged/d3.js) or the [d3-js Google group](https://groups.google.com/d/forum/d3-js) for general help.
