### ISSUE TITLE
How to contribute to Example Gallery page on Wiki?

### ISSUE THREAD

**Issue by benknight** [mbostock/d3#2350]
The Gallery page encourages people to add their own work to it, but I cannot figure out how that's supposed to be done.  Can't edit the page directly since the wiki isn't public, and Github doesn't support pull requests on wiki repos.  I also don't see any open or closed issues requesting things be added.  How is this supposed to work?

**Comment by jasondavies** [comment]
Unfortunately, we have had to disable Wiki editing due to an escalation in spam.  Hopefully we can come up with something better at some point.

**Comment by benknight** [comment]
Ah, that's okay.  My only suggestion would be removing the text at the top of the page that you can add your own.  This caused me to waste a good 10-15 minutes trying to figure out how, :-1:

**Comment by jasondavies** [comment]
Sorry about that.  I’ve removed the offending text.

**Comment by benknight** [comment]
Great thanks.  In the mean time I'd love to get my code up on the examples page somehow.  Do you think there will be anyway to do that any time soon? <3

**Comment by sdimi** [comment]
I'd love to get my code up on the examples page too.

**Comment by mbobra** [comment]
I'd like to showcase my visualization, too. In fact, I had it up there (I edited the wiki on December 14, 2014), but it was removed for some reason. Jason, if you can re-add the link, I'd appreciate it. It is a visualization of solar flares, published in Scientific American: http://www.scientificamerican.com/article/mapping-solar-flares-interactive/. Thanks : )

**Comment by mbostock** [comment]
The spammers seem to be on vacation, so I’ve re-opened the wiki.
