### ISSUE TITLE
Titanium cross-platform

### ISSUE THREAD

**Issue by vanderleisp** [mbostock/d3#2352]
Being new to embedded sw I'm facing some problems to test d3 on desktop browser, like having to deal with CORS, as most of the examples of d3 need to run using a server.
But the main goal of these tests is to see if could use d3 inside the Titanium cross-platform tool as a webview, and develop the hybrid app instead of native.
Problem is that even simple tests of d3 (like running the satellite example, doesn't start on webview, either with Android 4.1 or 4.3, so is there any minimum version that d3 needs as to run ?? or some trick to embedded it ?

**Comment by jasondavies** [comment]
These GitHub issues are for *bug reports and feature requests only*. Please use [StackOverflow](http://stackoverflow.com/questions/tagged/d3.js) or the [d3-js Google group](https://groups.google.com/d/forum/d3-js) for general help.
