### ISSUE TITLE
foreignObject on IE11

### ISSUE THREAD

**Issue by Anonyfox** [mbostock/d3#2353]
I'm building a collapsible tree, where the "nodes" are not circles, but custom HTML boxes (with input fields). Everything works fine so far, but in Internet explorer 11 the used `foreignObject`s are not rendered. The tree itself is fine and everything else seems to work, but foreignObjects don't show up. 

This is an example of how I use it currently: 

````
nodeEnter.append("foreignObject")
        .attr("x", -65)
        .attr("y", -10)
        .attr("width", 130)
        .attr("height", 50)
      .append("xhtml:div")
        .attr("class", "node-div")
        .html(function (d) {
          var parentId;
          if (d.parent) {
            parentId = d.parent.id;
          } else {
            parentId = null;
          }
          return "<input type='text' value='" + d.value + "' id='input-" + d.id + "' data-parent-id='" + parentId + "'>";
        })
````

and everything works fine, except in IE 11. Is there  a polyfill needed or something like that?

(I use a variation of https://github.com/tutorialhorizon/react-webpack-setup/tree/react-d3-tree)

**Comment by jasondavies** [comment]
[foreignObject is not supported by IE11](https://msdn.microsoft.com/en-us/library/hh834675(v=vs.85).aspx).
