### ISSUE TITLE
Updating a grouped bar chart (transition or removal of groups)

### ISSUE THREAD

**Issue by bgbrink** [mbostock/d3#2355]
I am trying to implement an extended version of the Grouped Bar Chart (http://bl.ocks.org/mbostock/3887051). Everything works fine, except updating the plot.

Normally I would just use selections, and use enter() to append new nodes, transition() to update existing nodes and exit() to remove the rest. Here is a working example of my plot (without groups), which shows the desired when you click on "sort by name" or "sort by value": http://jsfiddle.net/w2q0kjgd/1/

I used exactly the same concept and applied it to the groups, however it only appends new gruops everytime the draw function is called: http://jsfiddle.net/o3fpaz2d/6/

Am I doing something wrong or is this a bug?

**Comment by jasondavies** [comment]
These GitHub issues are for *bug reports and feature requests only*. Please use [StackOverflow](http://stackoverflow.com/questions/tagged/d3.js) or the [d3-js Google group](https://groups.google.com/d/forum/d3-js) for general help.
