### ISSUE TITLE
Factor out inessential parts

### ISSUE THREAD

**Issue by fresheneesz** [mbostock/d3#2361]
Why does d3 provide so many inessential APIs?

On [the homepage for d3](http://d3js.org/), it states:

> D3 is not a monolithic framework that seeks to provide every conceivable feature. Instead, D3 solves the crux of the problem: efficient manipulation of documents based on data. 

However, I see that d3 implements 
* its own jquery/sizzle-like selector API rather than just expecting dom-nodes given to it by another library
* Its own map and set objects
* A "nest" object
* Array manipulation methods
* A set of methods for generating random data
* a set of ajax utilities
* string formating
* csv formatting
* localization
* color utilities

And *many* more components that I don't understand well enough to evaluate whether or not they're relevant to data manipulation.

NONE of the above things seem necessary to data manipulation for a library that purports to rely on modern web standards. Shouldn't each of these things be split out into their own separate libraries, and then referred to as a recommended selection/array-manipulation/ajax/string-formatting/etc library?

I'm very wary of a library that says upfront that it isn't a monolithic framework, and then proceeds to go ahead and be one.

**Comment by fresheneesz** [comment]
Not only does this make for a larger more complicated framework, where most users are only using a small fraction of the system, but it bloats the size of the package, which looks to be around 150KB. That's a huge fraction of my application.

**Comment by mbostock** [comment]
56KB, assuming you gzip.

Although a default build is provided, the source code is designed for modularity. You can use SMASH to produce a custom build if you wish to optimize and only use some parts of D3; see the [SMASH wiki](https://github.com/mbostock/smash/wiki) for details, and the D3 Makefile itself.

The “inessential” APIs you mention are provided for convenience in the default build because they are often needed for data visualization. This situation will improve when ES6 modules are widely-supported, but until then we are stuck with various non-standard bundling systems.

**Comment by fresheneesz** [comment]
@mbostock So yes we don't have ES6 modules yet, but the bundling systems out there do conform to one of three standards: CommonJS, AMD, and even ES6 modules. My preferred system is [Webpack](http://webpack.github.io/) which, like browserify, uses CommonJS. 

Since you're using your own bundling tool (smash), why not split each component into its own module and use them as dependencies for this framework? Not only would users be much more easily able to pick and choose what modules they need, lowering the size of the code and removing a lot of cognitive load (making it easier for them to learn d3), but more people could benefit from the components you've written in other contexts than data-driven document manipulation.

I should also mention, Webpack already supports ES6 modules [via a loader](http://www.uxebu.com/blog/2014/11/get-real-es6-webpack/) and out-of-the-box support for ES6 [is imminent](https://github.com/webpack/webpack/pull/857). I'd really recommend checking webpack out.
