### ISSUE TITLE
d3.svg.axis animated transition seems broken in latest v3.5.5

### ISSUE THREAD

**Issue by lightblade** [mbostock/d3#2363]
http://codepen.io/anon/pen/dPrNvV

I remember axis used to have an animated transition on rerendering to different scale. Inspecting the source seems to show that was the intention.

https://github.com/mbostock/d3/blob/master/src/svg/axis.js#L33

**Comment by mbostock** [comment]
Forgetting to call selection.transition, maybe?

http://codepen.io/anon/pen/Bybpdv
