### ISSUE TITLE
import.html file

### ISSUE THREAD

**Issue by RenatoUtsch** [mbostock/d3#2374]
For the people that are using d3 with web components, an import.html file would be an essencial addition.

It is simply an import.html with the following content:
```html
<script src="d3.min.js" charset="utf-8"></script>
```

When working with web components, every component that uses d3 will import it through:
```html
<link rel="import" href="../d3/import.html">
````
This will prevent importing d3 more than once.

I can make a pull request if you want, but it is a very simple task.

**Comment by mbostock** [comment]
Merging into #2391.
