### ISSUE TITLE
how to fork wiki

### ISSUE THREAD

**Issue by int64ago** [mbostock/d3#2378]
Hi, I want to contribute to wiki, but only d3 is forked when I fork in wiki page

So how can I only fork the wiki project?

Thx :)

**Comment by sefakilic** [comment]
Here is a link on how to contribute to a GitHub wiki.

https://gist.github.com/larrybotha/10650410

**Comment by int64ago** [comment]
@sefakilic 
Thx :)

**Comment by jasondavies** [comment]
Also, note that direct Wiki editing is currently disabled for D3 due to spam: #2350.

**Comment by mgold** [comment]
Hopefully the wiki can be reopened soon.
