### ISSUE TITLE
Windows 8 touch event support

### ISSUE THREAD

**Issue by scottdurow** [mbostock/d3#2380]
Is there any plans to incorporate Windows 8 touch into d3 any time soon?
This would be along the lines of https://github.com/natevw/d3/tree/fix-drag-touchend-win8

Thanks!

**Comment by scottdurow** [comment]
Using CSS  touch-action: none; allows panning using touch - but not pinch-zooming in Windows 8.1 IE

Any ideas?

**Comment by natevw** [comment]
Hi Scott, actually just needed to update that very patch for a project this week: https://github.com/mbostock/d3/pull/2403

That's a relatively simple change — the zoom is a bit trickier (and I don't need it for my client's project) but someone else contributed a patch for that too, recently: https://github.com/mbostock/d3/pull/2405

Regarding `touch-action`, I'm not quite sure what you're asking but Pointer Events seem a little trickier here than Touch Events. I need a bit more experience to say definitively, but where TE let you control the browser via `preventDefault()` or lack thereof in your handlers, with PE you seem to have to choose beforehand. So you can set `touch-action: pinch-zoom` and the browser will ± send you all single pointer events but not double-finger stuff. Or you could try `touch-action: manipulation` but that seems to prevent any events from getting to JS. In practice I haven't hit a situation yet where I really need TE-style control, but YMMV.

**Comment by mbostock** [comment]
There are several separate issues here. D3 should not magically translating pointer events into touch events, but instead add support for pointer events to the various behaviors and components that need it:

* Zoom behavior #1439
* Drag behavior #2556
* Brush component #2446

**Comment by natevw** [comment]
@mbostock Thoughts on the notion of making the zoom and brush components themselves dependent on the drag, as described at https://github.com/mbostock/d3/pull/2403#issue-70245982? Then all the mouse vs. touch vs. pointer logic only needs to be written once, for the notion of "some sort of pointer pushed down, dragged, then released", instead of duplicated between the three.
