### ISSUE TITLE
d3.behavior.zoom().center() doesn't work when calling event()

### ISSUE THREAD

**Issue by raziellight** [mbostock/d3#2386]
zoom = d3.behavior.zoom()
        .center([width / 2, height / 2]);

doesn't work as expected when making a button.

	var zoomfactor = 1;

	d3.select(".zoomin").on("click", function (){
	    zoomfactor = zoomfactor + 0.2;
	    zoom
	    .on("zoom", zoomed).scale(zoomfactor).event(d3.select(".graphmap"));
	});

	d3.select(".zoomout").on("click", function (){
	    zoomfactor = zoomfactor - 0.2;
	    zoom
	    .on("zoom", zoomed).scale(zoomfactor).event(d3.select(".graphmap"));
	});

zoom.scaleExtent doesn't work either.

**Comment by mbostock** [comment]
Setting zoom.center only affects the behavior of mousewheel, as shown in [this example](http://bl.ocks.org/mbostock/6226534) and described in [the documentation](https://github.com/mbostock/d3/wiki/Zoom-Behavior#center). So I’m not sure what you expect here.

I’ve implemented a couple new examples that will hopefully help:

http://bl.ocks.org/mbostock/7ec977c95910dd026812 (buttons for zoom-in and zoom-out)
http://bl.ocks.org/mbostock/4dc8736fb1ce9799c6d6 (button for instantaneous reset)

And the original:

http://bl.ocks.org/mbostock/3892928 (button for reset transition)

**Comment by raziellight** [comment]
This fixes it. Thank you for all your work.
