### ISSUE TITLE
Error should be thrown if undefined is passed into 'select'

### ISSUE THREAD

**Issue by fresheneesz** [mbostock/d3#2392]
If you pass `undefined` into `d3.select`, it silently fails. Instead, it should throw an error to make the programmer aware of their mistake.

**Comment by mbostock** [comment]
D3 coerces inputs to expected types (so `undefined` is equivalent to `"undefined"`) but does not expressly validate input. While strict input validation provides an additional level of safety for the user, I did not feel it was worth the trade-off in terms of implementation complexity. If you want an additional level of safety in your code, I recommend writing tests for it.

**Comment by fresheneesz** [comment]
Coercing `undefined` into anything else doesn't make sense.. its unexpected, and looks like just a silent failure. Silent failures are always bad. It wouldn't be hard to implement this either: `if(arg===undefined) throw`.

**Comment by mgold** [comment]
> Silent failures are always bad.
In theory I agree, but JavaScript one does not have the luxury. The language, conventions, and emphasis on shaving bytes conspire against it. D3 fails silently in many other ways.

**Comment by fresheneesz** [comment]
While it may be true that the design of javascript's internals means silent failures can happen a lot, minimizing them should be a goal. Embracing silent failures simply leads to an unsustainable development and debugging process.

**Comment by mgold** [comment]
I am not getting into a flame war. This will be my last post on the thread.

If you want web-dev with type safety, I encourage you to check out [Elm](http://elm-lang.org/) (a new version is coming out soon).

**Comment by fresheneesz** [comment]
If this is looking like a flame war to you, you've never seen a flame war man. They get mean.

Elm looks pretty cool! I'll have to check it out
