### ISSUE TITLE
Firefox date parsing bug

### ISSUE THREAD

**Issue by nickschurch** [mbostock/d3#2398]
I have a visualization with date for the x-axis. I have the very simple d3 date parser:

```javascript
var format = d3.time.format("%Y");
```

When fed years, this creates a perfectly acceptable date axis with year labels in Chrome, IE and Safari, but in firefox, it results in '01 AM' as the label for every entry. Here is the example (try it):

http://www.compbio.dundee.ac.uk/user/nschurch/MeaslesViz/

I understand from googling around that this may be related to being on BST but I can't see any designation that is going to get round it. I tried specifying a utc formatter, but to no avail. So, am I doing something wrong here or is this a bug?

Using d3.v3.min.js, chrome 42.0.2311.90 (64-bit), firefox 37.0.1, on Ubuntu 14.04 64 bit.

**Comment by mbostock** [comment]
The issue is that the tick values in Firefox are not at midnight local time, due to #1197.

You are using the format instance to parse, but not to format the axis ticks; you could work around this issue by using the format in axis.tickFormat as well. For example:

```
xAxis.tickFormat(format)
```

**Comment by nickschurch** [comment]
Thanks make, that works perfectly.
