### ISSUE TITLE
could not find Circular shift in d3.scale

### ISSUE THREAD

**Issue by SaadAhmedSiddiqui** [mbostock/d3#2400]
is it possible to define domain
like 
[5,10] [0,5] or could be express as [0, 10] domainShift -5
with range [0, 200]
i.e. 
if the value is 5 the result would be 0
if the value is 10 the result would be 100
if the value is 4.9 the result would be 198

**Comment by mbostock** [comment]
Sure. You can create a discontinuity by repeating a value in the domain. Your example would be:

```
var scale = d3.scale.linear()
    .domain([0, 5, 5, 10])
    .range([100, 200, 0, 100])

scale(5); // 0
scale(10); // 100
scale(4.9); // 198.00000000000003
```

**Comment by SaadAhmedSiddiqui** [comment]
Thanks, it worked
this is my example, I was shifting timeScale with respect to timezone +5 GMT
I am using timeScale = makeScale([ 0, maxTime ], [plot.leftPad, plot.paddedWidth-1], Date.TIME_ZONE, 24); 

function makeScale(domain, range, shift, cycle){
            var process = shift ? function(n){
                return (cycle + n - shift) % cycle;
            }: function(n){ return n;} ;

            return function(value){
                return range[0] + ( process(value) - domain[0] ) / ( domain[1] - domain[0] ) * ( range[1] - range[0] );
            };
        }
