### ISSUE TITLE
Make locales built in the library

### ISSUE THREAD

**Issue by wytrych** [mbostock/d3#2409]
Would it make sense to hard compile the locales in the library, so they would be easily available by default?

**Comment by clcpolevaulter** [comment]
@mbostock is this something you would consider? I am trying to pull this into a rather large app that supports 36 languages. I will have to create a separate module that gives me a static locale when needed if not.

**Comment by mbostock** [comment]
The locales are not provided by default to keep the file size small. You’ll need a custom build or to load the locale definitions separately.

I am working on a new Rollup-based build system and modules structure for D3 4.0, and the new [d3-format](https://github.com/d3/d3-format) and [d3-time-format](https://github.com/d3/d3-time-format) are already available. You’ll still need to edit the index.js file (see [d3-format/index.js](https://github.com/d3/d3-format/blob/master/index.js) and [d3-time-format/index.js](https://github.com/d3/d3-time-format/blob/master/index.js)) to change the default locale or add multiple locales. Or you could roll your own build that exposes all the available locales as a standalone file.

Eventually, there will be a web interface for creating custom builds without needing to use the command line. The web interface should allow you to specify multiple locales, too, though I haven’t figured out exactly how that will work yet.

**Comment by clcpolevaulter** [comment]
Sweet deal. Thanks for the insight, @mbostock.

**Comment by mbostock** [comment]
I’m not planning on changing the current behavior for 3.x, and the 4.0 modules currently include all locales by default, so closing this issue. Most likely the web interface for custom builds in 4.0 will allow you to pick and choose which locales to include.
