### ISSUE TITLE
Discussion Forum

### ISSUE THREAD

**Issue by CrowdHailer** [mbostock/d3#2410]
Hi Is there a place to ask questions which are probably not really worthy of opening issues for?

If so can I suggest a link in the README page. 

If not can I suggest a Gitter channel for those who are interested. I have found it useful on other projects

**Comment by CrowdHailer** [comment]
OK the mailing list wasnt that hard to find. My apologies. However I don't know is there anything else?

https://groups.google.com/forum/#!forum/d3-js

**Comment by jasondavies** [comment]
We normally point people to [StackOverflow](http://stackoverflow.com/questions/tagged/d3.js) too.  In fact, when opening a new issue, a link to [guidelines for contributing](https://github.com/mbostock/d3/blob/master/CONTRIBUTING.md) (containing these links) appears above the entry form, but people sometimes miss it.

**Comment by CrowdHailer** [comment]
OK's so the information is all clearly around. I do forget to check for a CONTRIBUTING doc.
