### ISSUE TITLE
Treemap doesn't handle the level with all zero value correctly.

### ISSUE THREAD

**Issue by chaoteng** [mbostock/d3#2419]
When we try to build a Treemap with the data which all children have 0 value, it will display the treemap with children overlapped. Is it more reasonable to show an empty treemap or a treemap with same-sized children.

The demo is here: http://jsfiddle.net/znfxLcn3/

Thank you for help.

**Comment by mbostock** [comment]
Related #2420 (for d3.svg.pie).

**Comment by mbostock** [comment]
Fix staged in #2591 for 3.5.7.
