### ISSUE TITLE
Append plain text node

### ISSUE THREAD

**Issue by natevw** [mbostock/d3#2422]
I certainly haven't thought through all the implications of this, but I keep encountering situations where it'd be nice to append a text node rather than an element.

Consider labeling a form element. If the label text is on the left, you can get away with something like this:

```
sel.append('label').call(function (sel) {
  sel.text("Message: ");
  sel.append('input').attr('placeholder', "Type your message here.");
});
```

But if the label text needs to be on the right, you need to use a superfluous wrapper element:

```
sel.append('label').call(function (sel) {
  sel.append('input').attr('type', "checkbox");
  sel.append('span').text(" I submit to the power of this mighty EULA, may it live forever.")
});
```

For occasions like this, it'd be helpful if D3 let me do something like:

```
sel.append('li').call(function (sel) {
  sel.append('span').classed('quantity', true).text(function (d) { return d.count; });
  sel.append('#text', " ");
  sel.append('#text', function (d) { return (d.count !== 1) ? "widgets" : "widget"; });
});
```

Of course the catch is, could you re-select such text for later updates? The "widget" example directly above only works for entering selections, if `d.count` were to change, we'd probably need the second #text append to affect a selectable span — though the first use for the space would still be convenient. So unfortunately this might need to be a bit of a special case (**idea**: `sel.addText(str)`, returning the original `sel`, instead?) but arguably very handy when a situation only needs to set up such labelling/filler text once.

**Comment by mbostock** [comment]
I’ve thought about this, too, and the answer I always come to is “no” because you can’t select (as in, document.querySelector) text nodes. You can only select elements. By extension, D3 only works with elements, so if you want to add text, you should use a SPAN element rather than a raw text node.

That, or selection.html:

```js
selection.append("li").html(function(d) {
  return "<span class=\"quantity\">" + d.count + "</span> " + (d.count === 1 ? "widget" : "widgets");
});
```
