### ISSUE TITLE
scroll mouse zoom

### ISSUE THREAD

**Issue by alfredopacino** [mbostock/d3#2425]
Hi, I'm very new to d3, so long i've just studied a little this example I need
http://mbostock.github.io/d3/talk/20111116/pack-hierarchy.html
I'm wondering how to accomplish 2 feature:
- zoom action on mouse scoll, not on node click.
- keyboard event for multiple node selection (in the example, pressing ctrl key and clicking on nodes "scale" and "display" I want to show some infos related to both nodes in a div)

**Comment by gka** [comment]
this question should be asked on stackoverflow, tagged with [d3.js](http://stackoverflow.com/questions/tagged/d3.js). the issues on github are for bug reports and feature requests.
