### ISSUE TITLE
Inconsistent zoom behavior between browsers?

### ISSUE THREAD

**Issue by ghyonimor** [mbostock/d3#2426]
Hello, 
First of all - thanks for this awesome library!

In a project we're working on recently, we've encountered a problem with how different browsers handle zoom scale, as the mousewheel delta is not normalized in d3.
As a solution we plan on overriding d3_behavior_zoomWheel.

I'd appreciate your output on this matter.

Thanks in advance.

**Comment by mbostock** [comment]
Possibly related #2589.

**Comment by mbostock** [comment]
Duplicate of #2589.
