### ISSUE TITLE
d3.format percentage error

### ISSUE THREAD

**Issue by vmeng** [mbostock/d3#2428]
Use d3.format(",.1%")(0.0435), it should give 4.4%, but 4.3%

**Comment by mbostock** [comment]
The behavior is correct, and is a limitation of floating point precision (IEEE 754).

The number 0.0435 is more precisely represented as 4.349999999999999700239783351207734085619449615478515625e-2 in decimal. This number is less than 0.0435, and so rounds down to 0.043 when using Number.toFixed and similar methods.
