### ISSUE TITLE
axis.ticks() returns Arguments object after axis.ticks(count)

### ISSUE THREAD

**Issue by wrummler** [mbostock/d3#2430]
d3.svg.axis().ticks().constructor // function Array() { [native code] }
    d3.svg.axis().ticks().toString() // "10"

    d3.svg.axis().ticks(10).ticks().constructor // function Object() { [native code] }
    d3.svg.axis().ticks(10).ticks().toString() // "[object Arguments]"

This bit me when I was feeding an explicit tick spec of an axis to the underlying scale of the axis to get tick values from the scale to manipulate and then feed back to the axis. `scale.ticks` did not like the `Arguments` object, giving me `[]`.

The problem is this line in `axis.ticks`:

    tickArguments_ = arguments;

That line should probably look or at least behave like this:

    tickArguments_ = Array.prototype.slice.call(arguments);

In any case, an invocation's `arguments` object shouldn't be exposed to its callers.

**Comment by mbostock** [comment]
Sounds reasonable.

**Comment by mbostock** [comment]
Fix merged in #2591.
