### ISSUE TITLE
getNodeById

### ISSUE THREAD

**Issue by alfredopacino** [mbostock/d3#2431]
Hi, I'm new to d3. I'm creating nodes with id
```
  vis.selectAll("circle")
      [...]
      .attr("id", function(d) { return 'N'+i++; })
      [...]
```
Now, I have an array containing some nodeIDs (N001, N002, N003)
Where is the problem here?
```
for (var nodeid in stack){
		console.log(d3.select("[id='" + nodeid + "']").attr("name"))
	}
```
that select is not actually referring to my nodes

**Comment by israelst** [comment]
To select by id use `#`:
```javascript
console.log(d3.select("#N001").node())
```

**Comment by alfredopacino** [comment]
i get the error
Uncaught SyntaxError: Failed to execute 'querySelector' on 'Document': '575' is not a valid selector.

**Comment by alfredopacino** [comment]
I was making a logical error, I need the original json source not the d3 reference, sorry.
