### ISSUE TITLE
Transitions progress event

### ISSUE THREAD

**Issue by JabbyPanda** [mbostock/d3#2433]
I think it would be nice to extend _transitions_ API with new `progress` event

Inside this event handler one can have an insight at the current value that is currently changing using `transition` interpolator or add the condition to exit the transition prematurely.

The syntax for the proposed API could be as following 
```
 .each("progress", function(d) {
                var currentColor = cell.style('background-color');
                 console.log('cell currently has ' + currentColor + ` background`)       
                    }
                })
```

**Comment by mbostock** [comment]
You can do this already by defining a [custom tween](https://github.com/mbostock/d3/wiki/Transitions#tween). For example:

```js
d3.select("body").transition().style("background", "red").tween("progress", function(d, i) {
  return function(t) {
    console.log("cell background", this.style.backgroundColor);
  };
});
```

**Comment by JabbyPanda** [comment]
:+1:
