### ISSUE TITLE
[Wiki] [Examples] Access denied to Rotating Arcs

### ISSUE THREAD

**Issue by Gigabyte-Giant** [mbostock/d3#2438]
The example "Rotating Arcs", comes up with 403 (Access Denied) error.

Should the example be moved [to a new site] or removed?

Link: http://vyacheslavryabinin.com/datavis/absind

**Comment by mbostock** [comment]
The examples gallery is publicly maintained, so if you notice a broken link, feel free to delete it. I’ll do this one. Thank you!

**Comment by Gigabyte-Giant** [comment]
Awesome, thanks!
