### ISSUE TITLE
Disconnect drag behavior

### ISSUE THREAD

**Issue by cool-Blue** [mbostock/d3#2439]
Is there any support for this?
Patch d3.behavior.drag by replacing this code...
```js
function drag() { 
    this.on("mousedown.drag", mousedown).on("touchstart.drag", touchstart);
}
```
with this...
```js
function drag(selection, remove) {
    [{e:"mousedown.drag", l: mousedown},{e: "touchstart.drag", l: touchstart}]
        .reduce(function (s, b) {return s = s.on(b.e, remove ? null : b.l)}, this)
}
```
Then we could do this...
```js
_opts.element.call(_drag, "remove")
```
to disconnect the behavior.

**Comment by mbostock** [comment]
You can disconnect the drag behavior by saying:

```js
selection.on(".drag", null);
```

**Comment by cool-Blue** [comment]
Yep, I'm aware of that, but it's not intuitive and it's not documented in the API, hence my suggestion.

**Comment by mbostock** [comment]
There wasn’t any documentation on how to apply the drag behavior either. :wink: Fixed both of those issues.

**Comment by cool-Blue** [comment]
My little patch delivers a new feature with perfect symmetry by adding just one line of code... Anybody? ...No? ...Damn, this is a tough room... Hehe.😌
