### ISSUE TITLE
Wiki addition on the drag behaviors might contain an extra dot

### ISSUE THREAD

**Issue by monfera** [mbostock/d3#2448]
Hello Mike,

the recently added 

```selection.on(".drag", null);```

on https://github.com/mbostock/d3/wiki/Drag-Behavior contains a dot, just mentioning it in case it wasn't intended.

By the way, apparently it would have been possible for me to edit the Wiki text, though I didn't try to save anything.

**Comment by mbostock** [comment]
The dot is intended: ".drag" means any listener with the "drag" namespace. See the [selection.on](https://github.com/mbostock/d3/wiki/Selections#on) documentation.
