### ISSUE TITLE
Force layout: node "jumps back" on fast drag

### ISSUE THREAD

**Issue by vanquang9387** [mbostock/d3#2449]
Hi,
Please see this CodePen: http://codepen.io/vanquang9387/pen/gpLpGE?editors=001
When I do a fast drag (drag and quick release mouse), the node just moves in opposite direction.

**Comment by cool-Blue** [comment]
You can find an explanation of why this happens and how to manage it [here](http://stackoverflow.com/a/30433664/2670182).

**Comment by vanquang9387** [comment]
Thanks @cool-Blue
