### ISSUE TITLE
Change the force.linkDistance function so that it will work if argument x is a string

### ISSUE THREAD

**Issue by JVAdams** [mbostock/d3#2451]
This issue is described more fully at http://stackoverflow.com/a/30448047/2140956.

In short, in order to allow for varying lengths of links in the `forceNetwork` function of the R package **networkD3**, the `linkDistance` argument is set to something like `"function(d) { return d.value; }"`.  But this does not work with the `force.linkDistance` function of **d3js**, because it is a *string*.  @bgoldst suggests that this can be fixed by changing line 6307 of https://github.com/mbostock/d3/blob/master/d3.js from 
`linkDistance = typeof x === "function" ? x : +x;` 
to 
`linkDistance = typeof x === "string" ? eval('('+x+')') : +x;`.

**Comment by mbostock** [comment]
Sorry, but this is not the right place to fix the problem. If you have a string that represents a function, and you want to eval that string to turn it into code, you should do it outside of the D3 API.

**Comment by JVAdams** [comment]
Okay, thanks.  I posted an issue at **networkD3**.  https://github.com/christophergandrud/networkD3/issues/37
