### ISSUE TITLE
Cannot create quantile scale using Float32Array

### ISSUE THREAD

**Issue by oshikryu** [mbostock/d3#2455]
I am trying to create a quantile scale for a Float32Array of values.

Running the following code:
```
var  float32Array = new Float32Array(5);

d3.scale.quantile()
  .domain(float32Array)
  .range(['q1', 'q2', 'q3', 'q4']);

```
Throws the following error: `TypeError: x.map is not a function`

I suspect this is because Float32Arrays in javascript do not have a `map()` function like the default  `Array` class does.

For now I am recasting my Float32Array as an untyped array but I am wondering if the creating scales can be made so that it is not dependent on the array's type.

**Comment by mbostock** [comment]
I suppose you could reimplement [scale.domain](https://github.com/mbostock/d3/blob/master/src/scale/quantile.js#L26-L30) to allow a typed array as input, but it’d still be mapped to an untyped array internally—unless you did a fair amount of work to map, filter and sort the values.

**Comment by oshikryu** [comment]
Ah okay. I don't think it warrants enough of a full reimplementation of scale.domain - just a curiosity. 

Thanks
