### ISSUE TITLE
The “elastic” and “bounce” easing functions are reversed.

### ISSUE THREAD

**Issue by mbostock** [mbostock/d3#2456]
The following easing functions should be swapped:

* elastic-out ↔︎ elastic-in
* elastic-out-in ↔︎ elastic-in-out
* bounce-out ↔︎ bounce-in
* bounce-out-in ↔︎ bounce-in-out

See [easings.net](http://easings.net) for reference. And these:

http://bl.ocks.org/mbostock/3fad0a71418216b74444
http://bl.ocks.org/mbostock/5cf917540c86082abf36

**Comment by srogljan** [comment]
Hello,
sounds like a good issue for me. Let me try to fix it!

John

**Comment by mbostock** [comment]
It’s already fixed in [d3-ease](https://github.com/d3/d3-ease), @srogljan.

**Comment by srogljan** [comment]
Oops, sorry then - it looked so attractive :-) btw. why is this issue not closed as well?

**Comment by mbostock** [comment]
It will be closed when D3 4.0 is released.

**Comment by mbostock** [comment]
I’ve decided to close issues that are fixed in the new D3 modules, even though D3 4.0 has not yet been released, so that the open issues in this repository are more representative of open issues that still need to be fixed.
