### ISSUE TITLE
“gradient that follows a stroke” does not work in Firefox 

### ISSUE THREAD

**Issue by Flocksserver** [mbostock/d3#2459]
We use in our project d3.js and the "gradient that follows a stroke" like in this example: http://bl.ocks.org/mbostock/4163057 but it doesn't work as expected in Firefox. Then we discovered - it is only a problem in firefox... For visualize the problem and for easier understanding I changed the draw points in the example and these are the results:

Overview Screenshots: http://i.stack.imgur.com/dF25w.png

Points:

    var points = [
        [86, 388],
        [805, 447],
        [788, 40],
        [93, 72]
    ];

**Comment by mbostock** [comment]
Did you determine whether it was a bug in Firefox or a bug in the example?

**Comment by Flocksserver** [comment]
No and I'm not sure about it... I also asked this question on stackoverflow. The first reply was:
"his sounds more like an issue for the d3.js bug tracker IMHO" so I thought... maybe I 'm lucky and share this problem here looking for help. maybe it could be a bug. What do you think about it?

**Comment by mbostock** [comment]
It sounds like a bug in Firefox to me but I don’t have time at the moment to investigate.

**Comment by arusakov** [comment]
@Flocksserver 
I use Mac and Firefox 39. I don't see bug. Which version do you use?

**Comment by Flocksserver** [comment]
@arusakov Firefox 39 on Mac/Linux/Windows. No matter what OS. Have you changed the points as I mentioned in my first post?

**Comment by mbostock** [comment]
Seems fixed in Firefox 40.
