### ISSUE TITLE
d3.geo LineString is drawing an additional line in some projections

### ISSUE THREAD

**Issue by darktechsupport** [mbostock/d3#2462]
I'm trying to use the geo projections with canvas rather than svg, and I'm finding that adding an arc with LineString is only working properly with the orthographic projection.

The other projections either draw the arc with another straight line shooting off at the end, or they don't display the arc at all.

Here's an example: http://bl.ocks.org/darktechsupport/1335bc94532470f3a473

Is this something I'm doing wrong, or is this a bug?

**Comment by mbostock** [comment]
It looks like you have your longitude and latitude reversed. Longitude should range from -180° to +180°, and latitude from -90° to +90°, but one of your points is [47.61, 122.33]. In D3, GeoJSON and TopoJSON, coordinates are in the form [longitude, latitude] (as in [x, y]), not [latitude, longitude] ([y, x]).
