### ISSUE TITLE
attempting to use d3 with uglify/strict mode causes problems

### ISSUE THREAD

**Issue by seiyria** [mbostock/d3#2466]
I've been trying to find a version of d3 that I could use with grunt-contrib-uglify without going too far back. I got to 3.3.0 before I realized that I d3 just doesn't work in strict mode. Is it possible to have d3 compatible with strict mode so it works better with build processes like this?

**Comment by mbostock** [comment]
The code in this repository is currently being broken up into a variety of smaller modules for D3 4.0; see #2461. As part of this restructuring the code is all being written as ES6 modules, and I believe that means it should work in strict mode by definition.

**Comment by seiyria** [comment]
Sure, that's reasonable. I can't say for sure if that statement is true but I haven't explored it very much, so in that case I think it's best to wait and see. I'm not sure if this issue needs to remain open in that case, so I'll leave that up to your discretion. Thanks for getting back to me so quick!
