### ISSUE TITLE
Browser dependent behaviour

### ISSUE THREAD

**Issue by pulkitnandan** [mbostock/d3#2469]
When I view this fiddle code locally in chrome browser I'm able to see any axis i.e. css property .axis path{} is been completely ignored by the chrome browser while respected inside the fiddle and in mozilla firefox browser. Is this d3js bug or chrome.

**Comment by pulkitnandan** [comment]
You can find the fiddle at http://jsfiddle.net/Q5Jag/1116/

**Comment by mbostock** [comment]
Seems fine to me on both Chrome and Firefox?

Note that if you have the HTTPS Everywhere plugin installed it can interfere with library loading on JSFiddle. See jsfiddle/jsfiddle-issues#591.
