### ISSUE TITLE
input of type=file does return an event object using d3

### ISSUE THREAD

**Issue by fran-pena** [mbostock/d3#2470]
When a input of type=file is set with standard code, the file linked to an event return an Event object:
document.getElementById('upload').addEventListener('change', l2w_input_onchange, false); 
That object is useful, for example, to a FileReader object and then read the file.

With d3, the linked function does not return such Event Object.

**Comment by mbostock** [comment]
I’m not sure I understand what you’re asking, but I’ll try to answer. This code:

```js
document.getElementById('upload').addEventListener('change', l2w_input_onchange, false); 

function l2w_input_onchange(event) {
  console.log(event);
}
```

Is equivalent to this:

```js
d3.select("#upload").on("change", l2w_input_onchange, false);

function l2w_input_onchange() {
  console.log(d3.event);
}
```

In D3, listeners registered via selection.on receive data (*d*) and index (*i*), like other function callbacks. So if you want to access the current event within a listener, use d3.event.

**Comment by fran-pena** [comment]
Ok, I think you are right. Sorry for reporting a false bug!
