### ISSUE TITLE
Bower + D3

### ISSUE THREAD

**Issue by tapan-d-thakkar** [mbostock/d3#2474]
Hi,

After adding D3 to bower.json, if i run bower install i am getting below error. as I have added angular as well, i can see angular in my bower_components folder. but it fails for d3.

Bower.Json

"dependencies": {
      "angular": "1.2.19",
      "d3": "latest"
  },

Error: 

D:\Project>bower install
bower d3#*                  not-cached https://github.com/mbostock/d3.git#*
bower d3#*                     resolve https://github.com/mbostock/d3.git#*
bower d3#*                    download https://github.com/mbostock/d3/archive/v3.5.5.tar.gz
bower d3#*                    progress received 1.6MB of 2.9MB downloaded, 54%
bower d3#*                    progress received 1.8MB of 2.9MB downloaded, 62%
bower d3#*                    progress received 2.0MB of 2.9MB downloaded, 68%
bower d3#*                    progress received 2.2MB of 2.9MB downloaded, 76%
bower d3#*                    progress received 2.4MB of 2.9MB downloaded, 84%
bower d3#*                    progress received 2.6MB of 2.9MB downloaded, 91%
bower d3#*                    progress received 2.8MB of 2.9MB downloaded, 99%
bower d3#*                     extract archive.tar.gz
bower d3#*                invalid-meta d3 is missing "main" entry in bower.json
bower d3#*                invalid-meta d3 is missing "ignore" entry in bower.json
bower d3#*                       EPERM EPERM, rename 'C:\Users\admin\AppData\Local\Temp\AP-admin\bower\d3-14296-GzWfWk'

Stack trace:
Error: EPERM, rename 'C:\Users\admin\AppData\Local\Temp\AP-admin\bower\d3-14296-GzWfWk'

Console trace:
Error
    at StandardRenderer.error (C:\Users\admin\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:82:37)
    at Logger.<anonymous> (C:\Users\admin\AppData\Roaming\npm\node_modules\bower\bin\bower:110:22)
    at Logger.EventEmitter.emit (events.js:95:17)
    at Logger.emit (C:\Users\admin\AppData\Roaming\npm\node_modules\bower\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:45:20
    at _rejected (C:\Users\admin\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:844:24)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\admin\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\admin\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:788:41)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:604:44
System info:
Bower version: 1.4.1
Node version: 0.10.22
OS: Windows_NT 6.1.7601 ia32

Thanks.

**Comment by mbostock** [comment]
This appears to be a permissions issue with your filesystem, as indicated by the EPERM error, and is not related to D3. I’m afraid I cannot help you debug Windows technical issues.

**Comment by tapan-d-thakkar** [comment]
okay, but It's working when i remove d3 from bower,json and keep only Angular dependency. So i tried bower install only with angular and i am able to see it in my bower_components folder. So i don't see it as a file permission issue, as you see in that EPERM path, process is using user home for operation where I have full permission.

Let me know if I can help you with any other details to debug this issue.

**Comment by tapan-d-thakkar** [comment]
@mbostock i was able to resolve this issue by executing "npm uninstall -g bower && npm update decompress-zip && npm install -g bower" as mentioned https://github.com/bower/bower/issues/798
