### ISSUE TITLE
Layout.pie: NaN start/end angle when all values are zero

### ISSUE THREAD

**Issue by mauromelis** [mbostock/d3#2475]
I found a problem when using d3.layout.pie + d3.svg.arc to draw a simple piechart from collection.
When all data values are `0`, pie layout returns arc objects with `NaN` start and end angles (but startAngle of first object is `0`). When at least one value is defined, all is fine, and `0` arcs have same start/end angle as expected.
Actually I can check for `NaN` values by custom svg.arc accessors, but hope you can solve by returning objects with both start and end angle at `0`.

You can find an example and a fiddle here:
```javascript
var pie = d3.layout.pie();
var data = [0, 0];
// pie(data) returns:
[{ startAngle: 0, endAngle: NaN, data: 0, value:0, padAngle: 0 },
{ startAngle: NaN, endAngle: NaN, data: 0, value:0, padAngle: 0 }]
```
https://jsfiddle.net/et7c4hxt/

Moreover, maybe this request could be the fix: 
Layout.pie: Division by zero when sum(values) is 0
https://github.com/mbostock/d3/pull/2420

**Comment by figureone** [comment]
+1 to the suggested fix. In the meantime I am fixing NaN values in startAngle and endAngle with custom accessors:
```
var arc = d3.svg.arc()
    .startAngle( function ( d ) { return isNaN( d.startAngle ) ? 0 : d.startAngle; })
    .endAngle( function ( d ) { return isNaN( d.endAngle ) ? 0 : d.endAngle; });
```

**Comment by clayzermk1** [comment]
:+1: Also seeing this. Performing a `NaN` check does seem like a decent way of fixing this.

**Comment by mbostock** [comment]
Covered by #2420.
