### ISSUE TITLE
Image height/width in style cannot transition

### ISSUE THREAD

**Issue by dzhang55** [mbostock/d3#2477]
I'm not sure if this is a bug with d3, but when I define an image's height/width as a CSS style property instead of an attribute, it does not work with d3 transitions. I attempted to make a styleTween() for it, but regardless of what height/width I had already assigned my initial value would evaluate to "auto". 
![screen shot 2015-06-24 at 6 35 56 pm](https://cloud.githubusercontent.com/assets/11249514/8343110/e8f7c5e0-1a9f-11e5-8462-208e754ff091.png)
For example, this image would simply have a height and width of 50px, with no transition from 120px. Defining height/width as an attribute works as usual.

**Comment by mbostock** [comment]
The problem is that you are not specifying units, and CSS requires units. Try this:

```js
selection
    .style("height", "120px")
    .style("width", "120px")
  .transition()
    .style("height", "50px")
    .style("width", "50px");
```

**Comment by dzhang55** [comment]
I've tried it with units as well, and the transition does not work either.

http://bl.ocks.org/dzhang55/c08c31e6202489669adf

**Comment by mbostock** [comment]
That’s because you are using an SVG image, which requires attributes. You can only use width and height style properties on HTML image elements.

**Comment by dzhang55** [comment]
I see, thank you!
