### ISSUE TITLE
Add a "setdefault" to d3.map

### ISSUE THREAD

**Issue by rmadsen** [mbostock/d3#2479]
I think a function that performs an get-or-insert-default-and-return operation like [Python's `dict.setdefault(key, defaultVal)`](https://docs.python.org/2/library/stdtypes.html#dict.setdefault) would be a useful addition to the map operations.

An implementation could look like this:
```js
setdefault: function(key, default) {
   return d3_map_has(key) ? get(key) : set(key, default);
}
```

This makes it significantly easier to create new nested data sets. For example, imagine trying to create a mapping from a node to a list of its neighbors from a list of links (a.k.a edges). With `setdefault` the code looks like this:

```js
var neighbors = d3.map();
links.forEach(function(link, i) {
    neighbors.setdefault(link.source, []).push(link.target);
    neighbors.setdefault(link.target, []).push(link.source);
});
```

If you agree that this would be a useful addition, I'd be happy to create a pull request with an implementation and tests.

Thanks!
Ryan

**Comment by mbostock** [comment]
d3.map and d3.set are going away in favor of ES6 Map and Set, so I don’t plan on adding any new functionality to them.

**Comment by rmadsen** [comment]
Ok, thanks! I'll close this issue then.
