### ISSUE TITLE
Selection.call() does not finish before executing the next method.

### ISSUE THREAD

**Issue by SpencerCarstens** [mbostock/d3#2482]
I searched but did not find an open issue for this, sorry if it's a dupe or a known thing.

#### Issue:
When calling a function on a selection using selection.call(), the function is not allowed to finish before the next method in the chain is fired.

#### Repro:
In the below example, we have a selection of `link` that I wish to fade out and then `.remove()`. What happens in the non-working example is, `no()` is called and before it can begin the transition, the element is pulled from the DOM. In the working example, moving the `.remove()` into the `yes()` function fixes this issue. 

#### Code:
```javascript
/**
* Working
*/
link.exit()
  .call( yes );

function yes() {
  this.transition()
    .duration( 250 )
    .style( 'opacity', '0' )
    .remove();
}

/**
* Not Working
*/
link.exit()
  .call( no );
  .remove();

function no() {
  this.transition()
    .duration( 250 )
    .style( 'opacity', '0' );
}
```

**Comment by alignedleft** [comment]
Once a transition is initiated, it is "asynchronous" in the sense that it doesn't prevent subsequent code from running. So this is correct behavior. If you want something to execute at the end of the transition, use syntax like:

```javascript
this.transition()
  .duration(250)
  .style('opacity', 0)
  .each('end', function() {
    this.remove();
  });
```

**Comment by SpencerCarstens** [comment]
Awesome! Thanks! :+1:

**Comment by SpencerCarstens** [comment]
Thanks for the reply @alignedleft that is great info to know. :)

It works great inside the example `yes()` function, but does not solve the issue I was experiencing. 

`.call()` returns the selection and therefore the following chain would go from there. So, calling `.each('event',...` after the `.call()` throws an `a.call is not a function` error.

**Comment by mbostock** [comment]
I recommend using transition.remove, which is intended for exactly this use case. I’d only listen for transition end events if you need to do something more complicated. (The nice thing about transition.remove is that it automatically cancels removal if the transition is interrupted or another transition is scheduled on the elements that were going to be removed.)
