### ISSUE TITLE
d3.geo: problem with graticule with a CSS fill attribute 

### ISSUE THREAD

**Issue by templth** [mbostock/d3#2483]
Hello,

I try to define a graticule with a background color as described below:

    var graticule = d3.geo.graticule();

    var sel = d3.select(document.getElementById("someId"));
      sel.append('path')
         .attr('id', layer.id)
         .datum(graticule)
         .attr('class', 'graticule')
         .attr('d', path);

Here is the content of the CSS class `graticule` I use:

    .graticule {
      fill: #a4bac7;
      stroke: #777;
      stroke-width: .5px;
      stroke-opacity: .5;
   }

I have strange results with an orthographic projection:

![image](https://cloud.githubusercontent.com/assets/558344/8472305/62634ebc-20a0-11e5-9c28-54d8d390071b.png)

![image](https://cloud.githubusercontent.com/assets/558344/8472313/736414a8-20a0-11e5-96d1-be027d133be1.png)

Here are the versions of tools (d3 and topojson):

    "d3": "~3.5.5",
    "topojson": "1.6.19"

Thanks very much for your help,
Thierry

**Comment by mbostock** [comment]
The graticule is a MultiLineString geometry and should not be filled. Use a `{type: "Sphere"}` or [graticule.outline](https://github.com/mbostock/d3/wiki/Geo-Paths#graticule_outline) instead. For example:

http://bl.ocks.org/mbostock/5288571

**Comment by templth** [comment]
Thanks very much, Mike! I wasn't aware of this... I made a try with sphere type and it works fine!
