### ISSUE TITLE
Update 3.5.5 to 3.5.6 on home page

### ISSUE THREAD

**Issue by alignedleft** [mbostock/d3#2492]
On [d3js.org](http://d3js.org/), the CDN `src` link should be updated to 3.5.6. The "latest version" mention should also be updated.

BTW, where does the source for the website live? In the future, I could submit a PR and not bother you with an issue.

**Comment by mbostock** [comment]
Fixed. Sorry. I was just waiting for CDNJS to update and then I got distracted because it apparently takes a few days…

The repo is [d3/d3.github.com](https://github.com/d3/d3.github.com).

**Comment by alignedleft** [comment]
Cheers, thanks, Mike.
