### ISSUE TITLE
Relative import paths indistinguishable from third-party modules

### ISSUE THREAD

**Issue by callumlocke** [mbostock/d3#2495]
For example in [src/geo/mercator.js](https://github.com/mbostock/d3/blob/master/src/geo/mercator.js):

```js
import "../math/trigonometry";
import "geo";
import "projection";
```

Is there a reason you've avoided using paths like `./geo` and `./projection`?

Explicit relative paths would make it more obvious that these are not third party modules.

And it would make the code more interoperable with Node and other tools that assume this convention, like [Github Linker](https://chrome.google.com/webstore/detail/github-linker/jlmafbaeoofdegohdhinkhilhclaklkp?hl=en) (notice the incorrect link target in the screenshot below).

![image](https://cloud.githubusercontent.com/assets/250617/8680327/995a96de-2a58-11e5-860c-36f24c636f95.png)

**Comment by mbostock** [comment]
Thankfully, this is going away with 4.0 with the adoption of ES6 modules and [Rollup](http://rollupjs.org). (See [d3-arrays](https://github.com/d3/d3-arrays/blob/master/index.js) for an example.)

**Comment by callumlocke** [comment]
awesome. glad you're moving to rollup, it's the one
