### ISSUE TITLE
Feature request: smooth dragging in behavior.drag

### ISSUE THREAD

**Issue by masedesign** [mbostock/d3#2496]
What this means:  Dragging doesn't stop exactly where my mouse stops. Similar to how Google maps works (it allows you to drag and fling your visualization for faster maneuvering). This would match the zoom in/out style that is already implemented in `behavior.drag` (which we get for free as it uses the browsers scroll event, I believe).

**Comment by mbostock** [comment]
Related #2096, which applies to the zoom behavior.

**Comment by masedesign** [comment]
cool, thanks @mbostock closing this one out
