### ISSUE TITLE
Transition with transform=translate(x,y) using integers for x & y values in Firefox 38+ cause black background to flicker

### ISSUE THREAD

**Issue by nicthemighty** [mbostock/d3#2497]
Very simple test case. In Firefox 38+, when you click the buttons with integer x,y values, when the transition ends, the blank space between the two elements inside the node flickers black.

This does not happen in IE or earlier versions of Firefox. It also doesn't happen if the x,y values are floats. Also does not happen if there is no transition.

```html
<html>
<body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.js" charset="utf-8"></script>
<script>
function translate(){
	d3.select("#node").attr("transform", function() {return "translate(10,10)";});
}

function translate2(){
	d3.select("#node").transition().attr("transform", function() {return "translate(20.2,20.2)";});
}

function translate3(){
	d3.select("#node").transition().attr("transform", function() {return "translate(15,15)";});
}
</script>

<svg height="400" width="400">
<g transform="translate(20,20)">
    <g id="node">
        <g><circle r="5"></circle></g>
        <g transform="translate(50,0)"><text>test</text></g>
    </g>
</g>
</svg>
<button onclick="translate()">10,10 (no transition)</button>
<button onclick="translate2()">20.2,20.2</button>
<button onclick="translate3()">15,15</button>
</body>
</html>
```

**Comment by nicthemighty** [comment]
Please note, this only happens with a translate transformation. I've tried with transform=rotate and it does not occur.

**Comment by mbostock** [comment]
I’m not able to reproduce this on Mac OS X (Firefox 41). But this sounds like a rendering/antialiasing issue with Firefox, and it probably wouldn’t be something we could fix in D3 regardless. Sorry for not being helpful and for taking so long to reply!
