### ISSUE TITLE
How to create a drawing with shadows and colors with muliple faces using d3js

### ISSUE THREAD

**Issue by 3gwebtrain** [mbostock/d3#2503]
Can any one answer to this question: http://stackoverflow.com/questions/31636184/how-to-create-a-drawing-with-shadows-and-colors-with-muliple-faces-using-d3js

**Comment by jamesleesaunders** [comment]
Hi 3gwebtrain, Sorry, the GitHub issues register is not the right place to ask this sort of question, it is for reporting D3 bugs and issues. stackoverflow is the correct place to ask this question (which you have done).
All the best,
Jim
