### ISSUE TITLE
data key function

### ISSUE THREAD

**Issue by lakerka** [mbostock/d3#2505]
var arr = ['a', 'b', 'c', 'd']

        var svgRows = svg.selectAll(".row")
            .data(arr, function(d, i) { return new Object(); })
            .enter()
            .append("g");

This snippet instead of creating 4 group elements creates single group element where binded data equals 'a'.

**Comment by mbostock** [comment]
The key function must return a string, and the string-coerced value of `new Object()` is `"[object Object]"`, so all elements have the same key in the code snippet you posted, and therefore there is only a single `G` element created.
