### ISSUE TITLE
d3 + react: path attribute differs in node vs browsers

### ISSUE THREAD

**Issue by jarib** [mbostock/d3#2510]
I'm trying to write a universal / isomorphic webapp in React, using D3 to calculate `path` attributes for some SVG maps. 

There seems to be a single character/decimal difference in the calculation between Node and Chrome that makes the `path` string slightly different. This is not ideal since the DOM/SVG rendered server-side has to be thrown out. 

Here's the warning from React.

![image](https://cloud.githubusercontent.com/assets/572/9041117/91f556dc-3a06-11e5-91d9-fe334d311dea.png)

Any idea if this can be solved, or how I can investigate further?

**Comment by jarib** [comment]
The error is slightly different in Safari and Firefox:

Safari: 

![image](https://cloud.githubusercontent.com/assets/572/9041338/ed437856-3a07-11e5-8ea1-21b0ef78fc29.png)

Firefox:

![image](https://cloud.githubusercontent.com/assets/572/9041386/052bf11e-3a08-11e5-81fd-24eeb61cac93.png)

**Comment by gordonwoodhull** [comment]
You generally are not going to get exactly the same floating-point calculations with different renderers (and there are petty differences in path syntax). 

Try this with IE if you want to see a dramatically different result!

**Comment by jarib** [comment]
Right - but is there any way around it? At least in Chrome's case it seems like the fraction could be truncated to a fixed number of decimal points without causing significant problems.

**Comment by mbostock** [comment]
There are a few ways you could solve this, such as by parsing the generated SVG string and rounding to a given precision. But it’s not in-scope for D3 to ensure that generated path strings are identical on all platforms due to differences in floating point behavior, so I’m closing this issue.

**Comment by jarib** [comment]
Thanks. It seems to work OK if I cut the paths down to 8 decimal places:

```javascript
import parse from 'svg-path-parser';

function truncatePath(d, precision) {
    return parse(d).map(cmd => {
        if (cmd.code === 'Z') {
            return 'Z';
        } else {
            return `${cmd.code}${cmd.x.toFixed(precision)},${cmd.y.toFixed(precision)}`
        }
    }).join();
}

truncatePath(
    "M354.59423930727576,16.437855381383088L355.8425045944949,14.59145065458506",
    8
);
// M354.59423931,16.43785538,L355.84250459,14.59145065
```
