### ISSUE TITLE
D3.js Truck Factor

### ISSUE THREAD

**Issue by gavelino** [mbostock/d3#2515]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **D3.js** and obtained a value of **1**.

The developer responsible for this TF is:

Mike Bostock - author of 93% of the files 

To validate our results, we would like to ask **D3.js** developers the following three brief questions:

(a) Do you agree that the listed developer is the main developer of **D3.js**?

(b) Do you agree that **D3.js** will be in trouble if the listed developer leave the project (e.g., if he wins in the lottery, to be less morbid)?

(c) Does **D3.js** have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by mbostock** [comment]
This is neither a bug report or a feature request, so closing this issue. You can answer questions (a) and (c) yourself, and (b) is an existential, speculative question that I will not attempt to answer.

**Comment by gavelino** [comment]
Thank you.
