### ISSUE TITLE
.property setter with an undefined or null value doesn't remove the property

### ISSUE THREAD

**Issue by vp2177** [mbostock/d3#2525]
The .attr setter, called with a value of `undefined` or `null`, removes the attribute from the element(s).

Unlike the .property setter, which doesn't remove the property, but doesn't set it either.
I think it should be consistent with the .attr setter

**Comment by mbostock** [comment]
Yes, selection.property does delete the property if a null or undefined value is passed:

```js
> d3.select("body").property("foo", 42)
[Array[1]]
> document.body.foo
42
> d3.select("body").property("foo", null)
[Array[1]]
> document.body.foo
undefined
> "foo" in document.body
false
```

I think it’s possible some versions of IE don’t behave correctly if you try to `delete element.foo`, but that would be a browser bug, and D3 is not a compatibility layer.

**Comment by vp2177** [comment]
Okay, for an `<input type=checkbox>`, doing `d3.select('input[type=checkbox]').property('checked', undefined)` doesn't remove it.

**Comment by vp2177** [comment]
But then again, `delete document.querySelector('input[type=checkbox]').checked` doesn't, either.

**Comment by mbostock** [comment]
Right. That’s because `checked` is a built-in property: you can’t delete built-in properties.
