### ISSUE TITLE
Calling style with integer as value throwing Error on IE9

### ISSUE THREAD

**Issue by SRachamim** [mbostock/d3#2527]
When calling style function with integer as value, an 'Invalid arguments' Error is thrown on IE9.

For example:
```
el.append('rect')
  .style('height', 70)
  .style('width', 63);
```

I think in this case a 'px' should be added by default.

**Comment by mbostock** [comment]
Sorry, but D3 is not a compatibility layer. If you are specifying styles, you must use appropriate units ("70px" and "63px", here).

**Comment by benjamingr** [comment]
You might want to consider either warning against it in the docs or at least not use raw numbers in the examples without mentioning it.

**Comment by mbostock** [comment]
I have added a warning to the documentation and corrected the example there. (If that’s the one you were referring to.) The wiki is publicly-editable, and although this presents a risk of some users adding misleading examples, in general the net contribution is positive.

Thank you for your understanding.

**Comment by benjamingr** [comment]
Thanks for fixing the documentation. Cheers.
