### ISSUE TITLE
repositioning the parent node while dragging makes object to jump around

### ISSUE THREAD

**Issue by ebengtso** [mbostock/d3#2529]
I have a rectangle with resize handles, which i use to resize my rectangle.
```
<g>
<g id="rects" transform="translate(x,y)"><rect></g>
<g id="handles" transform="translate(x,y)"><rect id="handle1"><rect id="handle2"></g>
</g>
```
I have added a drag listener on each handle, and then I resize the rects group and apply a transform on both rects and handles to reposition the rectangle and handles.

If I change the position of the parent during drag I reproduce the problem, and using the origin does not solve the problem.

The only workaround to my problem is removing the group of handles and applying a transform on each of them to reposition each handle

A solution is provided in the pull #1055

**Comment by mbostock** [comment]
You need to apply the drag behavior at the same level that you are transforming. If you transform the parent, the drag behavior will get confused.
