### ISSUE TITLE
Inheritence is nearly impossible right now

### ISSUE THREAD

**Issue by Fathardie** [mbostock/d3#2539]
Hi everyone!

I have been trying to create extensions(inheritence) of certain d3 components but with the current code structure it is really hard to do that. Lets have a look at the axis component to show you an example:
```
function axis() {
  function axis(selection) {

  }

  axis.scale = function(x) {
    if (!arguments.length) return scale;
    scale = x;
    return axis;
  };
}
```
This is great and it works! However, when I want to create a function axis_child that inherits everything from axis and extends it with functionality (while creating a new callable function and holding a reference to the old one), we have a problem:

```
function axis_child() {
    var parent = d3.svg.axis();

   function axis_child(selection) {
       selection.call(axis)
   }
   $.extend(axis_child, parent);

   axis_child.scale_child = function(y) {
          //Awesome new functionality here
   }
}
```
```
Use case:
selection.call(axis_child().scale().scale_child()) //Error! axis does not have function scale_child
```
The problem is that the reference inside of axis.scale is to the axis function object and not to this. We can use the scale function from axis_child, but the return value is set to axis therefor rendering any axis_child functions useless thereafter. Also, when we save this instance, we are saving an axis function object and not a axis_child function object!
```
var axis_child = axis_child().scale()  //Error! This is now an axis, not an axis_child!
```

We can fix these issues fairly easily by referencing this instead of the function object but it will take a significant refactoring of all of the "configuration" functions for objects such as axis.

Our inheritence scheme could than be as proposed above. Is it possible to process this request or am I missing something crucial which is the reason you chose the direct function object reference over the this reference?

Thanks!

**Comment by gordonwoodhull** [comment]
I think [d3.rebind](https://github.com/mbostock/d3/wiki/Internals#rebind) helps with this.

**Comment by Fathardie** [comment]
That indeed has almost the exact functionality which I need! Thank you! However, in order for this to work, a lot of wrapper functions are created. For each of the functions in the source element one wrapper is created and that is added to target. By refactoring to 'return this', wouldn't we be able to remove the wrapper all together and just copy functions straight up? It is a very small performance increase, but a performance increase all together.

**Comment by mbostock** [comment]
Some of the awkwardness has to do with creating classes that effectively extend Function. A d3.svg.axis instance is not just an object, it’s a function that you can call (typically via selection.call). That makes it a little harder to extend than a normal object in ES5.

The other thing you’re running into is probably related to the age-old debate of composition versus inheritance. I prefer composition because it has a tendency to be safer and less leaky than inheritance. That can mean some additional code to expose wrapper functions, but often that code is trivial.
