### ISSUE TITLE
Limiting the zoom for time axis using scaleExtent() not working

### ISSUE THREAD

**Issue by mantri-govind** [mbostock/d3#2542]
Tried putting boundaries for x-axis using scaleExtent() and even tried putting the same with custom methods on Scroll event but it isn't working while the same thing with linear scale worked. Anyone came across this issue?

**Comment by mbostock** [comment]
The zoom.scaleExtent limits the scale factor of zooming; it does not restrict translation (panning). 

It sounds like you’re asking for #2019? (If I didn’t understand your request, let me know more details and I’ll re-open.)
