### ISSUE TITLE
Uncaught TypeError: string.slice is not a function

### ISSUE THREAD

**Issue by FallenRiteMonk** [mbostock/d3#2543]
Hy,

I get the following error trying to format a Date:

```
Uncaught TypeError: string.slice is not a function
d3_time_parseMonthNumber @ d3.js:2770
d3_time_parse @ d3.js:2556
format.parse @ d3.js:2532
(anonymous function) @    My line of code:    dateaset.forEach(function(d) { 
makeGraphs @    My line of code:    dateFormat.parse(d:timestamp);
notify @ queue.js:47
(anonymous function) @ queue.js:39
(anonymous function) @ d3.js:1991
event @ d3.js:504
respond @ d3.js:1944
```

Where:

```
var dateFormat = d3.time.format("%m/%d/%Y");
```

and 

```
d.timestamp = new Date(d.header.timestamp.long); // Outputs correct date
```

**Comment by mbostock** [comment]
It looks like you are passing a Date (`d.timestamp`) to format.parse? Is that possible? If you want to parse a string into a date, use format.parse; if you want to format a date into a string, use format.

**Comment by danieldram** [comment]
You will also get this error if the date is not a String, ie: '20110808' <-- correct, whereas 20110808 will give you an error as it's not a string and the function cannot slice/format it.

**Comment by mbostock** [comment]
Yes. [*format*](https://github.com/mbostock/d3/wiki/Time-Formatting#_format) expects a Date as input, and [*format*.parse](https://github.com/mbostock/d3/wiki/Time-Formatting#parse) expects a String. As it is currently implemented, the behavior is undefined if you give it anything else. I’ll consider adding type coercion in 4.0 (see d3/d3-time-format#14).

(Note that type-coercion if you pass a Date to parse, as described by the OP, is somewhat confusing. The Date is first coerced to a string, and then reparsed as a new Date. I suppose that might be intended, but typically if you already have a Date, then you don’t need to parse it.)

**Comment by danieldram** [comment]
Sorry I didn't mean that comment to be taken as an issue! I think it's fine without type coercion, one of the biggest issues with JavaScript without use-strict was coercion. I was just leaving a comment there for anyone else who had a similar error and usually it's due to the fact you're parsing an integer rather than a string, so either just run a .map to convert them to strings, or have it converted in the calling function per element.

Thanks for the response!
