### ISSUE TITLE
Seeded random

### ISSUE THREAD

**Issue by Petah** [mbostock/d3#2544]
It would  be nice to be able to seed the random number generator. This would enable us to have consistent results between pages loads for things like the force layout.

Or at least be able to inject a PRNG so we can provide our own.

**Comment by mbostock** [comment]
Hrm. Is it not sufficient to overwrite Math.random, as [seedrandom](https://github.com/davidbau/seedrandom) does? I know it’s a bit icky to overwrite built-in methods, but that seems relatively safe in this case.

**Comment by Petah** [comment]
No as I would want to provide a seed per force layout graph. As I could have many on the page, if I just override Math.random, it will depend on load order of the graphs and what other libraries also use Math.random.

**Comment by Lucas-naceri** [comment]
This is a seeded random.

**Comment by mbostock** [comment]
This is now covered by d3/d3-random#6.

**Comment by Petah** [comment]
@mbostock how does this solve the problem?
