### ISSUE TITLE
D3.brush drag not working properly on MS Surface and IE11 with touch

### ISSUE THREAD

**Issue by wassx** [mbostock/d3#2545]
Testing with example: http://bl.ocks.org/mbostock/4349545 I recognised, that touch drag on handles does not work for the brush with IE11 on MS Surface. When i try to drag handles with mouse or stylus it works as expected. The events for "brush", "brushstart", "brushend" are fired but the handles do not change.

**Comment by mbostock** [comment]
Duplicate of #2403.
