### ISSUE TITLE
SHA-1 Certificate warning when loading with firefox

### ISSUE THREAD

**Issue by DannyArends** [mbostock/d3#2553]
The following warning appears when I load the d3.min.js javascript from: https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js

"This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1."

I have no idea if this is the right place however

**Comment by jimaek** [comment]
You can use https://cdn.jsdelivr.net/d3js/3.5.6/d3.min.js instead. No errors

**Comment by DannyArends** [comment]
OK thanks, Just a note: 
The frontpage on the d3js.org website mentions the cdnjs.cloudflare.com one
Perhaps it is worth updating the link.

Thanks for the mirror, I recon this issue can be considered closed

**Comment by mbostock** [comment]
What browser are you using? Chrome 45 doesn’t issue any warnings, but that doesn’t mean SHA-1 signatures are inadequate. Though, I am surprised that Cloudflare wouldn’t be applying current security best practices.

**Comment by DannyArends** [comment]
Firefox 40.0.3, see the attached screenshot for info and the warning (German)

![sha1 error](https://cloud.githubusercontent.com/assets/47902/9870599/ad028136-5b8d-11e5-8f95-bebc08b67fe2.png)

**Comment by mbostock** [comment]
From <https://developer.mozilla.org/en-US/docs/Web/Security/Weak_Signature_Algorithm>:

> SHA-1 based signatures are common; as of May 2015, they comprise roughly 45% of signatures used in digital certificates. However, SHA-1 is showing its age and its continued use is discouraged. When your certificates are replaced, ensure that a stronger signature algorithm (such as SHA-256) is used.
> 
> SHA-1 certificates will no longer be treated as secure by major browser manufacturers beginning in 2017.
