### ISSUE TITLE
Preserve comments in distributed d3.js single file

### ISSUE THREAD

**Issue by JabbyPanda** [mbostock/d3#2554]
I would be nice to alter Makefile script to include `--comments` [uglify] (https://github.com/mishoo/UglifyJS2/blob/master/README.md) library directive that will include comments into resulted single `d3.js` file in dist folder. 

I guess only developers, not end-users are interested in`d3.js` file and developers like commented code.

**Comment by mbostock** [comment]
Will respond in #2555.
