### ISSUE TITLE
D3 is calling setAttribute, instead of setAttributeNS on fePointLight element.

### ISSUE THREAD

**Issue by afanasy** [mbostock/d3#2561]
```
d3.select('body').append('svg').append('fePointLight').attr('x', '1%')
```
gives
```
Error: Invalid value for <fePointLight> attribute x="1%"
```
I'm working around this bug currently by calling  `setAttributeNS` directly,
while d3 for some reason calls `setAttribute`, which is causing the problem.

**Comment by Wooyol** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

neolaocoon@naver.com 님께 보내신 메일 <[d3] D3 is calling setAttribute, instead of setAttributeNS on fePointLight element. (#2561)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by mbostock** [comment]
The selection.attr method always uses element.setAttribute unless you explicitly specify a namespace. If you want to specify the SVG namespace for the "x" attribute, for example, you need to say `selection.attr("svg:x", …)` instead. See [d3.ns](https://github.com/mbostock/d3/wiki/Namespaces) for the supported namespaces.

But, you shouldn’t need to specify the SVG namespace when setting an SVG attribute on an SVG element. The only case I’m aware of where you need to specify an attribute namespace is an SVG attribute from the xlink namespace, such as `<use xlink:href="…"/>` (see [SVG specification](http://www.w3.org/TR/SVG11/struct.html#UseElementHrefAttribute) and [example usage](http://bl.ocks.org/mbostock/bc4e32ec71636b498c46)).

**Comment by afanasy** [comment]
Thanks for giving the hint about namespaces "svg:x"! May be it's Chrome problem then (throwing error when doing `setAttribute` on `fePointLight`).
