### ISSUE TITLE
My chart's legend and axis labels don't show up in Chrome

### ISSUE THREAD

**Issue by chrismp** [mbostock/d3#2564]
I posted my issue on [Stackoverflow](http://stackoverflow.com/questions/32799604/my-d3-charts-legend-and-axis-tick-labels-appear-in-firefox-but-not-chrome).

I made a grouped bar chart, but the legend and axis labels don't show up in Chrome. It looks fine in Firefox, though. Attached are files showing how the chart looks in Firefox vs Chrome.

What am I doing wrong?

![ffchart](https://cloud.githubusercontent.com/assets/7936571/10119195/b34e89e0-645c-11e5-9026-33fde43b963d.PNG)
![chrome chart](https://cloud.githubusercontent.com/assets/7936571/10119196/b34ff6e0-645c-11e5-9cad-ab280a5984d8.PNG)

**Comment by CrandellWS** [comment]
https://github.com/chrismp/chrismp.github.io/pull/1

**Comment by CrandellWS** [comment]
can we close this issue please and thanks.

**Comment by CrandellWS** [comment]
You will have to as I can not
