### ISSUE TITLE
Fn invocation after ticks removal

### ISSUE THREAD

**Issue by sebadom** [mbostock/d3#2572]
I have a time scale axis with ticks.. the domain changes on several actions, and I need to run some code after old ticks are removed. I can't seem to find a way to do accomplish that... is there something i'm missing or is this not supported?

Thanks

**Comment by mbostock** [comment]
When you `selection.call(axis)`, the code runs immediately, modifying the DOM. So if you want to run some code after updating the axis, you simply run your code after calling the axis. (If you use a transition, then you can use the transition *end* event.)

**Comment by sebadom** [comment]
Thank you for your clarification
