### ISSUE TITLE
Display Table based on Selection

### ISSUE THREAD

**Issue by jt4000** [mbostock/d3#2574]
If you press on the specific bar or line, a table with data should appear below based on selection.

Question:
Is it possible to do it in d3?

Info:
A concrete example is this picture below.

Thanks!

![ggg](https://cloud.githubusercontent.com/assets/14993569/10330321/f7ec4d0e-6ccb-11e5-87c7-51fbddf720ef.png)

**Comment by CrandellWS** [comment]
Yes
Have a look at the gallery demos found at https://github.com/mbostock/d3/wiki/Gallery.

As for examples, you can see an implementation for what you describe at http://square.github.io/crossfilter/ then you could embed a line chart into the table http://bl.ocks.org/llimllib/841dd138e429bb0545df 

You might look at this demo as well http://xliberation.com/googlecharts/d3flights.html

Please close this issue, thanks.
