### ISSUE TITLE
transition chaining with arbitrary delays

### ISSUE THREAD

**Issue by cool-Blue** [mbostock/d3#2579]
Currently, if you chain transitions using `transition("t1").delay(1000).duration(2000).transition("t2").delay(1000)`, the second transition will interrupt the first after 1 sec: before the first one actually starts.  I guess the second transition has a delay of 3000 added to it which is subsequently overwritten by 1000.   
Are there any plans to allow delays on chained transitions?

**Comment by mbostock** [comment]
Chained transitions work by implicitly computing the delay for you. So, either you chose to specify the delay explicitly, in which case the benefit of chaining transitions is that you inherit the same reference time, namespace, easing, and duration; or, you don’t, and the delay is implicitly set to the previous transition’s delay + duration.

If you want to add a delay between chained transitions, an easy way to do this is to have a no-op transition in between:

```js
selection.transition() // this transition runs from t=1s to t=3s
    .delay(1000)
    .duration(2000)
  .transition() // then a delay from t=3s to t=4s
    .duration(1000)
  .transition() // then lastly another transition from t=4s to t=5s
```

Though, note that the last transition in this chain inherits the 1s duration, so it’s shorter than the first 2s transition.

**Comment by cool-Blue** [comment]
That fixes it for me and it's clean(ish)... although we have the situation where delay is delay... unless we say so! (...shut up and eat yer porridge).  

I wonder if delay per se should be exposed if it's behaviour is hijacked by chained transitions: would it be better if `selection.delay(t)` was actually implemented as `selection.transition().duration(t)`?  

Thanks for updating the wiki, I was going to do that but I was struggling with interrupted transitions and was going to update after I completed my understanding.
