### ISSUE TITLE
Linear scale: Nice domain and ticks do not always match

### ISSUE THREAD

**Issue by moshevds** [mbostock/d3#2580]
Compare this sentence from https://github.com/mbostock/d3/wiki/Quantitative-Scales#linear_nice:
> The optional tick count argument allows greater control over the step size used to extend the bounds, guaranteeing that the returned ticks will exactly cover the domain.

With this result from the current implementation:
```javascript
var scale = d3.scale.linear().domain([-0.1, 51.1]).nice(8);
scale.domain(); // => [ -5, 55 ]
scale.ticks(8); // => [ 0, 10, 20, 30, 40, 50 ]
```
In most cases I do get the result I expected, for example:
```javascript
var scale = d3.scale.linear().domain([6.3, 74.2]).nice(8);
scale.domain(); // => [ 0, 80 ]
scale.ticks(8); // => [ 0, 10, 20, 30, 40, 50, 60, 70, 80 ]
```

I looked at `d3_scale_linearTickRange`. The problem apparently stems from the step-size heuristic and its dependency on the values that `nice` is changing. I don't feel comfortable proposing a completely different heuristic, perhaps you would consider a patch to calculate the heuristic twice?

For comparison:
```javascript
var scale = d3.scale.linear().domain([-0.1, 51.1]).nice(8).nice(8);
scale.domain(); // => [ -10, 60 ]
scale.ticks(8); // => [ -10, 0, 10, 20, 30, 40, 50, 60 ]
```

**Comment by mbostock** [comment]
Moved to d3/d3-scale#9.
