### ISSUE TITLE
chord visual bug on blink

### ISSUE THREAD

**Issue by matheusramos** [mbostock/d3#2583]
There is a visual bug in chord layout in browsers based on Blink. When resizing the browser window, the bug occurs:

![Chord Bug](http://i.imgur.com/Mw7Bvcp.png)

It happens in Chrome and Opera, but not in Firefox. It is possible to reproduce the bug in the following links:
- https://www.jasondavies.com/mobile-lawsuits/ (1165x647 window)
- http://bl.ocks.org/StewartNoyce/9532973 (1280x647 window)

Since I don't know if the previous links use the latest version of d3, I made this [JSFiddle](http://jsfiddle.net/zqm3uz8h/) using the latest version and it is still possible to reproduce the bug.

This issue has been tested on:
- Google Chrome 45.0.2454.101
- Opera 32.0.1948.69
- Mozilla Firefox 41.0.1

**Comment by mbostock** [comment]
This is a browser bug.

https://code.google.com/p/chromium/issues/detail?id=514246

**Comment by matheusramos** [comment]
It is fixed in Google Chrome 46. Thanks.
