### ISSUE TITLE
Adding a dismiss event for (context) brush

### ISSUE THREAD

**Issue by sebailfico** [mbostock/d3#2587]
I think it could be useful to have an event being dispatched when a brush, particularly a context one, is dismissed, e.g. by clicking on an area of the chart free from the brush itself.
In the example shown in http://bl.ocks.org/mbostock/1667367 if you drag a brush and then click outside of it, it gets dismissed, but there's no esplicit event for this action.
Thanks.

**Comment by mbostock** [comment]
If you click outside of the brush (in the context area) in the linked example, it does fire the normal sequence of brushstart, brush and brushend events. The difference is that brush.empty returns true if the brush is empty on brushend.
