### ISSUE TITLE
Add name accessor to dsv/csv 

### ISSUE THREAD

**Issue by protobi** [mbostock/d3#2588]
Suggest adding an optional function to transform column names to dsv.parse(...), comparable to the row accessor added in #1107,

The motivation is that input datafiles may have column names...
* with arbitrary case generated from other packages that are case insensitive like SAS or SPSS, requiring conversion to some defined case in Javascript
* other software packages, e.g. SPSS, SAS, StatTransfer use their own rules to clean variable names with spaces, underscores, non-alphanumeric characters, duplicate / missing names, etc.

This is a tiny change to the public API referred to in PR https://github.com/mbostock/d3/pull/2429 

Submitting as a PR as it's nontrivial to monkey patch the new function . The method `dsv.parse` refers to private methods not exposed by d3, which themselves refer to other private methods.  

Another approach is to overwrite the row accessor to rename all the fields and return a new row but this seems clumsy esp for large files, http://stackoverflow.com/questions/26998476/right-way-to-modify-d3-csv-to-lower-case-column-names

**Comment by mbostock** [comment]
Merging into #2429.
