### ISSUE TITLE
using s format in 0 return 0y

### ISSUE THREAD

**Issue by UlTriX** [mbostock/d3#2595]
Using d3 version 3.5.6 using s formatter in 0 returns 0y
https://en.wikipedia.org/wiki/Metric_prefix y is yocto

**Comment by mbostock** [comment]
I can’t reproduce this issue.

```js
d3.format("s")(0) // "0"
d3.formatPrefix(0) // {symbol: ""}
```

Also, I’d be curious if you can reproduce this problem in the new [d3-format repo](https://github.com/d3/d3-format), which will be the 4.0 implementation.

**Comment by UlTriX** [comment]
I forgot to mention that it was d3.format("s")("0") that returned 0y

With other string values works fine. It was not supposed to work with strings?

**Comment by mbostock** [comment]
Great, thanks. Fixed the type coercion bug. Generally speaking it’s a bad idea to pass in the wrong type (and d3.format expects a number), but we should coerce to the right type, and I’ve fixed that bug in d3.formatPrefix, and by extension d3.format. Staged for 3.5.7 in #2591.
