### ISSUE TITLE
Update jsdom? (node 4)

### ISSUE THREAD

**Issue by maxkostow** [mbostock/d3#2596]
d3 currently relies on [jsdom 3](https://github.com/mbostock/d3/blob/v3.5.6/package.json#L54) which uses contextify which doesn't build on node 4. Is there any chance to update to jsdom 4+? It apparently breaks compatibility with node < 4 by [relying on a new `vm`](https://github.com/tmpvar/jsdom/blob/master/Changelog.md#400).

**Comment by mbostock** [comment]
Sucks that there’s no graceful upgrade strategy, but at least JSDOM was recently demoted to a development-only dependency so this only affects a subset of users.

I say we shouldn’t do this for a patch release with 3.5.7, but it seems reasonable to tie this to the 4.0 release.

**Comment by mbostock** [comment]
I’ve upgraded the 4.0 modules to use JSDOM 7.

**Comment by mbostock** [comment]
Fixed in 4.0, which now uses JSDOM 8.
