### ISSUE TITLE
Use of stack layout X accessor

### ISSUE THREAD

**Issue by aarthi0808** [mbostock/d3#2602]
I am clear about the actual usage of X accessor in stack layout. Though i gave x-accessor, stacking was   applied based on index.

```javascript
var layers = [
  {
    "name": "apples",
    "values": [
      { "x": "a", "y":  91},
      { "x": "b", "y": 290}
    ]
  },
  {  
    "name": "oranges",
    "values": [
      { "x": "b", "y":  9},
      { "x": "a", "y": 49}
    ]
  }
];

var stack = d3.layout.stack()
    .x(function(d){return d.x})
    .y(function(d){return d.y})
    .values(function(d) { return d.values; });
```

Here i have give x-accessor, See  in the second layer "orange" order of x value is not as same as order of x values in first layer . But stacking of data was only by index, not by "x".

**Comment by mbostock** [comment]
Stack values are always grouped by index. The purpose of the x-accessor is only to compute the derivative when using the “wiggle” offset. There was already some information about this in the API reference, but I’ve just edited it to hopefully make it clearer. Thanks for the report.
