### ISSUE TITLE
interval.offset where the step is not a whole number

### ISSUE THREAD

**Issue by tamc** [mbostock/d3#2611]
I was expecting d3.time.year.offset(new Date(), 0.5) to give me the date in six months time. Instead it gave me today's date. 

That was, for me, surprising. However, at a glance, this behaviour is implemented consistently across the time intervals. 

Does this mean the behaviour is intended? If so, I will update the docs on the wiki. If not, I will work on a patch.

**Comment by mbostock** [comment]
That’s intended. This functions like type coercion: an integer is expected, so the number is coerced to an integer. In 3.x it’s done implicitly, so your example functions like this:

```js
var d = new Date; // Fri Nov 06 2015 15:52:11 GMT-0800 (PST)
d.setFullYear(d.getFullYear() + 0.5); // 1446853931002
d; // Fri Nov 06 2015 15:52:11 GMT-0800 (PST)
```

In 4.0 (see [interval.js](https://github.com/d3/d3-time/blob/master/src/interval.js#L24) in [d3-time](https://github.com/d3/d3-time)), we explicitly use Math.floor. I’ll add a comment to the README over there.
