### ISSUE TITLE
"schedule is undefined" in d3 3.5.7

### ISSUE THREAD

**Issue by jpommerening** [mbostock/d3#2613]
Hi!
I just discovered a bug in the latest version (3.5.7) of d3. Version 3.5.6 is not affected.

Introduced [here](https://github.com/mbostock/d3/commit/14f54d7d65e88268eccaba7869864440f633a8fa#diff-8ec26bb2200335afde5d1a2c38280c16R8898) the function definition of "schedule" happens inside an `if` block, is not hoisted to the top and can thus not be used as a parameter for `d3.timer()`. Actually, function definitions inside an `if` are [prohibited in strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#Paving_the_way_for_future_ECMAScript_versions).

Seems to work in Chrome, but Firefox (38) throws an error: `ReferenceError: schedule is not defined`

**Comment by mbostock** [comment]
Looking.

**Comment by mbostock** [comment]
This is only a problem with the non-minified JavaScript, too.

This feels like a Firefox bug to me. I understand that the functions are hoisted, but this shouldn’t cause them to be undefined. Still, the fix is trivial.

**Comment by mbostock** [comment]
Fix staged in #2614. I will push a release shortly.

**Comment by jpommerening** [comment]
Cool, thanks!

Yes, that was the non-minified d3.js. But then again, another minifier might treat it differently :)

Anyway, thanks for the quick resolution :sparkles:

**Comment by tschneidereit** [comment]
> This feels like a Firefox bug to me. I understand that the functions are hoisted, but this shouldn’t cause them to be undefined.

It's not a bug per se: the behavior in cases like this used to be completely unspecified, and browsers just did different things. The ES6 spec finally contains a specification, if only [in an annex](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-functiondeclarations-in-ifstatement-statement-clauses). Note that the difference is that in SpiderMonkey, the function is *not* hoisted right now, whereas it is in other engines. Way more details than you're probably interested in can be found here: http://kangax.github.io/nfe/#expr-vs-decl. Implementing the spec'ed behavior is tracked in [bug 1071646](https://bugzilla.mozilla.org/show_bug.cgi?id=1071646).

**Comment by mbostock** [comment]
Thanks for the additional info; I wasn’t aware this was a recent standardization. I changed the release notes to be less accusatory. (Sorry!) I agree we should avoid conditional function declarations at least until the spec’d behavior is universally available.
