### ISSUE TITLE
Release v3.5.7 is not working with optimized almond modules

### ISSUE THREAD

**Issue by jrauschenbusch** [mbostock/d3#2617]
Since changing the function call `define(d3);` to `define(this.d3 = d3);` in the file `d3/src/end.js` an error occurs in optimized almond.js packaged modules:

`Cannot read property 'splice' of undefined (see https://github.com/jrburke/almond/issues/25)`

The change was introduced with:
commit-id: https://github.com/mbostock/d3/commit/1fad2e0cf7fba217eba0eadf3cae17c15090f1dd

An description of the problem is available here:
https://github.com/jrburke/almond/issues/25

It seems that the r.js optimizer cannot detect the new function param pattern and hence it is not converting it to the working function call define('d3',d3);

**Comment by mbostock** [comment]
This is a bug with r.js. You should file it over there.

That said, I can accommodate a workaround since it is trivial to do so.

**Comment by jrauschenbusch** [comment]
You are absolutely right. It is a bug with r.js. I'll file a bug over there.

Thx for your concession to fix it temporarily in d3.js with release v3.5.9!
