### ISSUE TITLE
D3 zoom not working with mousewheel in safari Version 8.0 (10600.1.25.1) (Mac)

### ISSUE THREAD

**Issue by sanjeevpande** [mbostock/d3#2626]
I am using d3.behavior.zoom().scaleExtent to achieve the zoom functionality. But this doesn't work in Safari Version 8.0 (10600.1.25.1) in Mac OS.
Even the example provided in the link http://bl.ocks.org/mbostock/6123708 doesn't work in above mentioned Safari version.
It works with double click and (shift + double click) but zoom with mousewheel doesn't work.

**Comment by mbostock** [comment]
Unfortunately, I no longer have a way of testing on Safari 8 and I am unable to reproduce your problem on Safari 9, so I am unable to investigate further. If you can provide further information then I will take another look.

**Comment by vbabenko** [comment]
@mbostock 
Hey, I have similar behavior and I can reproduce on Safari 10 (FF, Chrome works as expected).
Here is a fiddle https://jsfiddle.net/vbabenko/zq0v1rta/1/

Reproduce (Safari):
1. Wheel zoom on 'red' block
>> zoom works

2. Try to wheel zoom on svg element
>> wheel zoom doesn't work

Wheel zoom doesn't work on svg element. Note that dbClick is working on svg

Could you please advise? Everything is as described in original ticket.
