### ISSUE TITLE
I can not run the code for http://bl.ocks.org/mbostock/raw/1308257/

### ISSUE THREAD

**Issue by stevevaius** [mbostock/d3#2643]
I tried to run this chord diagram to test it but it failed due to can not find sources http://mbostock.github.io/d3/d3.layout.js?2.4.6 and http://mbostock.github.io/d3/d3.csv.js?2.4.6. Now, I dont know where to find these source files at least to run it locally? Any help?

**Comment by mbostock** [comment]
I’ve updated it to use V3:

http://bl.ocks.org/mbostock/1308257/46b4c63102ccab9cfa2a67c28a00962750bd3f2e

I thought I had already gone through all my gists to keep them up-to-date, but I missed some, so I’ll be going through them later today. Thanks for letting me know.

**Comment by stevevaius** [comment]
Thanks! Looking for updates ;)

**Comment by stevevaius** [comment]
P.S: I checked the code again and failed to run. On console: "var format = d3.format(",.3r");" part gave error on running so I changed the src to local "d3.min.js" and it worked.
