### ISSUE TITLE
How to use the d3.selectAll(...).each() method with ES6 arrow notation

### ISSUE THREAD

**Issue by wil93** [mbostock/d3#2644]
I had this code:

```javascript
var me = this;
...
d3.selectAll(".region").each(function(d) {
    d3.select(this).style("fill", me.compute_color(...));
})
```

With ES6, I can use the arrow notation to avoid overwriting `this`:

```javascript
d3.selectAll(".region").each(d => {
    d3.select(this).style("fill", this.compute_color(...));
})
```

However, this code doesn't work anymore because d3 is selecting the wrong element. In fact, I have lost the only reference to the element, because `this` was not overridden by d3.

How can I change `d3.select(this)` so that it works?

**Comment by mehmetavsar** [comment]
in lambda expressions, `this` context is preserved as parent function's this context. May this be the cause?

**Comment by mehmetavsar** [comment]
Two possibilities:
- d object may be holding a property that could be used as a reference (like DOM Object) or a selector string to itself

Or

```javascript
var mainSelection = d2.selectAll(".region");
mainSelection.each((d,i) => {
  mainSelection[i].style("fill"...  // Not sure if it's indexed.
});
```

**Comment by mbostock** [comment]
ES6 [arrow functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) lexically bind `this`, which prevents you from being able to access the `this` context of the selected node set by D3. There’s no way to fix this globally without abandoning the use of `this` as the selected node; some potential approaches are discussed in #2246.
