### ISSUE TITLE
window.d3 despite being loaded as an amd module?

### ISSUE THREAD

**Issue by mindspank** [mbostock/d3#2645]
```javascript
if (typeof define === "function" && define.amd) this.d3 = d3, define(d3)
```

We are using requirejs to load d3, however it seems that d3 has started to define itself in global scope now. Is there a reason I'm missing here?

We usually have multiple third party plugins running our software and many of them are using d3.
With 3.4.X of D3 we never noticed any issue but now we are getting clashes between d3 versions in global scope.

**Comment by mbostock** [comment]
Yes. See #1921.

**Comment by mbostock** [comment]
This has been the case since [3.4.10](https://github.com/mbostock/d3/releases/tag/v3.4.10).

**Comment by mindspank** [comment]
Ah ye, it was an odd edge case where we found it.

Module A loads D3js and shims in a sankey plugin.
Module B loads D3js and in the process overwrites the sankey plugin.
Module A tries to fire methods on the sankey plugin which has now been purged from window.d3

Cheers for the fast reply!
