### ISSUE TITLE
Force layout doesn't dispatch 'end' event on force.stop() call after 3.5.7

### ISSUE THREAD

**Issue by amalitsky** [mbostock/d3#2656]
Force layout doesn't dispatch "end" event on a `force.stop()` call, "start" event is dispatched instead. Most likely caused by de33875212f56845bac584d9441048e3c77c5ba9.

3.5.6 behavior: http://jsfiddle.net/amalitsky/wy1fm3ao/
3.5.7: http://jsfiddle.net/amalitsky/wy1fm3ao/3/
Click stop button while animation is in progress to call `force.stop()` explicitly. Double click on the svg resumes animation.

**Comment by mbostock** [comment]
Fixed in #2655, staged for 3.5.10.

**Comment by amalitsky** [comment]
Awesome, great thanks for super fast feedback on this issue and timely release.
