### ISSUE TITLE
d3.xml doesn't return an error on illegal XML

### ISSUE THREAD

**Issue by aubergene** [mbostock/d3#2659]
Will Watts at [last night's D3js London](http://www.meetup.com/London-d3js/events/226138191/) reported that `d3.xml` silently fails instead of returning an error when passed xml which uses an invalid namespace. I checked and can confirm the follow example will pass the callback `(null, null)`, instead of an error as the first param. 

```
<?xml version="1.0" encoding="UTF-8" ?>
<hello>
  <bad:world name="Earth"/>
</hello>
```

**Comment by mbostock** [comment]
Fixed this for 4.0 in [d3-request 0.2.2](https://github.com/d3/d3-request/releases/tag/v0.2.2).
