### ISSUE TITLE
foreignobject won't display in tree layout

### ISSUE THREAD

**Issue by zhangyin-github** [mbostock/d3#2660]
http://jsfiddle.net/v7rj7add/1/

nodeEnter.append("foreignobject").attr("x", 10).attr("y", -8).attr(
		"width", "130").attr("height", "30").append("xhtml:div").html(function(d) {
	return d.id;
});

I appended a foreignobject in each g element, but it won't show in firefox and chrome.
I've also tried append("xhtml:body").append("xhtml:div"), and even append("html").attr("xmlns", "http://www.w3.org/1999/xhtml"), but failed too.

But, if I inspect the g element, appending several blank lines after the foreignobject using the "edit as HTML" function, then the text will be shown.

Is this an D3 bug or a browser bug?

Before editing foreignobject in the inspector
![qq 20151128211045](https://cloud.githubusercontent.com/assets/6156866/11452055/a598576a-9614-11e5-8504-3b1b694b6636.png)

Editing the foreignobject tag in the inspector, appending several blank lines.
![qq 20151128211112](https://cloud.githubusercontent.com/assets/6156866/11452056/a9fc86fa-9614-11e5-855e-a5160e6fdf04.png)

Then it shows up!
![qq 20151128211122](https://cloud.githubusercontent.com/assets/6156866/11452057/ac0c2c2a-9614-11e5-9f4c-63909a32612d.png)

Running D3 3.5.9 on FF 42 and Chrome 46. All have the same problem.

**Comment by mbostock** [comment]
It’s spelled `foreignObject` with a capital O, not `foreignobject`. Yes, SVG is case-sensitive even though HTML5 is not.
