### ISSUE TITLE
Is there any plan to create an official Angular.js Wrapper of D3.js?

### ISSUE THREAD

**Issue by feniixx** [mbostock/d3#2661]

**Comment by BeAce** [comment]
Hey,
I am a Chinese student and I'm a trainee in a company in China.My boss tell me the D3.However, I know Angularjs, but I don't know how to use it for real development.
Sorrry about that.Maybe I have a long way to go.I have to spend a lot of time to make it.

2015-12-01 

18817834467 



发件人："Jonathan S." <notifications@github.com>
发送时间：2015-12-01 17:45
主题：[d3] Is there any plan to create an official Angular.js (#2661)
收件人："mbostock/d3"<d3@noreply.github.com>
抄送：

**Comment by feniixx** [comment]
WTF? @BeAce What has your comment to do with this question?

**Comment by mbostock** [comment]
There is no plan to provide an “official” Angular.js wrapper, no. D3 is designed to work with any number of frameworks. A search for [\[d3 angular\]](https://www.google.com/search?q=d3+angular) on Google provides a number of related resources including the [angular-nvd3 library](https://krispo.github.io/angular-nvd3/) and a detailed blog post, [Replacing (most of) d3.js with pure SVG + AngularJS](http://alexandros.resin.io/angular-d3-svg/). I suspect that with D3 4.0, which breaks D3 into [many decoupled modules](https://github.com/d3) (see #2461), it will be even easier to pick and choose the parts of D3 you want to use with another DOM framework such as Angular.

**Comment by feniixx** [comment]
Oh ok! thanks!
