### ISSUE TITLE
Mouseleave doesn't work after moving an element

### ISSUE THREAD

**Issue by sprkweb** [mbostock/d3#2671]
Example: http://codepen.io/anon/pen/bEdENP
You can see that class doesn't disappear when your mouse cursor leave a rectangle. You will see that the listener is not called if you will open Firebug.
I think it's bug of D3 because I have a working example with jQuery: http://codepen.io/anon/pen/vLOLyV

**Comment by mbostock** [comment]
D3 is simply exposing the browser’s native events here, so this is a bug in Firefox’s mouseleave and mouseenter implementation. Please file a bug with [Bugzilla](https://bugzilla.mozilla.org/) (if there isn’t one already). Here’s your example with vanilla JS:

http://codepen.io/anon/pen/GoJjdb

Note that mouseover and mouseout events seem to work fine.

D3 is not a compatibility layer; we typically do not include workarounds for browser bugs.
