### ISSUE TITLE
Support for "Accel" virtual modifier in `d3.event`

### ISSUE THREAD

**Issue by SylvainCorlay** [mbostock/d3#2672]
It would be very useful if `d3.event` exposed a shim for the "Accel" virtual modifier in the same way it exposes `shiftKey`, `altKey`, `metaKey`, and `crtlKey`,  i.e. with a `d3.event.accelKey` boolean.

The `Accel` virtual modifiers corresponds to `Ctrl` on Windows and `Cmd` on OS X.

It should be accessible via `d3.event.getModifierState("Accel")` but is not yet supported everywhere.

**Comment by mbostock** [comment]
D3 is not a compatibility layer: the modifiers (shiftKey, altKey, metaKey, and crtlKey) are not “exposed” by D3 except in the sense that your browser provides them natively on key events. So, if you want an `accelKey` modifier, you should implement it outside of D3.

**Comment by SylvainCorlay** [comment]
Fair enough. Thanks for the reply.
