### ISSUE TITLE
Force-directed layout: Slow initial chart stabilization after v3.5.4

### ISSUE THREAD

**Issue by richww** [mbostock/d3#2673]
Hello,

It appears that d3.js version 3.5.4 introduced a change which is causing force-directed layouts to initially stabilize much slower than before. Is this perhaps due to the release note on v3.5.4 "Improve initial random positioning of nodes for force layouts."? 

I took the existing "Mobile Patent Suits" demo page (http://bl.ocks.org/mbostock/1153292) and modified it by adding 500 nodes to highlight the initial stabilization difference (see images below).

In both examples below, I stopped the layout prematurely at 0.6 alpha to show how far the layout has stabilized. 

![d3js 3 5 3_stopped](https://cloud.githubusercontent.com/assets/4081683/11698910/2ba270f0-9eb9-11e5-8a3f-be02ee93c7ce.png)

v3.5.3 is already very stable even at 0.6 alpha. 

![d3js 3 5 4_stopped](https://cloud.githubusercontent.com/assets/4081683/11698908/29beeca0-9eb9-11e5-961e-1fe583f6f064.png)

In v3.5.4, many nodes are still far out of range from center gravity.  

From what I've tested in my own application, the chart is not only wildly bouncing around (more than in v3.5.3), but it overall takes a little longer to fully stabilize. This problem is essentially a blocker for us to upgrade past v3.5.3 due to the performance hit. The delay in getting to enough stabilization resembling a useful network is especially problematic for my application because we attempt to "Pause" the animation at certain alpha states, which now seem to be on a different scale (especially between .9 to .1) relative to v3.5.3.

*I will add that another force-directed layout sample page does not appear to have this problem when I similarly add 500 nodes to the graph (http://mbostock.github.io/d3/talk/20111116/force-collapsible.html). I know that the Mobile Suits demo uses paths instead of lines to connect the nodes, and also has arrow head markers, but I've taken these out and they don't appear to fix the issue.*

**Comment by mbostock** [comment]
I am planning on tackling this with the rewrite of the force layout for 4.0; related d3/d3-force#3.

**Comment by mbostock** [comment]
This has been fixed in 4.0’s [d3-force](https://github.com/d3/d3-force) thanks to the new, more stable velocity Verlet integration. See this example:

http://bl.ocks.org/mbostock/9a6d25c14e7bc5dc53de8215fc280669

Before at tick 5:

![frame-0005](https://cloud.githubusercontent.com/assets/230541/14803644/70736252-0b10-11e6-89a6-19f408b07832.png)

After at tick 5:

![frame-0005](https://cloud.githubusercontent.com/assets/230541/14803647/77d6883a-0b10-11e6-9ed4-362f601da4b9.png)
