### ISSUE TITLE
chord layout group sums

### ISSUE THREAD

**Issue by hndgzkn** [mbostock/d3#2678]
Hi, 

For chord layout, API reference states that chord.groups().value returns "the sum of the associated row i, a number.". In the implementation the value is calculated as "(x - x0) / k". When padding is 0, the calculated value is correct. However when padding is different than 0, this value is slightly different than actual sum. I wonder why you did not use groupSums array to get the row sum?

Best,
Hande

**Comment by mbostock** [comment]
Fixed in #2675. Will be in 3.5.11.
