### ISSUE TITLE
Time scale format shows weekday abbreviation except for Sunday

### ISSUE THREAD

**Issue by sbj42** [mbostock/d3#2680]
The format for a default time scale chooses from multiple formats based on values present in the Dates given.  For the first of each month it produces the complete month name.  For other days it sometimes chooses to use the weekday/date format "%a %d", and sometimes the month/date format "%b %d".  It bases that choice on whether it's Sunday.  This seems strange to me, because I get axes that look like this:

October, Fri 02, Sat 03, Oct 04, Mon 05, ...

It seems to be lines 139-140 of time/scale.js:

```.javascript
  ["%a %d", function(d) { return d.getDay() && d.getDate() != 1; }],
  ["%b %d", function(d) { return d.getDate() != 1; }],
```

`getDay` is 0 for Sunday.

To reproduce, run the following:
```.javascript
var f = d3.time.scale().tickFormat();
f(new Date("2015/10/01")) // -> "October"
f(new Date("2015/10/02")) // -> "Fri 02"
f(new Date("2015/10/03")) // -> "Sat 03"
f(new Date("2015/10/04")) // -> "Oct 04"
```

For myself, I'd want either the weekday formatting or the month formatting, but I don't know why anyone would want both in the same chart.

**Comment by mbostock** [comment]
See [*time*.tickFormat](https://github.com/d3/d3-scale#time_tickFormat) for the justification. If you want a different behavior, you’re welcome to roll your own implementation to [*axis*.tickFormat](https://github.com/mbostock/d3/wiki/SVG-Axes#tickFormat), possibly basing it off the existing one.

**Comment by sbj42** [comment]
I understand, and agree with the documentations characterization as "somewhat unusual".
