### ISSUE TITLE
d3.json request text/html, not application/json

### ISSUE THREAD

**Issue by vanboom** [mbostock/d3#2683]
I am making a request using d3.json
```javascript
 d3.json(url, function(error,json){console.debug(json);});
```
The GET request is hitting my server with the format set to `text/html` instead of `application/json` like the documentation suggests. 

If I add `?format=json' to the url, then I get the appropriate JSON back. 

I am just now starting to use d3 - amazing capability - thank you!

**Comment by mbostock** [comment]
I am unable to reproduce this error. I see it setting the request accept header as “application/json”:

![screen shot 2015-12-15 at 10 07 01 am](https://cloud.githubusercontent.com/assets/230541/11819235/9d74765c-a313-11e5-950e-ddaafcd555ee.png)

The mime type is set in [src/xhr/json.js](https://github.com/mbostock/d3/blob/master/src/xhr/json.js#L4), which then becomes the accept header and overrideMimeType in [src/xhr/xhr.js](https://github.com/mbostock/d3/blob/master/src/xhr/xhr.js#L95).
