### ISSUE TITLE
Have data functions return promises when no callback specified

### ISSUE THREAD

**Issue by aendrew** [mbostock/d3#2684]
Howdy!

As we move ever-closer to the shiny-happy ES2015 future, I was wondering whether there's any interest in having the data functions return promises somehow. My initial thought is to leave them function as per normal when a callback is specified, but otherwise return a ES6 promise. This would allow for some really cool programming patterns using the new ES7 async/await syntax, and allow intelligent loading of multiple datasets without resorting to something like `d3.queue`. Consider how straight-forward and just generally _nice_ this looks:

```js
let data1 = await d3.json('./data/myData.json');
d3.selectAll('.things').data(data1).enter().append('circle'); // or whatever — jump straight to the fun part!
```

Compare that to the normal syntax:
```js
d3.json('./data/myData.json', function(err, data) {
  d3.selectAll('.things').data(data1).enter().append('circle'); // Not bad but still verbose.
});
```

Or worse, the current way of implementing a promise in ES2015:
```js
let p1 = new Promise((res, rej) => {
  d3.json('./data/myData.json', function(err, data) {
    err ? rej(err) : res(data);
  });
});

p1.then((data1) => {
  d3.selectAll('.things').data(data1).enter().append('circle'); // Good lord, what a mess.
});
```

I know that D3 has [generally opted to stay in ES5 land](https://github.com/mbostock/d3/issues/2220) for the moment (save for module loading), but is this something that's being considered? Would happily write a PR if so!

**Comment by mbostock** [comment]
I copied your comment to d3/d3-request#1 and will respond over there.
