### ISSUE TITLE
D3 data functions only

### ISSUE THREAD

**Issue by missingdays** [mbostock/d3#2692]
Hello!
I'm sorry if this question was already answered, I couldn't find it anywhere.
Is there any way to build d3 without all its SVG, DOM and all other "browser" methods, leaving only scale, math, color, arrays and all other "data" methods?
Why do I need this? E.g. for building charts in THREE.js, fabric.js  or any other render library that doesn't have all this awesome data methods. And I care about the size of the application and libraries overall, so I wouldn't like to have svg utilities when I don't need them.
Thanks!

**Comment by mbostock** [comment]
Please see https://github.com/d3 for the new small modules that will be the basis of D3 4.0. Also read [Let’s Make a (D3) Plugin](http://bost.ocks.org/mike/d3-plugin/) and #2461 for some additional detail. For the ones you specifically mentioned:

* https://github.com/d3/d3-array
* https://github.com/d3/d3-color
* https://github.com/d3/d3-scale

The development of the new modules is ongoing, so there aren’t new modules for everything yet (such as hierarchical and force layouts).

**Comment by missingdays** [comment]
Okay, thank you very much!
