### ISSUE TITLE
bower - missing d3/d3.min when installing

### ISSUE THREAD

**Issue by dragosrususv** [mbostock/d3#2705]
Bower version: 1.7.2
D3 version used in bower.json:  "d3": "~3.5.6"

Is this intended?
As a small notice, this happened today locally and I have this bower configuration for 6 months now.

![d3](https://cloud.githubusercontent.com/assets/5492820/12218373/e4aef65c-b725-11e5-9518-8b2894346645.png)

**Comment by mbostock** [comment]
I’m not able to reproduce. Both `bower install d3` (3.5.12) and `bower install d3#3.5.6` installed d3.js and d3.min.js into bower_components/d3.

**Comment by dragosrususv** [comment]
@mbostock : I'm on Win7.
I initially just removed bower_components and fetched again and same problem.

Finally removed contents of C:\Users\User\AppData\Local\bower\, tried it again and it works.\
Could be some bower caching bug on Win machines.

Thanks for taking a look.

**Comment by mbostock** [comment]
Ya, sounds like your cache got borked. Glad you were able to fix it!
