### ISSUE TITLE
Visual Index is not showing third and fourth columns

### ISSUE THREAD

**Issue by mitchsumma** [mbostock/d3#2713]
Seems to be an issue for me on all browsers.

**Comment by mbostock** [comment]
Seems okay to me… ¯\_(ツ)_/¯

![screen shot 2016-01-20 at 9 40 43 am](https://cloud.githubusercontent.com/assets/230541/12457547/e5756d0a-bf59-11e5-9a55-0c8550f8fdcc.png)

The wiki is publicly-editable and maintained by the community, so it’s quite possible that someone edited the gallery and borked the style. Also, sometimes GitHub changes the appearance of the wiki and that causes breakages, too. I may eventually move the gallery to a dedicated web application that does a better job displaying and organizing the examples, but for now, it’s held together with duct tape and markdown.

**Comment by mitchsumma** [comment]
This is what I am seeing. I see the four columns for a few seconds, then
they disappear. Here I am on IE and Firefox:

[image: Inline image 4][image: Inline image 3]



On Wed, Jan 20, 2016 at 12:45 PM, Mike Bostock <notifications@github.com>
wrote:

> Seems okay to me… ¯_(ツ)_/¯
>
> [image: screen shot 2016-01-20 at 9 40 43 am]
> <https://cloud.githubusercontent.com/assets/230541/12457547/e5756d0a-bf59-11e5-9a55-0c8550f8fdcc.png>
>
> The wiki is publicly-editable and maintained by the community, so it’s
> quite possible that someone edited the gallery and borked the style. Also,
> sometimes GitHub changes the appearance of the wiki and that causes
> breakages, too. I may eventually move the gallery to a dedicated web
> application that does a better job displaying and organizing the examples,
> but for now, it’s held together with duct tape and markdown.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mbostock/d3/issues/2713#issuecomment-173299791>.
>



-- 
Mitch Goldstein
Senior Technical Consultant | Summa <http://www.summa-tech.com>
724-261-1132
mitch@summa-tech.com  <mitch@summa-tech.com>

**Comment by mbostock** [comment]
You can only attach images using the web interface, not by replying to an issue via email.

**Comment by mitchsumma** [comment]
Will do.

-Mitch

On Thu, Jan 21, 2016 at 10:15 AM, Mike Bostock <notifications@github.com>
wrote:

> You can only attach images using the web interface, not by replying to an
> issue via email.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mbostock/d3/issues/2713#issuecomment-173601720>.
>



-- 
Mitch Goldstein
Senior Technical Consultant | Summa <http://www.summa-tech.com>
724-261-1132
mitch@summa-tech.com  <mitch@summa-tech.com>
