### ISSUE TITLE
D3 opacity transition erases dotted lines/makes path invisible

### ISSUE THREAD

**Issue by raffe90** [mbostock/d3#2724]
I am trying to achieve a transition upon a colored via clipping chart (http://bl.ocks.org/mbostock/4062844) that has its path "above" dotted.

Once I try to do a click event to take the path above to opacity 0 it dissapears and there is no way of bringing it back, leaving only the path "below".

Example: https://youtu.be/MsAcJQgVR3k

Code:

```
d3.selectAll(".tag"+d.key.replace(/\s+/g, ''))
  .transition().duration(500)
  .style("opacity", newOpacity);

```
SO: http://stackoverflow.com/questions/34969051/d3-opacity-transition-erases-dotted-lines-makes-path-invisible

**Comment by mbostock** [comment]
Works for me.

http://bl.ocks.org/mbostock/b6c18261ef23b688f88f

**Comment by raffe90** [comment]
I have gotten it to work with one, but it seems that once I make it multiseries it breaks. That's why I post it here. 

Maybe (most likely) I'm doing something wrong, but it just seemed strange that I could make it work with one and once I made it multiseries it would behave erratically.

Moreover, I've been testing for the past week in different browsers/OS systems and the results are all over the place.

**Comment by mbostock** [comment]
Unfortunately I don’t have time to investigate this further (especially without any code that demonstrates the problem). It’s certainly possible there’s a browser rendering bug related to the clipping mask, but this doesn’t sound like a D3 bug in any case.

**Comment by raffe90** [comment]
I've done several versions, but just in case you do find the time (and maybe something does pop up) I will paste the last implementation (at least the important part)

```
    // Loop through each symbol / key
    dataNest.forEach(function(d,i) {
        svg.append("clipPath")
              .attr("id", "clip-above")
            .append("rect")
              .attr("width", width)
              .attr("height", function(){
                console.log(th(d.key), d.key);
                return y(th(d.key));
              });

          svg.append("clipPath")
              .attr("id", "clip-below")
            .append("rect")
              .attr("y", y(th(d.key)))
              .attr("width", width)
              .attr("height", height - y(th(d.key)));

          var clip = ["below", "above"];

          clip.forEach(function(v,i){
            svg.append("path")
              .attr("class", function() { return 'tag'+d.key.replace(/\s+/g, '') + " line " + v; })
              .attr("clip-path", function() { return "url(#clip-" + v + ")"; })
              // .attr("id", 'tag'+d.key.replace(/\s+/g, ''))
              .attr("d", line(d.values))
              .style('fill', 'none')
              .style("stroke", function() { // Add the colours dynamically
                  return color(d.key);
              });
          });
}
```

If you can find what's wrong that would be great, if not thanks anyways and I appreciate you taking the time

**Comment by mbostock** [comment]
Yeah, so if dataNest has multiple elements, you are creating multiple clipPaths with the same id (`clip-above` or `clip-below`). Unfortunately, you need to give them globally unique IDs on the page, due to the design of SVG. If they’re the same across the lines then you could just create them once and share them, though.

**Comment by raffe90** [comment]
You're totally right. I don't know how I missed that for so long... 

Just changed it and is working perfectly now.
