### ISSUE TITLE
d3.transpose() applied on loud matrices. call stack exception thrown.

### ISSUE THREAD

**Issue by secnodev** [mbostock/d3#2728]
First, thanks to all for your great and usefull job.
We noticed an exception from d3.transpose(m) when m is a loud matrix.

[bug_transpose_test.zip](https://github.com/mbostock/d3/files/112205/bug_transpose_test.zip)

Tested on chrome 48.0.2564.97 with d3 versions : 3.5.14 and 3.4.9.

Test code :
`
	var data1 = [1,2,3,4,5];
	var data = [];
	for(var i = 0; i<130000; i++)
	{
		data.push(data1);
	}
	var transposed = d3.transpose(data);
`

**Comment by mbostock** [comment]
This has already been fixed in [d3-array](https://github.com/d3/d3-array), but I can back-port the fix.
