### ISSUE TITLE
Issue with minification of D3 library

### ISSUE THREAD

**Issue by josheigel** [mbostock/d3#2731]
I tried minifying D3 and kept getting an error. I may be doing something wrong, but I used bower to install the latest version of D3 (which at the time was 3.5.10) and the when I minified the files using uglify, the same problem kept coming up.

I am probably totally out of my depth, but I changed a few places in the library and everything seemed to work with minifying the files, so I just thought I'd let you know the places within the main d3.js file since you have the repository broken up into modules.

**On line 1136**
`var name = ".dragsuppress-" + `**`++d3_event_dragId`**`, click = "click" + name, w = d3.select(d3_window(node)).on("touchmove" + name, d3_eventPreventDefault).on("dragstart" + name, d3_eventPreventDefault).on("selectstart" + name, d3_eventPreventDefault);`
**Added the parenthesis `(++d3_event_dragId)`**

---

**On line 7617**
`return type in d3_scale_linearFormatSignificant ? Math.abs(p - d3_scale_linearPrecision(Math.max(abs(range[0]), abs(range[1])))) + `**`+(type !== "e")`**` : p - (type === "%") * 2;`
**Added the parenthesis `(+(type !== "e"))`**

---
**On line 7975**
`var r0 = Math.max(0, `**`+innerRadius.apply(this, arguments)`**`), r1 = Math.max(0, `**`+outerRadius.apply(this, arguments)`**`), a0 = startAngle.apply(this, arguments) - halfπ, a1 = endAngle.apply(this, arguments) - halfπ, da = Math.abs(a1 - a0), cw = a0 > a1 ? 0 : 1;`
**Added the parenthesis `(+innerRadius.apply(this, arguments))...(+outerRadius.apply(this, arguments))`**

---

**On line 8091**
`var r = (+innerRadius.apply(this, arguments) + `**`+outerRadius.apply(this, arguments))`**` / 2, a = (+startAngle.apply(this, arguments) + `**`+endAngle.apply(this, arguments)`**`) / 2 - halfπ;`
**Added the parenthesis `(+outerRadius.apply(this, arguments))...(+endAngle.apply(this, arguments))`**

---

**On line 8493**
`function arc(r, p, a) {
  return "A" + r + "," + r + " 0 " + `**`+(a > π)`**` + ",1 " + p;
}`
**Added the parenthesis ` (+(a > π))`**

Again, I may be doing something wrong, but I couldn't figure out what, so I just wanted to get your advice and opinion. Thanks in advance and thanks for all the hard work putting this library out there!

**Comment by mbostock** [comment]
Hi @josheigel. These aren’t bugs in D3—these are bugs in your minifier, which appears to not observe JavaScript’s operator precedence correctly. Perhaps you’re using an old version of [UglifyJS2](http://lisperator.net/uglifyjs/)?

**Comment by josheigel** [comment]
Ok, that definitely could be. I'll double check it and adjust. Thanks for the response!
