### ISSUE TITLE
IE errors when setting up drag behavior on <use> elements

### ISSUE THREAD

**Issue by alpeshgaglani** [mbostock/d3#2735]
Hi,
We recently switched to employing <use> elements instead of groups for a variety of reasons. While this works fine on Chrome, IE breaks with the error: "Invalid operand to 'in': Object expected". This occurs in the d3_vendor_symbol function when trying to access "style" property of the node. Apparently, IE does not have the style property for use elements. 
I have setup a JS fiddle here: https://jsfiddle.net/dropship/53wuj1et/9/ to demonstrate the issue.
Is there a workaround, or something that can be fixed?
Thanks.

**Comment by mbostock** [comment]
There’s a fix in #2548. Unfortunately, I haven’t had time to merge it into a release yet.

**Comment by mbostock** [comment]
Fixed in 3.5.15.

**Comment by alpeshgaglani** [comment]
Thanks a lot! You've saved us several hours of re-work :)
