### ISSUE TITLE
i want to draw a graph with change  colors transparency, how to make it

### ISSUE THREAD

**Issue by lener1987** [mbostock/d3#2751]
I want this:
![ea81dw _k4ebs s_qf9_yiy](https://cloud.githubusercontent.com/assets/17535734/13383361/4c5814e0-dec3-11e5-8666-c333f2b421e8.jpg)

this is now:
![9qsg c30k oemb0w r31g0](https://cloud.githubusercontent.com/assets/17535734/13383450/edf393d2-dec4-11e5-9d44-a03ceae04173.jpg)

**Comment by mbostock** [comment]
Please try StackOverflow if you want help.
