### ISSUE TITLE
Two links broken

### ISSUE THREAD

**Issue by samlhumphrys** [mbostock/d3#2754]
Below two links under Introductions & Core Concepts are broken. 

learning D3.js(2)(Chinese) - jtyjty99999
learning D3.js(1)(Chinese) - jtyjty99999

**Comment by mbostock** [comment]
The wiki is publicly-editable, so feel free to delete broken links if you find them. I’ve gone ahead and done that for these two. Thank you.

**Comment by samlhumphrys** [comment]
Tks. I am familiar with Wikipedia, but i am pretty new to github. I did try to edit the page, but it kept returning 404 and I was not sure why (authority or something?) that's why i posted the request here...
