### ISSUE TITLE
Week of the year miscalculation?

### ISSUE THREAD

**Issue by kaiseroskilo** [mbostock/d3#2756]
Hello,

I'm using D3 version 3.5.16 and noticed that this:

`d3.time.format("%W/%Y")(new` Date(d3.time.format("%W/%Y").parse("53/2015")))

which should yield 53/2015 actually returns 01/2016. I don't think it is intended and even if it was it should be 00/2016 (since 00 is equivalent to the last week number of the previous year if I'm correct).

**Comment by mbostock** [comment]
%W defines 01/2016 as the first Monday in 2016. Per the [documentation](https://github.com/mbostock/d3/wiki/Time-Formatting#format):

> For `%W`, all days in a new year preceding the first Monday are considered to be in week 0.

Thus, the date 00/2016 is defined as the Monday *before* the first Monday in 2016 (January 4, 2016), which is by definition the last Monday of 2015 (December 28, 2015).

```js
d3.timeParse("%W/%Y")("00/2016"); // Mon Dec 28 2015 00:00:00 GMT-0800 (PST)
```

(I’m using the new [d3-time-format](https://github.com/d3/d3-time-format) API from 4.0, but it’s equivalent to d3.time.format in 3.x.) Note that it’s still possible to *format* the %W as 00/2016 given a date in 2016, provided that date is after or equal to January 1 but before January 4:

```js
d3.timeFormat("%W/%Y")(new Date(2016, 0, 1)); // 00/2016
```

Similarly, 53/2015 is defined as the 53rd Monday in 2015, which by definition is the first Monday in 2016, and thus equivalent to 01/2016.

```js
d3.timeParse("%W/%Y")("52/2015"); // Mon Dec 28 2015 00:00:00 GMT-0800 (PST)
d3.timeParse("%W/%Y")("53/2015"); // Mon Jan 04 2016 00:00:00 GMT-0800 (PST)
```

So, to take apart your example:

```js
var parseDate = d3.timeParse("%W/%Y"),
    formatDate = d3.timeFormat("%W/%Y");

var date = parseDate("53/2015"); // Mon Jan 04 2016 00:00:00 GMT-0800 (PST)
format(date); // 01/2016
```

You were also passing the parsed date to the Date constructor, like this:

```js
format(new Date(date)); // 01/2016
```

That’s redundant, but it shouldn’t have any effect.
