### ISSUE TITLE
Week number unconsistency

### ISSUE THREAD

**Issue by mhebrard** [mbostock/d3#2762]
Hello, 
I try d3.time.format for calculation of the week number...
I see some miscalculation between d3, and my calendar (week number track on google calendar)
Lets start the week on Monday (d3 %W)

Sun. 01/04/2015, ggl=01, d3=00
Mon. 01/05/2015, ggl=02, d3=01
Sun. 12/27/2015, ggl=52, d3=51
Mon. 12/28/2015, ggl=53, d3=52
Sun. 01/03/2016, ggl=53, d3=00
Mon. 01/04/2016, ggl=01, d3=01

According to [http://www.epochconverter.com/weeks/2015](this website), the google track follow the ISO-8601. 
I find a JS script that calculate the good number

// Source: http://weeknumber.net/how-to/javascript
`
function getWeek(date) { 
		var d = new Date(date);
		d.setHours(0, 0, 0, 0);
		d.setDate(d.getDate() + 3 - (d.getDay() + 6) % 7);
		var week1 = new Date(d.getFullYear(), 0, 4);
		return 1 + Math.round(((d.getTime() - week1.getTime()) / 86400000
            - 3 + (week1.getDay() + 6) % 7) / 7);
	}`

Hope it will help to fix the problem

**Comment by mbostock** [comment]
The `%W` directive defines a week number that is different from ISO 8601. ISO 8601 defines the first week as the week that contains the year’s first Thursday. Per the [API reference](https://github.com/d3/d3-time-format#locale_format), D3 defines the week number as:

> For `%W`, all days in a new year preceding the first Monday are considered to be in week 0.
