### ISSUE TITLE
Using d3.format("%") automatically rounds number

### ISSUE THREAD

**Issue by zhoux10** [mbostock/d3#2764]
Since entering d3.format(".0%") should round the number, why would d3.format("%") also automatically round the number? 

This prevents user from getting the full number in percentage form (They could always specify certain number of decimal places, but if the number has less decimals, it'll get padded with 0's, which is not always desirable)

For example, for the number 0.1234, in order to get 12.34%, the user has to specify d3.format(".2%"). Issues with this:

1) The user doesn't always know how many decimal places the number has
2) This format cannot be universally used against numbers with different decimal places (eg: 0.234, which should format to 23.4%, not 23.40%)

**Comment by zhoux10** [comment]
I'm going to take a stab at fixing this issue tonight unless otherwise notified

**Comment by mbostock** [comment]
This code has been rewritten for D3 4.0. I’d take a look at
https://github.com/d3/d3-time-format first.

**Comment by mbostock** [comment]
This code has been rewritten for D3 4.0. I’d take a look at [d3-format](https://github.com/d3/d3-format) first before starting new work in the D3 3.x codebase.

In 4.0, the precision is [defined as follows](https://github.com/d3/d3-format#locale_format):

> Depending on the *type*, the *precision* either indicates the number of digits that follow the decimal point (types `f` and `%`), or the number of significant digits (types `​`, `e`, `g`, `r`, `s` and `p`). If the precision is not specified, it defaults to 6 for all types except `​` (none), which defaults to 12. Precision is ignored for integer formats (types `b`, `o`, `d`, `x`, `X` and `c`). See precisionFixed and precisionRound for help picking an appropriate precision.

So in D3 4.0, `%` is equivalent to `.6%`:

```js
d3.format("%")(0.1234); // "12.340000%"
d3.format(".6%")(0.1234); // "12.340000%"
```

Thus, the `%` is like the `g` command, except it multiplies by 100 and appends a percent sign:

```js
d3.format("g")(0.1234); // "0.123400"
d3.format(".6g")(0.1234); // "0.123400"
```

It looks like the D3 3.x the precision ends up being NaN if it’s not specified, so it ends up doing something like this:

```js
(0.1234 * 100).toFixed(NaN) + "%"; // "12%"
```
