### ISSUE TITLE
Support for ES6-style import/export?

### ISSUE THREAD

**Issue by hanfeisun** [mbostock/d3#2777]
When I use `lodash` with Webpack, I could import only one function from it

`import clone from 'lodash/clone'`

By this way, only the source code of  `clone` function instead of the whole `lodash` library will be packed into the final bundle, which will reduce the file size of the packed file.

Sometimes, I  use only the `scale` functions in `d3` but not the other DOM-related function. Would there be a way to only import specific functions for d3?  In other words, will d3 support the ES6-style import/export like what lodash did?

**Comment by hanfeisun** [comment]
This may be related to https://github.com/mbostock/d3/issues/2461

**Comment by mbostock** [comment]
This is one of the primary goals of D3 4.0. See:

https://medium.com/@mbostock/let-s-make-a-d3-plugin-c8e697599f48#.n2fd39ous
https://github.com/mbostock/d3/tree/4
https://github.com/d3

D3 4.0 is built entirely using ES6 modules (import and export), using Rollup to produce a UMD bundle per repository. Thus you can use a variety of methods to pick and chose which code you want to use, either at the repository level (using concatentation, Webpack, Browserify, etc.) or at the individual symbol level (when using Rollup).

**Comment by SandHilt** [comment]
![image](https://user-images.githubusercontent.com/6170125/32621696-c780223e-c567-11e7-97e6-f197592d5f6b.png)
Apparently is not working on vanilla JavaScript in Chrome 62.0.3202.89 x64.

**Comment by mbostock** [comment]
@SandHilt You are trying to import the [generated UMD bundle d3.js](https://unpkg.com/d3@4/build/d3.js) as an ES module; you need to import the [ES module index.js](https://unpkg.com/d3@4/index.js) instead. However, if you are using ES modules, I recommend importing from the D3 submodule directly, such as [d3-selection’s index.js](https://unpkg.com/d3-selection@1/index.js). Please see my instructions on [asking for help](https://gist.github.com/mbostock/7f063e44c57ecb5828dd5643e61f92d3) rather than using GitHub issues.

**Comment by SandHilt** [comment]
Nice try.
But vanilla don't resolve paths like Webpack.
![image](https://user-images.githubusercontent.com/6170125/32623975-089558b4-c56f-11e7-81c8-07188a56e6c5.png)

**Comment by Ledragon** [comment]
If you post your question on StackOverflow with a link to a repo, I can try and help you. Working with d3 and Webpack works like a charm on my side

**Comment by SandHilt** [comment]
look my question [here](https://stackoverflow.com/questions/47331913/how-import-with-ecmascript-vanilla-javascript-with-modules-es6).
