### ISSUE TITLE
Examples' license

### ISSUE THREAD

**Issue by yay** [mbostock/d3#2779]
What would it mean to use your examples which are GPL in a closed source or MIT licensed app? Would you consider using dual licensing, say adding MIT/BSD as an option?

For example:
https://bl.ocks.org/mbostock/1345853

**Comment by mbostock** [comment]
The examples are GPL-licensed, so you are not allowed to use them in a closed-source or non-GPL-compatible application; you must release your code with a GPL-compatible license.

**Comment by yay** [comment]
OK, thank you for your reply.

**Comment by pkra** [comment]
@mbostock are the examples at https://observablehq.com/@d3/gallery GPL licensed, too? (Sorry if I missed something - I looked at the gallery, the org and individual items but couldn't find a license notice.)

**Comment by curran** [comment]
Related thread on licensing in Observable: https://talk.observablehq.com/t/license-for-code-submitting-on-github/1370/5

**Comment by pkra** [comment]
Thanks for the link, @curran, that's helpful. 

I could resolve my particular "problem" by finding an older version among @mbostock's blocks (with an explicit GPL license). I guess it would be nice if the official d3 examples had a license notice but I understand if it's not feasible (at this time or in general).

**Comment by Fil** [comment]
In the case when the license is missing and you really need it clarified, you are always welcome to ask the author(s) directly.
