### ISSUE TITLE
Chrome donut chart animation bug; transitions behave unexpectedly

### ISSUE THREAD

**Issue by kwhitaker** [mbostock/d3#2780]
In chrome, the code below has started causing an odd transition behavior in my pie chart when the data is updated.  I've attached an image to illustrate the issue.  This only started happening recently, and other browsers (Safari, IE10+) don't exhibit the behavior; the transitions behave just like they do in the example: https://bl.ocks.org/mbostock/1346395

![chrome-animation](https://cloud.githubusercontent.com/assets/108933/14151866/a9746aba-f675-11e5-8794-9ef6c5f838a6.gif)

The code below was generated from coffeescript. I can provide the original CS if requested

```js
({
  renderChart: function() {
    var color, height, radius, svg, width;
    width = this.ui.chartWrap.width();
    height = this.ui.chartWrap.height();
    radius = Math.min(width, height) / 2;
    color = d3.scale.category20();
    if (_.every(this.data, function(type) {
      return !type.count;
    })) {
      return false;
    }
    this.pie = d3.layout.pie().value(function(d) {
      return d.count;
    }).sort(null);
    this.arc = d3.svg.arc().innerRadius(.5 * radius).outerRadius(radius);
    svg = d3.select('#dups-chart').append('svg').attr('width', width).attr('height', height).append('g').attr('transform', "translate(" + (width / 2) + "," + (height / 2) + ")");
    this.path = svg.selectAll('path').data(this.pie(this.data)).enter().append('path').attr('d', this.arc).attr('class', (function(_this) {
      return function(d, i) {
        return _this.data[i]["class"];
      };
    })(this)).attr('data-type', (function(_this) {
      return function(d, i) {
        return _this.data[i].value;
      };
    })(this)).each(function(d) {
      this._current = d;
    });
    return this.updateChart();
  },
  updateChart: function() {
    var arcTween, hasData, view;
    view = this;
    arcTween = function(a) {
      var i;
      i = d3.interpolate(this._current, a);
      this._current = i(0);
      return function(t) {
        return view.arc(i(t));
      };
    };
    hasData = _.any(this.data, function(d) {
      return d.count > 0;
    });
    if (hasData) {
      this.ui.chartWrap.find('svg').show();
      this.pie.value(function(d) {
        return d.count;
      });
      this.path = this.path.data(this.pie(this.data));
      return this.path.transition().duration(750).attrTween("d", arcTween);
    } else {
      return this.ui.chartWrap.find('svg').hide();
    }
  }
});
```

**Comment by mbostock** [comment]
> the transitions behave just like they do in the example

Sorry, are you saying that this example is broken too? I don’t see any problem.

https://bl.ocks.org/mbostock/1346410

Or are you saying that your code is only broken on Chrome?

**Comment by mbostock** [comment]
In any case, I’m not able to do any further investigation without a running example that demonstrates the problem. Can you please reduce it to something that runs on bl.ocks.org (or, if you prefer, JSFiddle)? I will reopen this bug when you provide additional information for me to look at. Thank you!

**Comment by kwhitaker** [comment]
Sorry for the confusion.

The example works fine in Chrome, but not my code.

One thing I have noticed is that the larger the change (going from a count of 7mill -> 100k) affects the amount of weirdness in the transition.

**Comment by mbostock** [comment]
It certainly looks weird… like the inner and outer radius of the ending edge of the second yellow arc are wrong, but I have no idea why that would be. Perhaps you could try putting your data into the example I linked? Again, I’m happy to investigate if you can help me reproduce this problem.

**Comment by kwhitaker** [comment]
I'll work on getting something online. Thanks!

**Comment by kwhitaker** [comment]
Ok, so the values alone don't seem to cause the problem. Here is your example with the numbers from my API: https://bl.ocks.org/kwhitaker/87cefa0c596cffe51dab46369cf966f3

I'll update the code to reflect what I've written, and see if that causes it here as well.

**Comment by kwhitaker** [comment]
Well, I figured out where the bug was coming from. Turns out it had nothing to do with d3 at all; I had a `transition` in the CSS for my chart paths. Somehow there was a weird intersection between the d3 transition and the css transition in Chrome only.

**Comment by ndobb** [comment]
Wow @kwhitaker your last comment saved me after days of frantically grasping at straws for why my circle objects' transitions were all delayed in Chrome. In my case, I had a css transition: all 0.5s that seemed to be interfering with the d3 transition, causing an odd delay, and only in Chrome.
