### ISSUE TITLE
d3.color.contrastingColor

### ISSUE THREAD

**Issue by IPWright83** [mbostock/d3#2794]
I'd like to propose a new helper function on the various color implementations called `contrast` or `contrastingColor`. 

You often want to display a border or a label on something, who's color should be different to the base color. The `brighter()` and `darker()` functions will do this - but you need to know which to call in the first place. I think it'd be really useful to add a function that'll check the brightness and then  determine if it should return a brigther or darker result automatically. Something like this (modified from one of Mikes examples somewhere):

```
function contrastingColor(rgb) {
    return (rgb.r * 0.299 + rgb.g * 0.587 + rgb.b * 0.114) < 125 ? rgb.brigther(): rgb.darker();
};
```

**Comment by mbostock** [comment]
My personal inclination is that suitable contrasting colors tend to be a matter of taste, and that it’s better to provide an example for people to copy-and-paste than try to build that functionality directly into the library. And at any rate, such a new feature should be implemented in [d3-color](https://github.com/d3/d3-color) for 4.0, if at all.

It’s probably slightly better to convert to Lab space and check the *color*.l channel:

```js
function contrastingColor(color) {
  return (color = d3.lab(color)).l < 50 ? l.brighter() : l.darker();
}
```

Though, I doubt the difference is significant and your weighted-RGB approach is certainly faster.

**Comment by IPWright83** [comment]
I really need to turn my GitHub email notifications back on. 

That's fine Mike, thanks for looking at and at least considering it. That weighted RGB approach is actually yours and not mine ;) I might just extend D3 locally for this purpose.
