### ISSUE TITLE
d3.js does not work in Tor Browser due to CDN censorship

### ISSUE THREAD

**Issue by hdevalence** [mbostock/d3#2799]
When trying to use Tor Browser to view a page which includes from d3js.org, as [is suggested in the docs](https://github.com/mbostock/d3/wiki#installing),

    <script src="https://d3js.org/d3.v3.min.js" charset="utf-8"></script>

loading the script fails, because Cloudflare responds to the JS request with the following response:
```
CF-RAY: 2948f1c1366e25d4-MRS
Content-Encoding: gzip
Content-Type: text/html; charset=UTF-8
...
<head>
<title>Attention Required! | CloudFlare</title>
```
containing an HTML page. The reason is that Cloudflare [censors Tor users](https://blog.torproject.org/blog/trouble-cloudflare), returning captcha pages to "prove you are a human" in response to most HTTP requests. However, the human trying to view the page has no idea that any of this happens -- after all, this request is made by a browser, not a human -- and since browsers (rightfully) reject HTML responses to JS requests,  D3 just silently fails.

This problem can be fixed by whitelisting Tor in the d3js.org Cloudflare settings.

**Comment by mbostock** [comment]
I’ve whitelisted Tor. Thanks for the report.

**Comment by hdevalence** [comment]
Thanks so much!
