### ISSUE TITLE
Why are we not just returning a single element on select

### ISSUE THREAD

**Issue by jrgleason** [mbostock/d3#2813]
I was looking at the select code for some justification support (over JQuery) but I noticed [this](https://github.com/mbostock/d3/blame/master/src/selection/select.js)

```
for (var j = -1, m = this.length; ++j < m;) {
    subgroups.push(subgroup = []);
    subgroup.parentNode = (group = this[j]).parentNode;
    for (var i = -1, n = group.length; ++i < n;) {
      if (node = group[i]) {
        subgroup.push(subnode = selector.call(node, node.__data__, i, j));
        if (subnode && "__data__" in node) subnode.__data__ = node.__data__;
      } else {
        subgroup.push(null);
      }
    }
}
```

Why would we do this instead of....

```
for (var j = -1, m = this.length; ++j < m;) {
    subgroups.push(subgroup = []);
    subgroup.parentNode = (group = this[j]).parentNode;
    for (var i = -1, n = group.length; ++i < n;) {
      if (node = group[i]) {
        subgroup.push(subnode = selector.call(node, node.__data__, i, j));
        if (subnode && "__data__" in node) subnode.__data__ = node.__data__;
        return 
      } 
    }
}
```

Seems like it would save us at least a couple cycles.

**Comment by jrgleason** [comment]
basically the subgroup.push(null) seems useless

**Comment by mbostock** [comment]
Because *selection*.select preserves the index (the structure) of the selection. The implementation has been optimized slightly for D3 4.0 in [d3-selection](https://github.com/d3/d3-selection):

```js
for (var groups = this._groups, m = groups.length, subgroups = new Array(m), j = 0; j < m; ++j) {
  for (var group = groups[j], n = group.length, subgroup = subgroups[j] = new Array(n), node, subnode, i = 0; i < n; ++i) {
    if ((node = group[i]) && (subnode = select.call(node, node.__data__, i, group))) {
      if ("__data__" in node) subnode.__data__ = node.__data__;
      subgroup[i] = subnode;
    }
  }
}
```

See [How Selections Work](https://bost.ocks.org/mike/selection/) for more.

**Comment by jrgleason** [comment]
That looks better but I still don't understand why we couldn't return there we are expecting select to only return 1 value right? Also it looks kinda funny not using map.

**Comment by jrgleason** [comment]
Or maybe rather 1 or the other.

**Comment by jrgleason** [comment]
sorry maybe I don't understand what you mean by `preserves the index (the structure) of the selection`

**Comment by jrgleason** [comment]
Sorry I think I see what you are saying it needs to be a collection returned by select, which I agree with. But the return after the push would still accomplish this, no?

**Comment by mbostock** [comment]
That’s not what *selection*.select does. Please read the API reference for [*selection*.select](https://github.com/d3/d3-selection#selection_select) and perhaps some of the [various D3 tutorials](https://github.com/mbostock/d3/wiki/Tutorials) to learn more.

**Comment by jrgleason** [comment]
Sorry I guess I meant break my head was thinking map I will double che k thanks

**Comment by jrgleason** [comment]
So I had more time to read the blog post and I feel like it goes into extreme detail on selectAll but all I see about select is...

> Another reason selections aren’t literally arrays of elements is that they are arrays of arrays of elements: a selection is an array of groups, and each group is an array of elements. For example, d3.select returns a selection with** one group containing the selected element:**

So my assumption is that it will always be an array subclass with only 1 element. So wouldn't it mean when we were looping the the sizzle results we could return once we got the 1st one?

I am really sorry just trying to make sure I understand.

**Comment by jrgleason** [comment]
nm I see so the push is actually returning 

`[[null]]`

in that case rt?
