### ISSUE TITLE
locale Indian Number System format 

### ISSUE THREAD

**Issue by rohithdaka** [mbostock/d3#2817]
In India, the number system is formatted like this
1 (One)
10 (Ten)
100 (Hundred)
1,000 (Thousand)
10,000 (Ten Thousand)
1,00,000 (One Lakh)
10,00,000 (Ten Lakhs)
1,00,00,000 (One Crore)
10,00,00,000 (Ten Crores)
1,00,00,00,000 (Hundred Crores)
10,00,00,00,000 (Thousand Crores)
1,00,00,00,00,000 (Ten Thousand Crores) 
10,00,00,00,00,000 (One Lakh Crore) 
and it goes on. 

The grouping is 2 except at the beginning. Thousand is written as 1,000 and not as 10,00

Names are not important but I couldn't figure out grouping variable in the pull request I submitted for en-IN locale #2816 

It was mentioned that the array will be cycled through so I can't put [2,3] How do we solve this?

**Comment by mbostock** [comment]
Moved to d3/d3-format#21.
