### ISSUE TITLE
NaNL , MNaN, NaN for attribute x, cy, cx errors from Topojson Datamaps D3 globe

### ISSUE THREAD

**Issue by alexanthony813** [mbostock/d3#2822]
genomie.herokuapp.com/demo/#/map

Earlier, the link above contained an awesome spinning D3/datamaps-powered globe. Now for some reason I am getting this never ending list of errors and no SVG globe. Given the fact that it was working before and that I was using the CDNs in my script tags, I initially thought that it was due to some error with updates to the Topojson or D3 CDN. 

I have verified that the actual values being passed in are in fact numbers. I have also verified that the versions in the script tags alone are certainly not the problem. 

If anyone has ever seen an error remotely like this, I would really appreciate any insight, specifically on what MNaN and NaNL mean. I believe that the cause must be a recently deprecated feature of D3, but this is really my only idea at this point. 

Below is the error log, notice that despite using the non-minified version of d3 it still does not provide a helpful Stack Trace at all. What I have determined from this is that the error is coming from trying to instantiate a new Datamap like below, please keep in mind that this was working perfectly fine.

`    map = new Datamap({
        element: document.getElementById('mainCanvas'),
        scope: 'world',
        projection: 'orthographic',
        geographyConfig: {
            popupOnHover: false,
            highlightOnHover: false
        },
        fills: {
            defaultFill: '#34495e'
        },
        projectionConfig: {
          rotation: rotationNums
        },
        bubblesConfig: {
          popupOnHover: false,
          animate: false,
          highlightOnHover: false
        }
    });`

![Admittedly unhelpful error log, apologies](https://cloud.githubusercontent.com/assets/12706410/15160759/29e20c0c-16b0-11e6-9c06-7f978c1e5b3b.png)

**Comment by jodibean** [comment]
What was your resolution?  We just (out of nowhere) started getting these same errors on some (but not all) of our maps. Nothing has changed on our end, but as we also use the CDN for D3, we're assuming that some new release changed something. TIA.
