### ISSUE TITLE
selection.transition(duration) - Convenience Function

### ISSUE THREAD

**Issue by the-jxc** [mbostock/d3#492]
The following convenience function would be great.  It would allow the programmer to write one piece of code which would very efficiently support the zero duration transition case without incurring the overheard of timers or other additional processing.

```js
d3_selectionPrototype.transition = function(duration) {
  return duration ? this.transition().duration(duration) : this;
};
```

**Comment by mbostock** [comment]
I’m not planning on doing this for D3 4.0. There are a couple of ways to write code that can take either a transition or a selection, and still do special stuff if it’s one or the other. Using `instanceof`:

```js
if (context instanceof d3.transition) {
  // context is a transition
} else {
  // assume context is a selection
}
```

Or by checking for [*transition*.selection](https://github.com/d3/d3-transition#transition_selection):

```js
if (context.selection) {
  // context is a transition
} else {
  // assume context is a selection
}
```

Given that transitions and selections are different interfaces, I think that encouraging ambiguity (as d3.transition(*selection*) did in D3 3.x) is dangerous.
