### ISSUE TITLE
Ordinal scale rangeBand when defined with rangePoints()?

### ISSUE THREAD

**Issue by factormystic** [mbostock/d3#584]
Currently the `rangeBand` property is set to 0 in `scale.rangePoints`, but I'm questioning the usefulness of this. Isn't a rangeBand the `step` width in this context?

I understand that philosophically, if you don't define your scale range via `rangeBands` or `rangeRoundBands` then expecting a value for `rangeBand` might be odd, but practically speaking it's useful to know the width between the range points, which is what I expected `rangeBand` to provide.

**Comment by mbostock** [comment]
I’m redesigning the ordinal scales for 4.0, and I’m happy to report that the new point scale (which replaces ordinal.rangePoints) has a *point*.step method which is equivalent to the proposed rangeStep.
