### ISSUE TITLE
d3.mouse return incorrect position when browser zoomed.

### ISSUE THREAD

**Issue by frogcherry** [mbostock/d3#668]
d3.mouse performs a little strange in mouse events. When the svg did not on the left of screen, if I use the zoom tool of browser, it can’t recognize the location of mouse correctly. It happens in IE9, chrome, safari, opera, only in firefox it works well.

I made a simple **demo** of that: http://walkpie.cnodejs.net/
You can review the demo and download the code in the demo page.

The core part of the demo:
```html
<table>
<tr>
<td width="35%" style="background-color: steelblue;">This is Left.</td>
<td><div id="container"></div></td>
</tr>
</table>
```

```javascript
var vis = d3.select("#container")
    .append("svg")
    .attr("width",600)
    .attr("height",400);

vis.append("rect")
    .attr("width",600)
    .attr("height", 400)
    .attr("style", "fill:none;stroke:red;");

var cl = vis.append("circle")
    .attr("cx", 50)
    .attr("cy", 50)
    .attr("r", 5);

vis.on("mousemove", function(){
    var cp = d3.mouse(this);
    cl.attr("cx", cp[0])
      .attr("cy", cp[1]);
});
```

**Comment by mbostock** [comment]
As far as I can tell, this has been fixed in current browsers. However, it is related to d3/d3-selection#67.
